### ISSUE TITLE
where can I tip ?

### ISSUE THREAD

**Issue by ras0k** [Purfview/whisper-standalone-win#1]
how many hours did you spend on this project, can I pay you for your time?

thank you so much for your help, this is an amazing integration for non-tech-savvy users !

**Comment by ras0k** [comment]
he said there's a tip button on his other repos

**Comment by Purfview** [comment]
You can find donate button on this repo: https://github.com/Purfview/InpaintDelogo

**Comment by Purfview** [comment]
Satan number was received. Thx :P

**Comment by ras0k** [comment]
I wish I could send 10x more… I’ll try to think of you when I get my next check !
