### ISSUE TITLE
CUDA v12 not supported?

### ISSUE THREAD

**Issue by nikich340** [Purfview/whisper-standalone-win#102]
version r160.3_windows:
```
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
[1004] Failed to execute script '__main__' due to unhandled exception!
```
Is there a way to add support for cuda 12.x?

**Comment by Purfview** [comment]
It's written that `GPU execution requires CUDA v11.x`...

> Is there a way to add support for cuda 12.x?

This question belongs there: https://github.com/OpenNMT/CTranslate2

**Comment by Purfview** [comment]
> Is there a way to add support for cuda 12.x?

There is no point in CUDA 12, the tests shows that F"aster-Whisper CUDA v12" has "up" to -10% drop in performance,
So, we can say bye for CUDA v12 till the unforeseeable future. 😆
