### ISSUE TITLE
RuntimeError: Failed to beep

### ISSUE THREAD

**Issue by Purfview** [Purfview/whisper-standalone-win#104]
### Moved to Issues

<div type='discussions-op-text'>

<sup>Originally posted by **ZephyrOtk** November  9, 2023</sup>
Hello, Im facing an error at the end of the transcribe/translate process, however, it doesn't affect the process and still export a subtitle file

> Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 681, in <module>
  File "D:\whisper-fast\__main__.py", line 676, in cli
RuntimeError: Failed to beep
[10580] Failed to execute script '__main__' due to unhandled exception!</div>

**Comment by ZephyrOtk** [comment]
on Windows 11, I run command like this one: 
> whisper-faster "Video-path" -l=en -m=large-v2 -bs=1 -ct=auto -pp --task=transcribe

**Comment by Purfview** [comment]
In what console?

**Comment by ZephyrOtk** [comment]
cmd as admin
Is that right, sorry I dont know too much about IT, just normal user

**Comment by ZephyrOtk** [comment]
Got it, thank you for the information, however, it dont affect the result so I am fine with it.

**Comment by Purfview** [comment]
Yeah, it doesn't affect anything else, just a beep sound.
