### ISSUE TITLE
Additional whisper quantized models

### ISSUE THREAD

**Issue by BBC-Esq** [Purfview/whisper-standalone-win#105]
Would you consider linking my huggingface.co page here:

[https://huggingface.co/ctranslate2-4you](https://huggingface.co/ctranslate2-4you)

It contains a slew of all quantizations of all sizes of whisper models, and v3 is coming soon as well.

**Comment by Purfview** [comment]
No.

**Comment by BBC-Esq** [comment]
> No.

Oh, can I ask why?  Did I offend?

**Comment by Purfview** [comment]
Better question why this should be here.

**Comment by BBC-Esq** [comment]
Um...because you provide a link to [https://github.com/Purfview/whisper-standalone-win](https://github.com/Purfview/whisper-standalone-win), but his models are only in fp16, and I thought fans off ctranslate2 and faster-whisper would appreciate more quantizations without having to convert at runtime.

**Comment by Purfview** [comment]
IMO, that's is not important.

**Comment by BBC-Esq** [comment]
> IMO, that's is not important.

It's your repo, doesn't hurt to ask.  Have a good one dude.

**Comment by Purfview** [comment]
This repo is aimed at newbies, and they shouldn't be overwhelmed by non-important information on the main page.
