### ISSUE TITLE
Update OpenAI's Whisper to latests

### ISSUE THREAD

**Issue by Softwaregnu** [Purfview/whisper-standalone-win#106]
Hi Purfview,

Can you add large-v3 model to Whisper-CPU? Thank you!!

**Comment by Purfview** [comment]
Ha, why do use Whisper and not Faster-Whisper?

I only keep it here for a reference tests, I didn't thought that anyone actually is using it. 😄

**Comment by Softwaregnu** [comment]
Hello, first of all thanks for your project :)

I need to use Whisper on computers with little capacity and very modest hardware, more intended for office automation. They do not have GPUs with CUDA, nor are they from Nvidia (that is why I discard the original OpenAI model and the faster model). That is, I need to use Whisper using a mediocre CPU and RAM, so I can tell you that it takes a long time to complete the task hehe.

The ideal is to run it in CUDA, but the reality is that in many areas there is no such hardware and in the end you have to use what is available. I compiled the project at home from the original OpenAI project and it works very well, I use an RTX 3080. But I would like to be able to use it in the work environment on computers intended for office automation. This is where its execution on CPUs, and not GPUs, comes into play. I saw your project of a portable model (that does not require headaches in installation and configuration) and a version that used the CPU and not the GPU and it has been wonderful. It goes very very slow, but it works.

The only thing I have seen is that it was outdated, without the possibility of using the large-v3 model and that I don't know where the models are downloaded hehehe :) Possibly at work I can only use the tiny, small and perhaps base models, but hey, It never hurts to have the splendid large-v3 model. Thank you!

**Comment by Purfview** [comment]
> I need to use Whisper on computers with little capacity and very modest hardware...  ...not have GPUs with CUDA...

That's another reason why you should use **Faster-Whisper**!  😄

**Comment by Softwaregnu** [comment]
True, I just saw that with the --device=CPU indication it works perfectly!!! thank you :)
