### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Milincho** [Purfview/whisper-standalone-win#111]
Getting this error with a file:

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 687, in <module>
  File "D:\whisper-fast\__main__.py", line 587, in cli
  File "faster_whisper\transcribe.py", line 274, in transcribe
  File "faster_whisper\audio.py", line 52, in decode_audio
  File "faster_whisper\audio.py", line 103, in _resample_frames
  File "faster_whisper\audio.py", line 90, in _group_frames
  File "faster_whisper\audio.py", line 80, in _ignore_invalid_frames
  File "av\container\input.pyx", line 202, in decode
  File "av\container\input.pyx", line 134, in demux
  File "av\container\streams.pyx", line 117, in av.container.streams.StreamContainer.get
IndexError: tuple index out of range
[9376] Failed to execute script '__main__' due to unhandled exception!

**Comment by Purfview** [comment]
Post the command you run.

**Comment by Milincho** [comment]
whisper-faster.exe "\\nonecg\v\Subs\" --output_dir "\\nonecg\v\Subs\" --task translate --language ja --output_format srt --vad_filter True --best_of 5 --beam_size 1 --suppress_tokens -1 --condition_on_previous_text True --temperature_increment_on_fallback 0.2 --compression_ratio_threshold 2.4 --logprob_threshold -1.0 --no_speech_threshold 0.6 --skip

**Comment by Purfview** [comment]
You wrote "Getting this error with a file", what is that mysterious file?

**Comment by Milincho** [comment]
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 86.5 MiB
Duration                                 : 2 min 11 s
Overall bit rate                         : 5 505 kb/s
Frame rate                               : 30.000 FPS
Writing application                      : Lavf58.39.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Format settings, GOP                     : M=4, N=60
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2 min 11 s
Bit rate                                 : 5 502 kb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.022
Stream size                              : 86.5 MiB (100%)
Writing library                          : x264 core 159 r2991 1771b55
Encoding settings                        : cabac=1 / ref=2 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=hex / subme=4 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-1 / threads=48 / lookahead_threads=12 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=120 / keyint_min=60 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=5500 / vbv_bufsize=11000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Codec configuration box                  : avcC

NSFW: https://mega.nz/file/YPFn2ayT#-yfRpWw88mivoIK-yQz3q6BpEEJITzXNgja7u9Q9AZU

**Comment by Milincho** [comment]
I have other files that show the same error, if you need them.

**Comment by Purfview** [comment]
No need, I'll check that file first.

**Comment by Purfview** [comment]
Error happens because there is no audio in that file.

**Comment by Milincho** [comment]
I'm processing a whole folder with many files. Then the correct behavior would be to skip that file and continue to the next, right?

This other file has audio ( NSFW https://mega.nz/file/4XVCHZKL#KIVMnsOnKUjgs6W5JgrbNyprBHLqvUMg8p8YAMC2ggs ) and shows the problem:


Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 704, in <module>
  File "D:\whisper-fast\__main__.py", line 604, in cli
  File "faster_whisper\transcribe.py", line 274, in transcribe
  File "faster_whisper\audio.py", line 52, in decode_audio
  File "faster_whisper\audio.py", line 103, in _resample_frames
  File "faster_whisper\audio.py", line 90, in _group_frames
  File "faster_whisper\audio.py", line 80, in _ignore_invalid_frames
  File "av\container\input.pyx", line 202, in decode
  File "av\container\input.pyx", line 181, in demux
  File "av\container\streams.pyx", line 63, in av.container.streams.StreamContainer.__getitem__
  File "av\container\streams.pyx", line 106, in av.container.streams.StreamContainer.get
IndexError: list index out of range
[22128] Failed to execute script '__main__' due to unhandled exception!

**Comment by Purfview** [comment]
> Then the correct behavior would be to skip that file and continue to the next, right?

From my point of view that would be the incorrect behavior.

**Comment by Milincho** [comment]
> > Then the correct behavior would be to skip that file and continue to the next, right?
> 
> From my point of view that would be the incorrect behavior.

If you are automatically processing a folder with hundreds of files, you don't want the whole process to stop because *one* file fails.

This should be an option at least.

**Comment by Purfview** [comment]
The program needs audio to work, if you feed it non-audio it will crash, and it should. 

Some code would need to be implemented to check the files first and weed out non-audio.

Or you can batch process files one by one, read there -> https://github.com/Purfview/whisper-standalone-win/discussions/29

**Comment by Milincho** [comment]
> The program needs audio to work, if you feed it non-audio it will crash, and it should.

It is crashing also with the .flv, which does have audio, and stops the whole process.

> Or you can batch process files one by one, read there -> #29

"It can have significant overhead as it will reload executable and model on every file"

**Comment by Purfview** [comment]
> It is crashing also with the .flv, which does have audio

Upload it somewhere.

> "It can have significant overhead as it will reload executable and model on every file"

I know, I wrote that.

**Comment by Milincho** [comment]
> > It is crashing also with the .flv, which does have audio
> 
> Upload it somewhere.

Already did and posted it: 

This other file has audio ( NSFW https://mega.nz/file/4XVCHZKL#KIVMnsOnKUjgs6W5JgrbNyprBHLqvUMg8p8YAMC2ggs )

> > > "It can have significant overhead as it will reload executable and model on every file"
> 
> I know, I wrote that.

So there isn't any better way to do it? ok, then how can I feed it differetn video formats? 

Can I just put:

for %%f in (*.mp4 *.m4v *.mkv *.avi *.mov *.mpg *.mpeg *.wmv *.divx *.xvid) do call set list=%%list%% "%%f"

or does it needs , or ; to separate the different file extensions?

**Comment by Milincho** [comment]
More problems...   🤦🏻

"CMD does not support UNC paths"

**Comment by Purfview** [comment]
> So there isn't any better way to do it?

You could write some function to "check the files first and weed out non-audio".

>ok, then how can I feed it different video formats?

https://stackoverflow.com/questions/56495133/batch-file-searching-for-multiple-file-formats-in-for-loop

> "CMD does not support UNC paths"

Try different consoles, maybe PowerShell supports them.

**Comment by Purfview** [comment]
Check this test build: https://we.tl/t-T1AibifMI1

And test `--check_files` argument.

**Comment by Milincho** [comment]
File errors still stop the process.

Like with these 2 videos: https://mega.nz/file/xHVDAD7b#_Ur9PPp_Fe9W_9N0LitVqjsKtVpFzMiZIdzozXzz8U0
https://mega.nz/file/8DskwCyJ#0sYv5OMjdzovOyVeJQK4iWRO_i1AlDpnfcOmn6IAiOA

**Comment by Purfview** [comment]
> File errors still stop the process in that test build.

Not for me, tested the first file.

**Comment by Milincho** [comment]
> > File errors still stop the process in that test build.
> 
> Not for me, tested the first file.

Sorry, I forgot to properly add the --check_files 2 setting.

It works now. Many thanks! 😊

Why I don't get (in my total ignorance about coding, I know) is why isn't it easier to make a setting that allows the program to continue with the next files if one shows an error, than to check all the files for errors first...

**Comment by Purfview** [comment]
You can't "allow to continue" if program is already crashed.

**Comment by Milincho** [comment]
I'm getting a "File extends beyond end of segment." message at the start of the process with some files. 

Is this something I should be worried about? i don't want to open another "issue" if it isn't important...

**Comment by Purfview** [comment]
Below "Starting transcription on:" message?
Then it's just a warning/info about non-standard file, not important.

**Comment by Purfview** [comment]
Implemented in `r160.7` as `--check_files` switch.
Doesn't take arguments. It's using 2nd option from beta.

**Comment by gkngkngkn** [comment]
"--check_file"  this parameter can automatically skip files without audio. 

However, when encountering some error files that cannot be played (I am transcribing thousands of videos in batches, so it is almost impossible to manually identify individual error files), the entire process will still terminate.

I try to refer to the method in comment #29 and transcribe one by one. but I didn't quite understand that post, If I transcribe one by one, it can only be done for files within a single folder, right?

Currently, I need to process folders that contain multiple subdirectories, and each subtitle file is saved in its corresponding subfolder.

here is my parameter whisper-faster.exe "E:\study" --device cuda --language en --model medium.en --compute_type int8 --batch_recursive --skip

**Comment by Purfview** [comment]
> However, when encountering some error files that cannot be played (I am transcribing thousands of videos in batches, so it is almost impossible to manually identify individual error files), the entire process will still terminate.

This shouldn't happen, I think. Can you share such file?

> I try to refer to the method in comment https://github.com/Purfview/whisper-standalone-win/discussions/29 and transcribe one by one. but I didn't quite understand that post, If I transcribe one by one, it can only be done for files within a single folder, right?

No limited, limited only to your skill in writing the batch scripts.

**Comment by gkngkngkn** [comment]
### This shouldn't happen, I think. Can you share such file?
Later, I understood the reason. It turns out that these few files couldn't be played on my external hard drive, but they worked fine once I moved them to the local hard drive.

###Not limited, limited only to your skill in writing the batch scripts, or Google for such.
If you don't know how to write complicated scripts then you can simply generate a list with all the files then just add whisper commands in every line with some text editor, that's it.

i will try it thx.

**Comment by gkngkngkn** [comment]
I understood the reason later, It turns out that these few files couldn't be played on my external hard drive, but they worked fine once I moved them to the local hard drive. it works now :)


> Not limited, limited only to your skill in writing the batch scripts, or Google for such.
> If you don't know how to write complicated scripts then you can simply generate a list with all the files then just add whisper commands in every line with some text editor, that's it.
i will try it thx.
