### ISSUE TITLE
Hi How can I contact you?

### ISSUE THREAD

**Issue by shruru** [Purfview/whisper-standalone-win#114]
Hi Purfview, I am newbie regarding the ASR but I found you are good at it via SubtitleEdit with the fast-whsiper, what's your email I am willing to pay for some things to be done. Thanks a lot 🙏🏻
my: shawnforum[at]gmail.com

**Comment by Purfview** [comment]
purfview at protonmail.com

**Comment by shruru** [comment]
thanks
