### ISSUE TITLE
make --skip option to also skip media file if subtitle exists in the output folder

### ISSUE THREAD

**Issue by Milincho** [Purfview/whisper-standalone-win#115]
Could you make --skip option to also skip media file if subtitle already exists in the output folder, besides the same folder?

**Comment by Milincho** [comment]
Also, when using a whole folder as input, an option to also process all its subfolders would be useful too.

**Comment by Purfview** [comment]
> Also, when using a whole folder as input, an option to also process all its subfolders would be useful too.

This one is available already wirh `-br` or `--batch_recursive`.

Btw, with recursive and outputting subs to a one folder then they can overwrite the ame named files.

**Comment by Milincho** [comment]
> Btw, with recursive and outputting subs to a one folder then they can overwrite the same named files.

Mmm...   I think that's the opposite.

My workflow is as follows:

I have a folder with media files, which also has many other subfolders with files in various sublevels.

I want to process all those files and output the subtitles to a specific "V:\Subtitles" folder, containing all the generated subtitles.

When I add more media files to that media folder and its subfolders structure, I want for whisper-faster to process all again, skipping all the already generated subtitles that are currently on that "V:\Subtitles" folder.

**Comment by Milincho** [comment]
And btw, does the --skip and --check_files options work together so only files with no currently generated subtitles are checked? 🤔

**Comment by Purfview** [comment]
> And btw, does the --skip and --check_files options work together so only files with no currently generated subtitles are checked?

Yes.

> Could you make --skip option to also skip media file if subtitle already exists in the output folder, besides the same folder?

Check this test build: https://we.tl/t-LLtO5mNxgA

**Comment by Milincho** [comment]
It crashes with .flv files like this one (nsfw): https://mega.nz/file/ALFn1CrS#6a34cvhP1b7k1hteC7-CxAgZz_WHnvIj_FqlIOIHiWQ

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 807, in <module>
  File "D:\whisper-fast\__main__.py", line 706, in cli
  File "faster_whisper\transcribe.py", line 274, in transcribe
  File "faster_whisper\audio.py", line 52, in decode_audio
  File "faster_whisper\audio.py", line 103, in _resample_frames
  File "faster_whisper\audio.py", line 90, in _group_frames
  File "faster_whisper\audio.py", line 80, in _ignore_invalid_frames
  File "av\container\input.pyx", line 202, in decode
  File "av\container\input.pyx", line 181, in demux
  File "av\container\streams.pyx", line 63, in av.container.streams.StreamContainer.__getitem__
  File "av\container\streams.pyx", line 106, in av.container.streams.StreamContainer.get
IndexError: list index out of range
[20316] Failed to execute script '__main__' due to unhandled exception!

**Comment by Purfview** [comment]
Did you used --check_files?

**Comment by Milincho** [comment]
When I use --check_files it excludes them all, but those files play without players in the video player, so isn't it a problem with the flv format itself?

**Comment by Purfview** [comment]
> ...so isn't it a problem with the flv format itself?

Shouldn't be. Something must be not right with that file. Try to remux it with MKVToolNix or similar.
