### ISSUE TITLE
Is very Good, I can use it ,Thanks

### ISSUE THREAD

**Issue by super-crayfish** [Purfview/whisper-standalone-win#116]
![image](https://github.com/Purfview/whisper-standalone-win/assets/17097939/34a4fd3c-dd2d-4411-8649-09c73fcd1887)

视频提取音频
ffmpeg -i 222.mp4 -vn -b:a 128k -c:a mp3 output.mp3

截取4秒后的音频 
ffmpeg -i output.mp3 -ss 4 -c copy output2.mp3

使用 whisper-faster.exe  生成字幕 

whisper-faster.exe  output3.mp3 -l=Chinese --model=medium --output_format srt

**Comment by Purfview** [comment]
No need to use ffmpeg:

whisper-faster.exe 222.mp4 -l=Chinese --model=medium
