### ISSUE TITLE
Use current working dir or the dir where the video/audio file is at as default output_dir

### ISSUE THREAD

**Issue by fireattack** [Purfview/whisper-standalone-win#117]
Currently the file by default saves to where the executable is at, which is weird.

I think it should either save to CWD or where the video file is at.

Consider the following:

```
D:\>C:\software\whisper-faster E:\1min.wav --model small --output_format srt
```

I think the output should be either `D:\1min.srt` or `E:\1min.srt`.

I tried a few other whisper CLIs (including the original official one and whisper-ctranslate2) and they seem to all choose CWD as default `ouptut_dir`.

**Comment by cagenuts** [comment]
just use `-o=source` it's right there in the help.
