### ISSUE TITLE
Conflict between Faster-Whisper-Standalone and another Whisper variant

### ISSUE THREAD

**Issue by oep42** [Purfview/whisper-standalone-win#12]
I've been testing different variants of Whisper, including Faster-Whisper-Standalone. I tested Faster-Whisper-Standalone (version 2023.5.13.117) with a short video, first with the Windows Command Prompt, and after that with Subtitle Edit. This worked fine. [I had made a copy of Faster-Whisper-Standalone's `C:\Whisper-Faster\whisper.exe`, like this: `C:\Whisper-Faster\whisper-ctranslate2.exe`, to be used with Subtitle Edit.]

After that, I installed other variants of Whisper which are supposed to be used with the Command Prompt.

After that, I could still use Faster-Whisper-Standalone with Subtitle Edit, but it was not possible anymore to use Faster-Whisper-Standalone with the Command Prompt. (I don't know after which additional install, this problem appeared.)

I found out, that this had happened:

- I discovered this program: `C:\Program Files\Python310\Scripts\whisper.exe`. (I suppose this had been installed with one of the other Whisper variants that I installed after I tested Faster-Whisper-Standalone as described above.)
- I discovered, that when I tried to use Faster-Whisper-Standalone like this `whisper "D:\videofile.mkv" --language=English --model=medium`, not `C:\Whisper-Faster\whisper.exe` was being run, but `C:\Program Files\Python310\Scripts\whisper.exe`. So, apparently, somewhere in my system, it was set, that when I use "whisper" in the Command Prompt, `C:\Program Files\Python310\Scripts\whisper.exe` will be used. 
{{{If I temporarily change the name of `C:\Program Files\Python310\Scripts\whisper.exe` into `C:\Program Files\Python310\Scripts\@@@whisper.exe`, and then run the command `whisper "D:\videofile.mkv" --language=English --model=medium` again, then this results in this error message: _The term 'whisper' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again_.}}}

'Installing' Faster-Whisper-Standalone again, is not a solution, because the setting, somewhere in my system, is that `C:\Program Files\Python310\Scripts\whisper.exe` will be used whenever I run `whisper` from the Command Prompt. I guess that this setting will only diasappear, when I uninstall all other variants of Whisper that I have installed, but I am not really willing to do that.

**Suggestion**
I suggest to change the name of Faster-Whisper-Standalone's file "whisper.exe" into something else like "whisper-fwsa.exe", or something like that, to prevent a conflict with another installed variant of Whisper. 
I am not sure if this is really a solution for me, because, when I use the command `whisper-ctranslate2 "D:\videofile.mkv" --language=English --model=medium` (here I am calling a renamed copy of "whisper.exe"), then the error message "_The term 'whisper-ctranslate2' is not recognized as the name of..._" always appears now. [There is no other file "whisper-ctranslate2.exe" in my system than `C:\Whisper-Faster\whisper-ctranslate2.exe`.] So in the end, I may have to remove 'everything Whisper' from my system, in order to be able to use Faster-Whisper-Standalone again in the Command Prompt.
Perhaps the problem is not just with the name of the Faster-Whisper-Standalone exe-file (`C:\Whisper-Faster\whisper.exe`), but with what is inside that file. If 'inside' that file, it is supposed to run something called "whisper", that may have to be changed too.

**Additional remark**
When I run Whisper when the model to be used with that, has been downloaded before, I have Whisper blocked in my firewall, because then there is no need for Whisper to connect to the internet. When whisper tries to download a model when the internet is blocked, Whisper creates the folder where it wants to place that model, before crashing because that download fails. 
I noticed that `C:\Whisper-Faster\.cache` has been created (with empty subfolders where a model is supposed to be) during working with Faster-Whisper-Standalone, as if Faster-Whisper-Standalone wants to download the models there also. I have no idea why this happened, and if that's what is meant to happen. See the image below.

![Whisper-Faster- cache](https://github.com/Purfview/whisper-standalone-win/assets/84353335/ff8b0037-d9b1-4143-a643-dc444fe23be2)

**Comment by Purfview** [comment]
There is no conflict, you renamed executable and you are trying to run it by different filename. You need to run by its actual filename.

**Comment by oep42** [comment]
It does not make a difference whether `.exe` is included in the command or not. When `C:\Program Files\Python310\Scripts\whisper.exe` is temporarily made 'invisible' by changing its name into `C:\Program Files\Python310\Scripts\@@@whisper.exe`, this is what happens when using "whisper" and "whisper.exe" in the command:

![Running 'whisper' and 'whisper exe'](https://github.com/Purfview/whisper-standalone-win/assets/84353335/28d26f5b-8bfa-4524-8072-3b87dafc4a32)

**Comment by Purfview** [comment]
This repo has nothing to do with whatever you installed with Python.

I don't understand what you are trying to do here, why you are renaming that executable and why your are trying to call it by non existent name?

**Comment by Purfview** [comment]
And you need to call executables from a path where it's located or with path, unless you add path to PATH environment cariable.

**Comment by Purfview** [comment]
> Additional remark

SE download problems have nothing to do with this repo.

**Comment by oep42** [comment]
I am sorry if I have been unclear.

I don't know how Python works, so all I'm doing here, is guessing. (I would be very happy if anyone with Python knowledge would chime in here.)

The fact is, that at first, on "day 1", Faster-Whisper-Standalone worked fine with the Command Prompt. And a day later, on "day 2", it didn't work anymore. What did I do in between? Installing and trying various other Whisper variants. I cannot think of anything else that changed in between, that may have caused Faster-Whisper-Standalone-Command to fail. 

When I tried, on day 2, to run Faster-Whisper-Standalone-Command again, another variant of whisper started. I guess that this other variant is one of the variants that I had installed between day 1 and day 2.

When looking into this, I found out, that there were indeed two "whisper.exe" files in my system, (1) one which belongs to Faster-Whisper-Standalone [`C:\Whisper-Faster\whisper.exe`], and (2) one which belongs to another Whisper variant [`C:\Program Files\Python310\Scripts\whisper.exe`] I couldn't find out to which other Whisper variant this second "whisper.exe" belongs. (I guess that this second "Whisper.exe" was not in my system on day 1.)

I guess that this has happened:
During the installation (between day 1 and day 2) of one of the other Whisper variants (which includes a "whisper.exe" file), somewhere in my system was set, that whenever a command that starts with "whisper" (or "whisper.exe") is used in the Command Prompt, this newly installed "whisper.exe" will be used, and not the "whisper.exe" which belongs to Faster-Whisper-Standalone.
Since then, whenever I use a command that starts with "whisper" (or "whisper.exe"), this newly installed variant of Whisper is being used, effectively blocking the use of Faster-Whisper-Standalone-Command.

A way to test whether Faster-Whisper-Standalone's "whisper.exe" is indeed blocked in that way (by some setting somewhere in my system), is to remove the other "whisper.exe" from the system, and then run a command that starts with "whisper". When the other "whisper.exe" is removed, only Faster-Whisper-Standalone's "whisper.exe" remains on the system. 

When [1] only Faster-Whisper-Standalone's "whisper.exe" is on the system; and [2] a command that starts with "whisper" (or "whisper.exe") is used; and [3] when that command then fails because "whisper" (or "whisper.exe") cannot be found, then I can imagine only one explanation for this: There is a setting in the system, that makes the system look only in the location of the other "whisper.exe". So then the system looks exclusively for `C:\Program Files\Python310\Scripts\whisper.exe`, and it does not look for `C:\Whisper-Faster\whisper.exe`. This "[1] [2] [3]" is what happened, and this is what I tried to describe above.

Instead of removing the other "whisper.exe" from the system, it is also possible to (temporarily) rename it. In this context, this renaming has the same effect as removing it from the system. I chose to use this 'rename trick', instead of removing the other "whisper.exe" from the system.

So my guess is, that when the command Prompt is used, Faster-Whisper-Standalone's "whisper.exe" is blocked by a setting somewhere in the system.

If this guess is correct, then this is, I am afraid, not true:

> This repo has nothing to do with whatever you installed with Python.

Both Faster-Whisper-Standalone-Command and the other Whisper variant, use the Command Prompt. I believe, that whenever a command that starts with "whisper" (or "whisper.exe") is given, the Command Prompt, i.e. the system, decides what to do, and not what's in "C:\Whisper-Faster\whisper.exe".

> And you need to call executable from a path where it's located or with path, unless you add path to PATH environment variable.

I believe that there is, within Windows, an alternative way to find executables, like info somewhere in the Windows Registry, that whenever a command that start with "whisper" is given, a specific "whisper.exe" file that is at a specific location, is executed. Such info can be added to the Registry when a program is installed.

> SE download problems have nothing to do with this repo.

Fully agreed. (I never suggested this. Sorry if I gave the impression to suggest this.)

**Comment by Purfview** [comment]
You are repeating same thing as in your first post.

Please describe your issue in one sentence and one issue per thread please.

**Comment by oep42** [comment]
> I don't understand what you are trying to do here


From this I understood, that you wanted me to explain more. Please try to understand that I have tried very hard to explain as clearly as possible what I was trying to say.

> Please describe your issue in one sentence and one issue per thread please.


My issue is this: After I installed other Whisper variants, Faster-Whisper-Standalone for Command Prompt, stopped working.

**Comment by Purfview** [comment]
I don't know what means "stopped working".

**Comment by oep42** [comment]
I want to create subtitles for a video with Faster-Whisper-Standalone for Command Prompt. First this was possible. Now, after installing other Whisper variants, that is not possible anymore. (= Now Faster-Whisper-Standalone for Command Prompt, does not work anymore.)

There is no error message, because Faster-Whisper-Standalone for Command Prompt simply does not run at all anymore (because it is blocked now, I guess).

**Comment by Purfview** [comment]
If there is no error then it works.

**Comment by oep42** [comment]
> If there is no error then it works.

Sorry, if it doesn't run, it doesn't work.

Please don't turn this into a play on words.

**Comment by Purfview** [comment]
Then why you refuse to provide "error"? Abstractions like "doesn't work" doesn't describe your problem in any way.

**Comment by oep42** [comment]
> Then why you refuse to provide "error"?

Again, I cannot produce an error, because there is no error. 

Compare this with a tool you would like to use, but which is somehow out of reach.
That "being out of reach", that is the problem here.

**Comment by Purfview** [comment]
Then make a screenshot of what is in the screen, what is there behind of alleged "invisibility".

**Comment by oep42** [comment]
Please do not edit (and mostly delete) my earlier comment here. That is rather unsportsmanlike. Here is my earlier comment that you "destroyed" by editing it:

#######################################

> Then why you refuse to provide "error"?

Again, I cannot produce an error, because there is no error. 

Compare this with a tool you would like to use, but which is somehow out of reach.
That "being out of reach", that is the problem here.

The problem is, that Faster-Whisper-Standalone for Command Prompt, cannot be started.

#######################################


I think I have explaned enough for now.

Again, in one sentence, the essence of the problem: 
**Faster-Whisper-Standalone for Command Prompt cannot be started.**

Please be so kind to take this serious.

**Comment by Purfview** [comment]
>Please do not edit (and mostly delete) my earlier comment here. That is rather unsportsmanlike.

I didn't noticed that instead of reply I edited you post, so sorry for that, now I restored it.

>I think I have explaned enough for now.

But you explained nothing. "Doesn't work" or "invisible" - that's not how computers work.
If you don't understand how computers work then post a screenshot of the issue, abstract fantasies won't help here.
