### ISSUE TITLE
Faster-Whisper - Last sentence missing

### ISSUE THREAD

**Issue by Dean-Corso** [Purfview/whisper-standalone-win#133]
Hi @Purfview,

Sometime it stops at 99% and does skip the rest of the seconds to check but why? When I do check the results in output files then there are missing some text / last sentence at the end. When I just cut the video at the end maybe the last minute and use this short video again with Whisper / same Model & settings as I used in full video then I get one more sentence out (last one). Is there any reason why I don't get that last sentence when I use Whisper on the entire video?

**Comment by Purfview** [comment]
What version?

**Comment by Dean-Corso** [comment]
So I just used the latest version r160.10. Can't check the same again with older version so then I have to wait again a longer time till Whisper is finished. I'm using CPU device. Just as info, not sure whether it's important or not.

I have another little question about the languages I do set in Whisper (just asking here if you don't mind because it's a small question). I was using English with the  --language for some English speeches which seems to work good but then I tried using it with some German language speech (News) and see that not sentence has any dot (punctuation) so all was written without comma, dot etc. When I do use the  --sentence parameter then I get just one big sentence out. Can I do anything about it?

**Comment by Purfview** [comment]
I just need JSON file and srt, where you have "last sentence missing".

> r160.10

This is not "Whisper".

**Comment by Purfview** [comment]
> I tried using it with some German language speech (News) and see that not sentence has any dot

Look there at the very end: https://github.com/Purfview/whisper-standalone-win/discussions/130

**Comment by Dean-Corso** [comment]
The last sentence is not written into any output file. Not in SRT / VTT / JSON etc it's just missing because I did recognize it by watching the video first and then I did check all output files and was surprised that there is something missing. When I watch the full video at end then I can see the PRE last sentence whish is displaying in video player and right after there should come another sentence (person in video is talking another sentence) but there comes nothing anymore. After that I did cut the last minute separated and did use Whisper again and in this short last minute video Whisper does print the last sentence out in all files & CLI window too. So you think it's an Model issue? I was using medium Model with English language and also trying the tiny.en Model but there is the last sentence also missing when I use it with the entire video. Below 2 images I made. First of full video...
![Missing_2023-12-04_235005](https://github.com/Purfview/whisper-standalone-win/assets/88513086/40d345fe-5b4d-4245-b96d-db2f1208e7f7)
...the last sentence which was logged "00:30:38,630 --> 00:30:40,610" = 1838 - 1840 and in CLI title you can see its just checking till second 1841 only.

Now the short 58 seconds video...
![Missing2_2023-12-04_235005](https://github.com/Purfview/whisper-standalone-win/assets/88513086/73265685-67a4-40f4-9b9b-53e560383a97)
...so somehow Whisper or Model do not check all seconds and stop before (19 secs in full video and 6 secs too early in short video). What is the problem in that case?

About punctuation issue with German language. I tried using that another command "-prompt=None" and now it's better but I did not found that command in help file. What about that --prefix=* command. Somehow I don't understand the description of it what it does. What was custom prompt I could see on the image you did post?

**Comment by Purfview** [comment]
> The last sentence is not written into any output file.

Then problem is in the model I think. Better share the audio.

> and in CLI title you can see its just checking till second 1841 only

Does that percentage stays in the title when operation is finished?
As I remember there is no progress update of the last chunk, because it disappears from the title anyway. Try `--pp`.

**Comment by Purfview** [comment]
> ..running till 100% but in this case not..

Wrote you already that you are wrong, why you are even repeating this nonsense...

> Sure, on the image I did post you can see that "Operation finished in: XY seconds".

Strange, that it stays for you in the title. OK, then I'll allow it in the next release, to update the title with the last progress update.

> Do you have any clue what input format would be best using it with Whisper?

Original. There is no best, any nano change in audio can affect model transcribing randomly different, but generally it won't be better or worse.

> ...want Whisper to create a SRT / VTT etc file from time code X to time code Y.

You can't do this. Cut your file first to whatever you like. For example with MkvToolNix. 

> ...but the last sentence is still missing. 

Not much of a problem. sometimes the half of an audio is missing. 😆

Closing this as there is no point in fantasizing on stuff without the sample.
