### ISSUE TITLE
blank text issue

### ISSUE THREAD

**Issue by llurk** [Purfview/whisper-standalone-win#135]
I also made a post on Subtitle Edit. This error occurs with the medium, large v1-3 models. Are there any ways to fix it?
![Screenshot 2023-12-08 000526](https://github.com/Purfview/whisper-standalone-win/assets/134845325/294f00a0-735f-4499-ae00-f75ded4cca77)

https://github.com/SubtitleEdit/subtitleedit/issues/7711#issue-2030435127

**Comment by Purfview** [comment]
Share the audio with the problem.

**Comment by llurk** [comment]
#[https://github.com/SubtitleEdit/subtitleedit/issues/7711#issue-2030435127](url)

**Comment by llurk** [comment]
Sorry, that file is approximately ~3GB. I usually use faster-whisper for Chinese and Japanese files.

**Comment by Purfview** [comment]
I don't need video, just audio. You can remux just audio with MkvToolNix.

**Comment by llurk** [comment]
https://drive.google.com/file/d/1zZ8RZYyuk-ENx3cZIIwhFteEWq0c2s8O/view?usp=drive_link
https://drive.google.com/file/d/1Uv07zJvLKNVyZomp-3LZU37MB3xigcho/view?usp=drive_link

**Comment by llurk** [comment]
Are you encountering that error in the file? I extracted it from videos that ranged from 1 to 3 hours, and the appearance of the error varies depending on the specific file. I can edit short files, but longer ones are quite challenging.

**Comment by Purfview** [comment]
Are you encountering that error in the file?

No.

Better share the `json` file, you can get it with `-f=all` option.

**Comment by Purfview** [comment]
Another output format. The file with `json` extension.

**Comment by llurk** [comment]
No JSON file is available. I executed the 'faster-whisper.exe' file in the terminal using version 160.10, with manually downloaded DLL files, and applied the large-v3 model. The returned results differ significantly from the version processed in Subtitle Edit. In SE, some lines occasionally exceed 200 characters, and the error resembles the one shown in the image I posted. I am also perplexed as to why this occurred.

**Comment by Purfview** [comment]
Probably you have enabled post-process options in SE, then probably your issue is not with Faster-Whisper at all.

Disable them! You can use `--standard_asia` switch to shape too long lines.

**Comment by Purfview** [comment]
> No JSON files are available.

`-f=all`

**Comment by llurk** [comment]
> Probably you have enabled post-process options in SE
No. i don't know optimize syntax, I just used the default configuration in SE.

**Comment by Purfview** [comment]
Oh, there is another thing with SE, read there -> https://github.com/SubtitleEdit/subtitleedit/issues/6946

> I just used the default configuration in SE.

Post-process is enabled by default in SE.

**Comment by Purfview** [comment]
There shouldn't be blank lines from Faster-Whisper.

**Comment by Purfview** [comment]
I'm closing this, unless you show me `JSON` file with blank lines.

**Comment by Purfview** [comment]
In terminal if you use it directly or in advanced options in SE.

**Comment by Purfview** [comment]
For example:

`whisper-faster.exe "D:\myvi.mkv" --language=Chinese--model=medium --standard_asia -f=all -o=source`

**Comment by Purfview** [comment]
> Oh, where can I start learning?

How to use terminal? Maybe start there -> https://www.youtube.com/watch?v=A3nwRCV-bTU

What exactly are keywords?

`whisper-faster.exe --help`

**Comment by llurk** [comment]
Running the code in the terminal yields good results but is quite time-consuming. Could you provide me with an optimized command for executing faster-whisper specifically tailored for Japanese and Chinese?

**Comment by Purfview** [comment]
> This `-f=all` increases the execution time of Subtitle Edit by nearly 3 times. 

That's impossible, converting formats is instant. Faster than an eye blink. 😄

There are no blank lines in your json.

> Running the code in the terminal yields good results but is quite time-consuming. 

It's time-saving! 😆

**Comment by Purfview** [comment]
I can only answer about the files produced by `whisper-faster.exe`, about SE ask in SE repo.

**Comment by llurk** [comment]
Okay, I have obtained the results I needed. Thank you

**Comment by Purfview** [comment]
>There is some errors in the srt file created simultaneously with the JSON file.

Then share that file.
**Not the file saved with SE.**
