### ISSUE TITLE
RuntimeError: CUDA failed with error out of memory

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#141]
I have a different problem. It seems that either somehow or I don't know how to determine it, but I keep getting some errors, I'm sending the logs.
[whisper_log.txt](https://github.com/Purfview/whisper-standalone-win/files/13660107/whisper_log.txt)

**Comment by Purfview** [comment]
Can you share the audio sample to reproduce it?

**Comment by nielka98** [comment]
yes but tomorrow

**Comment by nielka98** [comment]
I won't share it for now because I have a different problem. It seems that either somehow or I don't know how to determine it, but I keep getting some errors, I'm sending the logs.
[whisper_log.txt](https://github.com/Purfview/whisper-standalone-win/files/13660107/whisper_log.txt)

**Comment by nielka98** [comment]
For now, I'm trying to fix it myself

**Comment by nielka98** [comment]
I'm also wondering whether the errors may be caused by the fact that I have extremely low memory on the C drive and here's my question: Is it possible to move it to the D drive?

**Comment by Purfview** [comment]
One issue per thread please.

> I won't share it for now because I have a different problem. It seems that either somehow or I don't know how to determine it, but I keep getting some errors, I'm sending the logs. [whisper_log.txt](https://github.com/Purfview/whisper-standalone-win/files/13660107/whisper_log.txt)

Here you have `RuntimeError: CUDA failed with error out of memory` error.
That's because you don't have enough VRAM. What is GPU model and how much VRAM it has?
Try to remove  `-bs=10` parameter you are using there and use `-bo=1`.
