### ISSUE TITLE
Amara.org

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#144]
Hey, I think I found an interesting error and I'm wondering how to fix it. Maybe someone had this too. Well, no matter what subtitles it generates on Whisper in the second version, the beginning always sounds identical, it makes the beginning of only the same subtitles of this type: "Sottotitoli creati dalla comunità Amara.org." and then it generates normally. Does anyone know how to fix?

**Comment by Purfview** [comment]
I wrote you before, post a sample!

**Comment by nielka98** [comment]
https://drive.google.com/file/d/1VJw6PFeUOgL_xDPTi5bjrjZWb9cuVZZH/view?usp=sharing

**Comment by nielka98** [comment]
> Już Ci pisałam, wrzuć próbkę!



> I wrote you before, post a sample!
but this happens with every video I transcribe

**Comment by Purfview** [comment]
And what settings do you use? And srt file would help too.

**Comment by nielka98** [comment]
> What settings do you use? 
-bs=10 -bo=10 --temperature_increment_on_fallback=None
And srt file would help too.
i dont't have :(

**Comment by Purfview** [comment]
You didn't posted what model do you use and what compute_type.

> -bo=10 --temperature_increment_on_fallback=None

There is no point in setting `-bo` when you are disabling it with disabled fallback.

> i dont't have :(

Then post what you have.

**Comment by albino1** [comment]
https://github.com/openai/whisper/discussions/928

**Comment by nielka98** [comment]
> You didn't posted what model do you use and what compute_type.
> Whisper large version two
> > -bo=10 --temperature_increment_on_fallback=None


> Then post what you have.

If you want, I can share the log with you...

**Comment by nielka98** [comment]
> [openai/whisper#928](https://github.com/openai/whisper/discussions/928)

but it doesn't help me anyway because I use whisper in editing subtitles edit

**Comment by Purfview** [comment]
large-v2:

```
[01:25.500 --> 01:38.030]  C'era chi pensava a noi, duro sei tu.
[01:39.330 --> 01:47.000]  E lui ti fava perduta ma assurdi,
[01:48.100 --> 01:52.220]  con la speranza e la voglia di vivere,
[01:52.540 --> 01:55.240]  coltiva la vita sua.
[01:56.340 --> 01:59.560]  Era lui, pronto salto.
```

That's without `-bs=10`.

**Comment by Purfview** [comment]
Btw, if it's musical then you would want to lower `--vad_threshold` as vad cuts out random parts from songs, maybe set it to `0.3`.

**Comment by nielka98** [comment]
> duży-v2:
> 
> ```
> [01:25.500 --> 01:38.030]  C'era chi pensava a noi, duro sei tu.
> [01:39.330 --> 01:47.000]  E lui ti fava perduta ma assurdi,
> [01:48.100 --> 01:52.220]  con la speranza e la voglia di vivere,
> [01:52.540 --> 01:55.240]  coltiva la vita sua.
> [01:56.340 --> 01:59.560]  Era lui, pronto salto.
> ```
> 
> To bez `-bs=10`.

how??

**Comment by Purfview** [comment]
I wrote - `large-v2`. Using latest `r160.11` version.

**Comment by nielka98** [comment]
But wait, you use it in the program or in the console

**Comment by Purfview** [comment]
In console.

**Comment by nielka98** [comment]
This changes things.... Because I don't know how to use the console whispr

**Comment by Purfview** [comment]
If you use `ffmpeg v5.xx` in SE then it would be exactly same thing.

**Comment by nielka98** [comment]
explain more because I don't understand

**Comment by Purfview** [comment]
I have nothing to add more to what is said in that video.

**Comment by nielka98** [comment]
I have the 6 version of this program. How do I change this version and do I need to change something in this program from Nikola? Or how? Sorry for asking. I know it's annoying, but I want to understand and I want Whisper to work in a satisfying way.

> Jeśli użyjesz `ffmpeg v5.xx` w SE, będzie dokładnie tak samo.

**Comment by Purfview** [comment]
Replace it with older version -> https://www.videohelp.com/download/ffmpeg-5.1.2-full_build.7z

**Comment by nielka98** [comment]
and where to put it now because I have already downloaded it

**Comment by Purfview** [comment]
It's in "Subtitle Edit\ffmpeg\" folder.

**Comment by nielka98** [comment]
and now?

**Comment by nielka98** [comment]
what now?

**Comment by Purfview** [comment]
Now output from faster-whisper in SE vs console shouldn't be different.

**Comment by nielka98** [comment]
The only problem is that... I have it installed in several places

**Comment by Purfview** [comment]
Only you can know what you are doing out there. 😆

**Comment by nielka98** [comment]
But will it bother me? That's what I'm asking

**Comment by Purfview** [comment]
Probably not.

Here I tried medium model:

```
[01:24.350 --> 01:38.870]  C'era chi pensava a noi, c'era chi aveva già considerato che il tuo futuro sei tu.
[01:38.870 --> 01:47.790]  E lui ti dava per noi, perché contava su chi.
[01:48.350 --> 01:55.990]  Con la speranza e la voglia di vivere cortiva la vita sua.
[01:56.630 --> 01:59.690]  Era lui il proprio salto.
```

No "Amara" here too.

**Comment by nielka98** [comment]
You know that these are not the last problems I come here with, unfortunately :D

**Comment by nielka98** [comment]
It could be even a little more accurate and I would be turbo happy
> [01:24.350 --> 01:38.870]  C'era chi pensava a noi, c'era chi aveva già considerato che il tuo futuro sei tu.
> [01:38.870 --> 01:47.790]  E lui ti dava per noi, perché contava su chi.
> [01:48.350 --> 01:55.990]  Con la speranza e la voglia di vivere cortiva la vita sua.
> [01:56.630 --> 01:59.690]  Era lui il proprio salto.

**Comment by Purfview** [comment]
> You know that these are not the last problems I come here with, unfortunately :D

For the new problems search the issues, if you can't find solution then open a new one.

**Comment by Purfview** [comment]
> It could be even a little more accurate and I would be turbo happy

For better accuracy on the musicals you would need to preprocess the audios extracting only the vocals.
With Demucs or similar.

**Comment by nielka98** [comment]
It works. Maybe not as I would like, but it works, thank you

**Comment by Purfview** [comment]
I'll think about how to improve it on such cases.

Btw, I noticed some strange unexpected model behavior on this audio, not sure what to think about it yet... maybe tomorrow when I'll be sober. 😊

**Comment by Purfview** [comment]
Try `r160.12`, now model should be less susceptible to be stuck in the bad hallucinations loop.

**Comment by nielka98** [comment]
is this the commander or something?

**Comment by nielka98** [comment]
I would like to remind you that I do not use the console, only whisper in the program

**Comment by Purfview** [comment]
It's the new version of the program.

**Comment by Purfview** [comment]
Currently SE auto-downloads an older `r160.7` version.

**Comment by nielka98** [comment]
I'd like a link, please

**Comment by nielka98** [comment]
> Try `r160.12`, now model should be less susceptible to be stuck in the bad hallucinations loop.
Okay, tell me what it's about and give me the link because I don't understand, I remind you. I don't know anything about programming and I barely understand how to do it.

**Comment by Purfview** [comment]
> Okay, tell me what it's about and give me the link because I don't understand, I remind you. I don't know anything about programming and I barely understand how to do it.

It's nothing about the programming.
Releases you can find when pressed the `Releases` button on the main page of the repo at the right side.

**Comment by nielka98** [comment]
IT WORKED !!!! IT WORKED!!! I'm sorry for shouting, but damn I'm so happy, I finally found it and it works, I did what you told me, i.e. I separated the music from the musical and.... IT WORKED!!!
maybe the subtitles are not arranged as I would like them to be, but that's the least of my problems, I can do it manually, but it worked
Thank you, this is the most beautiful Christmas gift I could get for Christmas, the opportunity to translate, the possibility of my beloved musical

**Comment by Purfview** [comment]
What music separator did you used?

If there is some light implementation then I could include it as an option, need to look around as most of the are too heavy...

**Comment by nielka98** [comment]
I used uvr 5

**Comment by nielka98** [comment]
If I were to suggest something to you, I would work on the placement of the subtitles because when it comes to large v 2, it's a tragedy... Or maybe I messed something up and there are some commands that can handle it

**Comment by nielka98** [comment]
But once again, thank you very, very, very, very, very, very much for what you do and for being you

**Comment by Purfview** [comment]
> I used Program uvr 5

I didn't tested it but looks like it should be good.

> If I were to suggest something to you, I would work on the placement of the subtitles because when it comes to large v 2, it's a tragedy... Or maybe I messed something up and there are some commands that can handle it

Open a new feature request at the Discussions.

**Comment by nielka98** [comment]
> 
> Jeśli istnieje jakaś lekka implementacja, mógłbym uwzględnić ją jako opcję, muszę się rozejrzeć, ponieważ większość z nich jest zbyt ciężka…

What exactly is this about, what exactly do you want to do? Because I don't get it and I would like to understand

**Comment by Purfview** [comment]
I meant including the music/vocal separation internaly as an option.

**Comment by nielka98** [comment]
That would be amazing! Mother, I would really like to learn programming someday
