### ISSUE TITLE
Faster-Whisper on drive D?

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#145]
How to safely transfer Whisper to the D drive and is it even possible? Because my C drive is dying and I have very little space

**Comment by Purfview** [comment]
If you use it in SE then it want it to be in its subfolder, then better reinstall SE to disk D.

**Comment by Purfview** [comment]
Try disk cleanup -> https://support.microsoft.com/en-us/windows/disk-cleanup-in-windows-8a96ff42-5751-39ad-23d6-434b4d5b9a68

**Comment by nielka98** [comment]
Hey, the models are still installed on the C drive, please help me how to move them to the D drive, I need to move them to the D drive

**Comment by Purfview** [comment]
> Hey, the models are still installed on the C drive

Maybe you need to use a standalone SE version. Better ask in SE's repo.
[I use standalone SE]

**Comment by nielka98** [comment]
Okay, I admit, I'm panicking... When I wrote this message, I had 81Megabytes of free space now I have 12.5 GB of water space so it's good, sorry, I panic too quickly and don't believe in myself enough
