### ISSUE TITLE
large-v3 error

### ISSUE THREAD

**Issue by boykan313** [Purfview/whisper-standalone-win#146]
Hello! I downloaded a new model, but it gives an error. please tell me how to fix it?
![18](https://github.com/Purfview/whisper-standalone-win/assets/90963133/aebb92d2-62f9-4eec-a35f-ee652b2a3e50)

**Comment by boykan313** [comment]
![190](https://github.com/Purfview/whisper-standalone-win/assets/90963133/61d3a3b9-b4bc-4aae-8c19-f4603f6afea7)
This is also a strange error. I removed the direct language designation and everything worked, but only once. Now it gives the error that I indicated earlier.

**Comment by Purfview** [comment]
"Downloaded" from where? ATM it works with this - https://huggingface.co/Purfview/faster-whisper-large-v3-fp16
I next or after next releasde I'll switch large-v3 to the systrans repo model.

**Comment by boykan313** [comment]
> "Загружено" откуда? Банкомат работает с этим - https://huggingface.co/Purfview/faster-whisper-large-v3-fp16 В следующем или после следующего релизе я переключу big-v3 на модель репозитория systrans.

I downloaded it not from here, but from the developer’s page, there are another 30k+ downloads there. I'll download this option, thanks.

**Comment by boykan313** [comment]
> In next or after next release I'll switch large-v3 to the systrans repo model.

and what will this lead to?

**Comment by Purfview** [comment]
Then it will be compatible with official v3 structure, basically leads to nothing except that you would be able to use "fine-tuned" large-v3 models.

**Comment by Purfview** [comment]
Love how "ATM" was translated to `Банкомат` for you. 😆

**Comment by boykan313** [comment]
> Love how "ATM" was translated to `Банкомат` for you. 😆
> 
> Actually it means "at the moment".

hahaha, it turned out funny :) I understood you, thank you, for now I’ll download the model you suggested and really look forward to the update! :)

**Comment by boykan313** [comment]
![er](https://github.com/Purfview/whisper-standalone-win/assets/90963133/8ad3cccc-1193-4410-8787-4ee2fc003c45)
Hello! I downloaded the model you suggested, but it still gives me an error... =(

**Comment by Purfview** [comment]
Only now you the version you are using is visible - `r160`, that versions doesn't support v3.

**Comment by boykan313** [comment]
> Only now the version you are using is visible - `r160`, that versions doesn't support v3.

It's strange that I can't do it. I downloaded your latest version 167 and updated Updated PyInstaller to v6.3.0
Updated CTranslate2 to v3.23.0
it still gives an error.
![Uploading 546.jpg…]()

**Comment by Purfview** [comment]
Probably because you are trying to using non-official v3 model, that version supports only the official v3 model.

**Comment by boykan313** [comment]
> Probably because you are trying to using non-official v3 model, that version supports only the official v3 model.

I downloaded the version you suggested.. ok, I removed it and launched the download directly from the terminal :)

**Comment by Purfview** [comment]
> I downloaded the version you suggested..

When I suggested it there where no version "167".

**Comment by Purfview** [comment]
> and updated Updated PyInstaller to v6.3.0 Updated CTranslate2 to v3.23.0

No idea what you are updating out there... it's not for Python at all. 😆
