### ISSUE TITLE
Suboptimal use of CPU ressources?

### ISSUE THREAD

**Issue by guilamu** [Purfview/whisper-standalone-win#149]
Hello,

First, let met thank you for this incredible piece of software!

Then, just a question. On an 8 cores CPU it seems whisper-faster is not using all cores. Is that normal?

Bests!
![Capture](https://github.com/Purfview/whisper-standalone-win/assets/8114194/fe915e57-a01d-4f4d-8978-d46e5ab372d9)

**Comment by Purfview** [comment]
It's using **optimal** CPU resources, that's max 4 cores, using more than 4 would be suboptimal as performance doesn't increase.

You can test it with `--threads` argument.

**Comment by guilamu** [comment]
Okay, thank you very much!
