### ISSUE TITLE
Error each time I transcribe?

### ISSUE THREAD

**Issue by Qel0droma** [Purfview/whisper-standalone-win#15]
every time I transcribe I get this error "2023-05-25 13:45:37.1493312 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1671 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.". It still transcribes and everything seems to be working but i'm curious as to what is this error?

**Comment by Purfview** [comment]
This is not an error.

Next version I'll try to remove this message.
