### ISSUE TITLE
large V2 

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#153]
Are there any commands that will make whispers or the second version will spread the subtitles better? Because now what's happening, what's happening, it's a disaster

**Comment by Purfview** [comment]
Can you describe what's "happening" with that large-v2? Can you share a short sample of those happenings?

Is that happening not happening with medium or large-v3?

**Comment by Purfview** [comment]
I see same "CUDA failed with error out of memory" error you posted before -> https://github.com/Purfview/whisper-standalone-win/issues/141

Closing this.
