### ISSUE TITLE
[Subtitle Edit] "text not found" - "Loading result from STDOUT"

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#155]
Hello, help. The program stopped loading sound and doesn't want to generate subtitles. I get the following message: text not found   how to fix it, is it even possible and what's wrong?
at the bottom I am attaching the log
[whisper_log.txt](https://github.com/Purfview/whisper-standalone-win/files/13752724/whisper_log.txt)

**Comment by nielka98** [comment]
And you know what's worst, the program was still working yesterday and today I can't generate subtitles

**Comment by Purfview** [comment]
It fails without any error produced in your SE log file.
You mentioned before that you have very low disk space in C drive, check how much there is. You need at least ~300-400Mb to run it.

And I see that you use `r160.12` version now, your previous log shows `r160.7`, anyway, it shouldn't be a version issue.

**Comment by nielka98** [comment]
I brought the models on a CD according to Nikolaj's advice, my antivirus uninstalled the Sub program and I don't know what's going on, I even want to update CUDA

**Comment by nielka98** [comment]
really what I don't try to generate on the stove pops up, it doesn't find the text and Loading result from STDOUT  in log and this happens regardless of the whisper's version I don't know what's going on seriously Please help me I know you're fed up with me

**Comment by nielka98** [comment]
And I see that you use `r160.12` version now, your previous log shows `r160.7`, check if `r160.7` version fails too now.

unfortunately too

**Comment by Purfview** [comment]
> I brought the models on a D according to Nikolaj's advice,

Then you need ~300Mb. As it self extracts to the system's temp on the run.

> my antivirus uninstalled the Sub program and I don't know what's going on

I've no idea what "Sub program" is.

> Loading result from STDOUT in log and this happens regardless of the whisper's version

That would mean that it not a particular problem with this repo, maybe some general with the SE.
You better ask this at the SE repo.

**Comment by Purfview** [comment]
> regardless of the whisper's version

To be sure, did you mean other Whisper implementations or other Faster-Whisper versions?

**Comment by nielka98** [comment]
> Then you need ~300Mb. As it self extracts to the system's temp on the run.
>  i have

> 
> I've no idea what "Sub program" is.
 is SE

**Comment by nielka98** [comment]
other versions of Faster-Whisper

**Comment by Purfview** [comment]
> is SE

If antivirus deleted SE then how you can run it?

> other versions of Faster-Whisper

Oh, then write it so, because "whisper" doesn't tell me much, there are lost of Whisper implementations.

**Comment by Purfview** [comment]
You need to run Faster-Whisper directly in console and see what it shows there.

**Comment by nielka98** [comment]
> > jest SE
> 
> Jeśli program antywirusowy usunął SE, jak możesz go uruchomić?
> 


because I installed it again and then uninstalled it and installed the version thanks to which I can have the models on the D drive

**Comment by nielka98** [comment]
> Musisz uruchomić Faster-Whisper bezpośrednio w konsoli i zobaczyć, co tam pokaże.

how?

**Comment by Purfview** [comment]
> how?

1) In the Windows's "Run" type `cmd` and press Enter. That should open the Command Prompt.
2) Then navigate to `faster-whiper.exe`'s folder, with `cd` command, for example `cd D:\Subtitle Edit\Whisper-Faster`
3) Now you can run faster-whiper.exe` with your choice of parameters.

Command example:
`whisper-faster_.exe "D:\Videos\somevideo.mkv" --language=English --model=medium --verbose True`

**Comment by nielka98** [comment]
Could you make a video on how to open yours in the console because I have no idea

**Comment by Purfview** [comment]
I already wrote what to do in the previous post.
Try to use Google for things you don't understand.

the link to the video guide how to use console is posted on the main page of this repo.

**Comment by nielka98** [comment]
I can't... all I get is something like this: 'whisper-faster.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Purfview** [comment]
Then post screenshots of the console.
I don't have a cristal ball to see what you are doing there. 😆

**Comment by nielka98** [comment]
![Zrzut ekranu (121)](https://github.com/Purfview/whisper-standalone-win/assets/116809558/75945ac1-695c-4eae-80e8-a4bbbbd56e34)
what's next?

**Comment by Purfview** [comment]
You didn't tell the program what to do, so it shows all parameters for you.

Wrote you a command example before, here I can repeat it:
`whisper-faster.exe "D:\Videos\somevideo.mkv" --language=English --model=medium --verbose=true`

**Comment by nielka98** [comment]
ok, it worked, it was about updating cuBLAS and cuDNN

**Comment by Purfview** [comment]
Bingo!

Not "updating", you didn't had those libs.
I wonder why SE didn't auto-downloaded them for you, anyway, that is SE's issue.

**Comment by Purfview** [comment]
Now, when you are !a pro programmer! you can use it directly. 😆

**Comment by nielka98** [comment]
No, I'm too stupid to use Whisper in the console. Besides, I install them manually, so... Mother, you did it. Ok, I'll go generalize the subtitles
