### ISSUE TITLE
Important Please read.

### ISSUE THREAD

**Issue by CMOSFA** [Purfview/whisper-standalone-win#157]
Hi. I am a NOOB to the standalone version as well as to github so I am posting here. How do I contact Purfview as I want some advice and am willing to donate in exchange for some required features. Thank you.

**Comment by Purfview** [comment]
>  am willing to donate in exchange for some required features. 

It's **not a donation** if you require something in return. I don't offer the paid services.
Implementing something for a donator is more likely, but not guaranteed at all.
You get 0 entitlements as a donator, you just get my intangible gratitude, so, better google "people for hire website".

> how do I contact Purfview 

You are writing under my repository, so you are already contacting me.

> as I want some advice

Btw, I don't offer the paid or personal advises too.
**Issues & Discussions are at your service!**

**Comment by CMOSFA** [comment]
Hey Purfview,

Sorry for the misunderstanding. I used the term donation because that is the button on the site. As I said that I don't know how GitHub works so I didn't know the correct method to address the matter. It was my fault that I assumed that developers offer paid services here. I sort of stumbled on your work by accident and found it pretty useful. I am a new student of Python though I primarily transcribe recordings for business meetings. I'm trying to expand my horizons but due to a backlog I thought that I would request some features and made the mistake of presuming that you would require compensation for going out of your way for someone. Either way I would like to wish you the best. Please keep up your good work. Your work deserves more recognition. Cheers.
