### ISSUE TITLE
Error on running  linux app: "Could not load library libcudnn_ops_infer.so.8."

### ISSUE THREAD

**Issue by Darksoulsong** [Purfview/whisper-standalone-win#158]
I downloaded the Linux app and ran it with the command "whisper-faster "./media/foo.wav" --model small --language English. 

After a few downloads:
```
Model not found at: /home/user/.local/bin/_models/faster-whisper-small
Attempting to download:

Downloading config.json: 100%|██████████████| 2.37k/2.37k [00:00<00:00, 352kB/s]
Downloading tokenizer.json: 100%|██████████| 2.20M/2.20M [00:00<00:00, 2.96MB/s]
Downloading vocabulary.txt: 100%|█████████████| 460k/460k [00:00<00:00, 959kB/s]
Downloading model.bin: 100%|█████████████████| 484M/484M [00:22<00:00, 21.7MB/s]
Downloading model.bin: 100%|████████████████▉| 482M/484M [00:22<00:00, 20.6MB/s]
Standalone Faster-Whisper r167.2 running on: CUDA

```

I got the error below:

```
Discarding ID3 tags because more suitable tags were found.
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
[1]    12357 IOT instruction (core dumped)  whisper-faster "./media/foo.wav"  
```

Do you have any ideas of what might be happening? Thanks!

**Comment by Purfview** [comment]
Download [libs ](https://github.com/Purfview/whisper-standalone-win/releases/tag/libs) and place them at the executable.

**Comment by Purfview** [comment]
I thought that dependencies would work similar to Windows where it first would look at the same folder where executable is.
I need google how they work then...

> I've also tried adding the folder to PATH.

But this should work for sure, no?

**Comment by Purfview** [comment]
> A hacky workaround using Docker:

Not sure what you are doing there, but what if system has CUDA12 stuff installed and you need some CUDA11 libs for some executable?
How you make them be seen by particular executable and not visible for other executables.

**Comment by Purfview** [comment]
Googled a bit.. didn't understand much yet what should I do for it to work out of the box...

But maybe this solution should work from the users side [when keeping libs at the same dir]:

`$ LD_LIBRARY_PATH=. ./whisper-faster`

Note: It will not modify the LD_LIBRARY_PATH variable of your system. The change only affects to this, and only this, execution of your program.

**Comment by Purfview** [comment]
Check this test build [archived libs too] -> https://we.tl/t-z2vSqp5Zfe
Check if it finds libs when running executable normally, I can't test it.

**Comment by Purfview** [comment]
> The test build works but only with the prefix...

Then, it **doesn't** work, for what it's tested for.

**Comment by Purfview** [comment]
Check this test3 build - https://we.tl/t-n9kIdO9Vy5

I think this should work now, and it should work when whisper-faster is called from anywhere [not from the same dir].

**Comment by Darksoulsong** [comment]
Thank you for your attention, guys.
I tried a few things: First, I added the "test3" executable along with the dependencies to my `./local/bin` directory; it didn't work, so I copied the "libcu*" files to "usr/local/lib", in case of the executable is looking for those files in the default Linux libraries location, but no luck.
Finally, I created a directory in my home dir, moved the files there, added the executable and the deps to the $PATH, and ran it, which did not work either.  The executable is still unable to find the lib files.

**Comment by Purfview** [comment]
> The test still doesn't work on my machine.

Probably I must be doing something wrong with the basic syntax as I'm not Linux user.
Stay tuned for the new tests. 😆

> I tried to run it with the workaround ("LD_LIBRARY_PATH=. ./whisper-faster /home/usr/test.wav -m=small -l=en -o=source"), it didn't work either, but gave me a slightly different error, this time it's mentioning the "libnvrtc.so" file:

Can you post what `ls -p | grep -v /` shows?

Btw, libcudnn_ops_infer.so.8 doesn't show such dependency:
```
xxx@xxx-virtual-machine:~/Desktop/whisper-fast$ ldd libcudnn_ops_infer.so.8
	linux-vdso.so.1 (0x00007fffecf76000)
	libcublas.so.11 => /home/xxx/Desktop/whisper-fast/./libcublas.so.11 (0x00007fb2b074b000)
	libcublasLt.so.11 => /home/xxx/Desktop/whisper-fast/./libcublasLt.so.11 (0x00007fb28c1c5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb28c1a7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb28c184000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb28c17e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb28bf9d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb28be4c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb28be31000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb28bc3f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb2bc2e6000)
```

**Comment by Purfview** [comment]
@Darksoulsong Maybe you didn't installed  CUDA at all?

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by Purfview** [comment]
@extremelyonline here is test4 -> https://we.tl/t-Qo9Cq6qm6I

Drop it to a folder with those 4 libs and run it from the same folder:
`./whisper-faster_test4 /source/myfile.mp3 -m=tiny -l=en -o=source`

**Comment by Purfview** [comment]
I think, I cracked this stuff -> https://we.tl/t-EnuimGaQxT

**Comment by Darksoulsong** [comment]
@Purfview Yes, CUDA is installed. 
I gave the new version a try. Here's the  complete output:

```
➜  apps ./whisper-faster /home/usr/test.wav -m=small -l=en -o=source

Model not found at: /home/usr/apps/_models/faster-whisper-small
Attempting to download:

Downloading config.json: 100%|██████████████| 2.37k/2.37k [00:00<00:00, 346kB/s]
Downloading vocabulary.txt: 100%|████████████| 460k/460k [00:00<00:00, 1.80MB/s]
Downloading tokenizer.json: 100%|██████████| 2.20M/2.20M [00:00<00:00, 5.72MB/s]
Downloading model.bin: 100%|█████████████████| 484M/484M [00:18<00:00, 26.6MB/s]

Standalone Faster-Whisper r167.2 running on: CUDA2M/484M [00:18<00:00, 30.6MB/s]


Starting transcription on: /home/usr/test.wav

Discarding ID3 tags because more suitable tags were found.
2023-12-28 18:17:04.075921870 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1987 CreateInferencePybindStateModule] Init provider bridge failed.
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
[1]    6768 IOT instruction (core dumped)  ./whisper-faster  -m=small -l=en -o=source

```

By the way, this is the output of the `nvidia-smi` command; maybe that helps
![image](https://github.com/Purfview/whisper-standalone-win/assets/2078582/ed46490e-decc-4007-9e51-5bda41532120)

**Comment by Purfview** [comment]
Do you have those 4 libs at the executable in "apps"?

Btw, I see that I uploaded my test version with artificial "bridge failed" warning to test dependencies stuff by myself. [it doesn't affect functionality].
Anyway, here it's without that warning: https://we.tl/t-hwGQZW318C

**Comment by Purfview** [comment]
If you want to keep those libs at a different place then you need to add them to `LD_LIBRARY_PATH`.

For example, execute this in terminal [replace `/usr/local/my_libs/` with your path to libs] :
`echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/my_libs/' >> ~/.bashrc`

Restart Linux and check if path is added with -> `echo $LD_LIBRARY_PATH`

**Comment by Darksoulsong** [comment]
Excellent, it works! But I had to install the libs first with  `sudo apt install nvidia-cudnn`. Apparently, the app cannot find the libs in the same folder, even if I use the workaround.
Thank you, @Purfview, for the great job!

**Comment by Purfview** [comment]
Btw, if someone wnders how to make libs to be found on the same dir:
You need to patch executable's `RPATH` with `$ORIGIN`,  `RUNPATH` doesn't work as it doesn't propagate for the dependencies.

**Comment by Purfview** [comment]
Closing as can't investigate it further without knowing what distro @Darksoulsong is using.

Someone with same problem post your distro info.
