### ISSUE TITLE
can you share the script to build the executable app

### ISSUE THREAD

**Issue by iorilu** [Purfview/whisper-standalone-win#16]
actually i also tried to build exe file using faster-whisper, but 
after i use pyinstaller to build it , the folder size is very huge , 
only torch cost 4G space 

but your package seems very small , even add torch is only 1G , so 
i wonder how you did it. 

it will be appreciated if you can share the build script like .spec file usd by
pytinstaller or others. 

if you don't want to post it publicly , you can send to my email:  somesun@gmail.com, thanks

**Comment by Purfview** [comment]
Torch is not need for faster-whisper, just remove it from your script.

> even add torch is only 1G 

It's for OpneAI's Whisper, not for faster-whisper.

**Comment by iorilu** [comment]
ok , I will try to remove torch before build ,  i thought torch is required for GPU execution

how did you do to pack everything into one exe file?

**Comment by Purfview** [comment]
> how did you do to pack everything into one exe file?

https://pyinstaller.org/en/stable/usage.html?highlight=onefile#cmdoption-F

**Comment by iorilu** [comment]
thanks for the info
I tested some videos, it seems yours are better than defaluts, 
could you share the source code if possible , since I also want to buiid
a version for my personal use, maybe be add some other features.

**Comment by Purfview** [comment]
Check it there: https://github.com/Purfview/whisper-standalone-win/blob/main/faster-whisper%20cli/__main__.py
