### ISSUE TITLE
Whisper Timestamped

### ISSUE THREAD

**Issue by PetrusVermaak** [Purfview/whisper-standalone-win#162]
I love your win version, as it is too challenging and complex to make the others work if you're not an expert.

Whisper is notorious for subtitles being way out of sync.

Could you please make an alternate version or incorporate Whisper Timestamped? 
https://github.com/linto-ai/whisper-timestamped

**Comment by Purfview** [comment]
> Whisper is notorious for subtitles being way out of sync.

That's outdated info. For same reason "Whisper Timestamped" is not actual for that anymore.

Btw, do you actually use Whisper? Use Faster-Whisper!

**Comment by PetrusVermaak** [comment]
Yea I meant whisper faster. So whisper faster no longer has the timestamp issue? Because I still get out of sync files...

Here is a typical cmd, am I doing something wrong?
./whisper-faster "G:\audiofile.mp4" --language=English --vad_filter True --language=English --model=large-v3 --beam_size=1 --threads=12

**Comment by Purfview** [comment]
> So whisper faster no longer has the timestamp issue? 

No longer "outdated" timestamps issues.

> Because I still get out of sync files..

Can't comment on that without a sample [cut a short one].

> Here is a typical cmd, am I doing something wrong?
./whisper-faster "G:\audiofile.mp4" --language=English --vad_filter True --language=English --model=large-v3 --beam_size=1 --threads=12

VAD is enabled by default, try "large-v2", don't use "beam_size=1" and "--threads".

**Comment by PetrusVermaak** [comment]
thanks! will do!

**Comment by PetrusVermaak** [comment]
Is there a cmd or setting that can timestamp per word for current version?

**Comment by Purfview** [comment]
> Is there a cmd or setting that can timestamp per word for current version?

It's by default on, `--word_timestamps`.

**Comment by PetrusVermaak** [comment]
Perfect! `--word_timestamps True `worked. Thank you for an absolutely amazing tool!!

**Comment by Purfview** [comment]
Worked what? It's "True" by default, you don't need to do anything for it to "work".  😆

**Comment by PetrusVermaak** [comment]
cmd would not run without adding true at the end. It said: whisper-faster-r167.2.exe: error: argument --word_timestamps/-wt: expected one argument

I then added `--word_timestamps True`, this ran but its not broken up per word. What am I doing wrong?

**Comment by Purfview** [comment]
> I then added --word_timestamps True, this ran but its not broken up per word. What am I doing wrong?

You meant srt file is not broken to a one word per sub? That option doesn't do that. There is `--one_word` option.

Why you need it broken up?

**Comment by PetrusVermaak** [comment]
Thanks! `--one_word 1` worked great! We use it to remove unwanted words from videos. It's a very fast way of editing.
