### ISSUE TITLE
large-v2

### ISSUE THREAD

**Issue by JDTR75** [Purfview/whisper-standalone-win#165]
Hi! I updated to the latest version and I'm having issues when running `large-v2` on non-English files. I was searching before posting this but couldn't find anything related. (I'm getting just a bunch of "............." or "!!!!!!!!!")

I'm only facing this issue with `large-v2` model specifically. Other models are just working fine.

**Comment by Purfview** [comment]
Can you you share a sample with the issue?

**Comment by JDTR75** [comment]
Unfortunately I can't (NDA). Seems like it's only happening with this particular audio. But still got me curious as to why only `large-v2` was having this issue. All the other models worked just fine. You can safely close this 🙂.

**Comment by Purfview** [comment]
Try `-prompt=None`. 
Or `--prompt=auto`, this works only if --language is specified.

**Comment by JDTR75** [comment]
It worked with `-prompt=auto`!
I know it's hard if there's no sample 😓. Sorry about that.

**Comment by Purfview** [comment]
@JDTR75
I've just remembered one bug from vanilla Whisper, I wonder if it's triggering this hallucination for you.

Bugfix is incorporated in new `r167.3` release.

Try it on that file with the same settings when you was getting that hallucination loop.

**Comment by JDTR75** [comment]
Hello! It's still hallucinating with `r167.3` if I don't use `-prompt`.

**Comment by Purfview** [comment]
> It's still hallucinating

Could you run it with `--verbose=true`  and share the output directly from the console? 
Transcription of the few minutes.

> Let me use this to ask you about this as well - maybe it's not the the right thread, lmk-. I'm seeing this on the console all the time: Could not load preprocessor_config.json: Expecting value: line 1 column 1 (char 0). Might be affecting something?

This doesn't look right. With what commands you are getting it?

**Comment by JDTR75** [comment]
So the weirdest (or maybe not) thing happened. I updated SE to the latest beta before reading this. It's now running `large-v2` but it omitted part of the first seconds of the audio even though the VAD clearly detects audio there.

I'm running it like this from SE, nothing special at the moment: `whisper-faster.exe --language es --model "large-v2" "D:\TEMP\7e7359a6-df52-4fe1-a828-e4cfb1210154.wav"`

[whisper_log.txt](https://github.com/Purfview/whisper-standalone-win/files/13842676/whisper_log.txt)

**Comment by JDTR75** [comment]
Here you go... ran directly from CLI.

![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/2186c510-3605-40fc-b363-0f66c3da1ea8)

[purfview.txt](https://github.com/Purfview/whisper-standalone-win/files/13843190/purfview.txt)

**Comment by Purfview** [comment]
Was you doing anything with the models, like copying files manually?

Try to delete large-v2 folder and get model re-downloaded.

**Comment by JDTR75** [comment]
Nope, not doing anything with the models - not savvy enough to be messing around with that. I usually download them from SE's list.

Followed your lead and deleted and re-downloaded the model directly from CLI. Here you go, nothing changed.

![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/117f62c6-24b6-445c-834b-5046a799f939)

[purfview.txt](https://github.com/Purfview/whisper-standalone-win/files/13843576/purfview.txt)

**Comment by Purfview** [comment]
> Followed your lead and deleted and re-downloaded the model directly from CLI. Here you go, nothing changed.

It changed, there is no more: `Could not load preprocessor_config.json: Expecting value: line 1 column 1 (char 0)`.
I wonder what that was about, did you that download model manually from SE links or SE downloaded it automatically?

Try `-prompt=default2`.

**Comment by JDTR75** [comment]
You're right about the preprocessor message, that changed. On SE you just use the GUI.

![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/12bbe34b-0fa6-4683-b8f5-f4ddfe9131cd)

I'll be back shortly with the results for `-prompt=default2`.

**Comment by Purfview** [comment]
Maybe there is some bug with SE's autodownload, try to delete the model again and download it now with SE.

**Comment by JDTR75** [comment]
**Downloading the model from SE.**
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/25ae1b71-2c39-4e36-bd50-b7ed9d4204a6)
[purfview.txt](https://github.com/Purfview/whisper-standalone-win/files/13844003/purfview.txt)


**Results with `-prompt=default2`**
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/e4462198-6b0c-43af-8d60-5dae15686cd7)
[purfview_prompt_default2.txt](https://github.com/Purfview/whisper-standalone-win/files/13844049/purfview_prompt_default2.txt)


The different paths are because I used a separate, clean instance of SE and downloaded the large-v2 from there - same SE beta version to not mess with the tests.

**Comment by Purfview** [comment]
>  ...the model from SE.

Hmm, that message there again,  must be some bug in SE, reported it there -> https://github.com/SubtitleEdit/subtitleedit/issues/7813

> purfview_prompt_default2.txt

Looks like default prompt is triggering that loop, "default2" was previous default, maybe I need to swap it back.

**Comment by JDTR75** [comment]
Here you go.

![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/f3118a54-4f42-4e1b-bf57-7177c2af74f5)
[purfview_test_build.txt](https://github.com/Purfview/whisper-standalone-win/files/13845020/purfview_test_build.txt)

**Comment by Purfview** [comment]
Still hallucinated after some time.

Here is `test2` build -> https://we.tl/t-ct9GUGOoab

**Comment by JDTR75** [comment]
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/b617d174-8ddc-4bd1-9949-4f749b382f51)
[purfview_test_build2.txt](https://github.com/Purfview/whisper-standalone-win/files/13846458/purfview_test_build2.txt)

**Comment by Purfview** [comment]
Here is test3 build -> https://we.tl/t-w4PyZgUJkB

**Comment by JDTR75** [comment]
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/56903fff-0fe3-4cab-a4dd-b683a650b924)
[purfview_test_build3.txt](https://github.com/Purfview/whisper-standalone-win/files/13846744/purfview_test_build3.txt)

**Comment by Purfview** [comment]
Hmm, what if you update libs to v4 https://github.com/Purfview/whisper-standalone-win/releases/download/libs

**Comment by JDTR75** [comment]
Link says "Page not found"

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/releases/edit/libs

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

**Comment by JDTR75** [comment]
Seems like nothing changed
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/277a6c5b-a28b-46fb-98d3-107b2384961c)
[purfview_test_build3.txt](https://github.com/Purfview/whisper-standalone-win/files/13846817/purfview_test_build3.txt)

**Comment by Purfview** [comment]
Here is test4 build -> https://we.tl/t-ee1tuduGJr

**Comment by JDTR75** [comment]
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/30464245-5c44-4ab3-bcdc-cb54b2de365d)
[purfview_test_build4.txt](https://github.com/Purfview/whisper-standalone-win/files/13846985/purfview_test_build4.txt)

**Comment by Purfview** [comment]
OK then... I'll make "default2" back as default.
I
'll cleanup all this spam. Btw for you GPU `-ct=float16` should be fastest.

**Comment by JDTR75** [comment]
Happy to help! Thanks for the tip on the compute type 👍

**Comment by Purfview** [comment]
I noticed there are lots of prompt resets in "[purfview_prompt_default2.txt](https://github.com/Purfview/whisper-standalone-win/files/13844049/purfview_prompt_default2.txt)" because of - `* Reset prompt. prompt_reset_on_no_end is triggered.`

There can be discontinuations in transcription between chunks/windows on prompt reset.

Could you share one more test with `-prompt=auto`?

**Comment by JDTR75** [comment]
![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/5b0d148c-3226-454e-a158-556e08c0f514)
[test4_prompt_auto.txt](https://github.com/Purfview/whisper-standalone-win/files/13847669/test4_prompt_auto.txt)

**Comment by Purfview** [comment]
Thx. There "prompt_reset_on_no_end" was triggered only once. I wonder if "auto" is better than "default2".

If you have feedback on that then post there -> https://github.com/Purfview/whisper-standalone-win/discussions/142

Btw, you can output srt files formatted by `--sentence` or `--standard`. "--sentence" makes easier to spot punctuation.

**Comment by JDTR75** [comment]
You're welcome! I use `--sentence` for everything, actually. I didn't use it in these tests to leave the arguments as clean as possible. I'll make to post about it on the right thread.
So should I stay with this build or will you upload something new? Thanks again!

**Comment by Purfview** [comment]
It affects only srt and vtt files.
You can delete all those "tests".
