### ISSUE TITLE
Faster-Whisper inside Docker fails

### ISSUE THREAD

**Issue by defano** [Purfview/whisper-standalone-win#166]
Using the latest release for Linux ([Whisper-Faster r167.3](https://github.com/Purfview/whisper-standalone-win/releases/tag/faster-whisper)) inside a Docker container results in the following error when issuing the command `whisper-faster audio.wav`:

```
Traceback (most recent call last):
   File "__main__.py", line 1100, in <module>
   File "__main__.py", line 768, in cli
TypeError: '>' not supported between instances of 'NoneType' and 'int'
[3370] Failed to execute script '__main__' due to unhandled exception!
```

This appears to be caused by the script being unable to detect the number of CPUs. If a non-zero value for `--threads` is supplied on the command-line, the tool works normally.

Good: `whisper-faster --threads 1 audio.wav`
Bad: `whisper-faster audio.wav` 

Excellent work on this, by the way. It's a very convenient utility for those of us who don't regularly work in Python.

**Comment by Purfview** [comment]
Should be fixed in `r167.4`.
You should see warning if CPU cores can't be detected.

> Excellent work on this, by the way. It's a very convenient utility for those of us who don't regularly work in Python.

Thx. Yeah, the wast majority of Python's community is "the devs for the devs", not so friendly for the mortal users...
