### ISSUE TITLE
Seems like it's using all cpu cores?

### ISSUE THREAD

**Issue by stellar-z** [Purfview/whisper-standalone-win#168]
Hi,

I saw [https://github.com/Purfview/whisper-standalone-win/issues/149](url) and wondered why my system has higher cpu cores usage.

In my case it seems all cores are being used based on task manager.
Version r167.4.
I used `whisper-faster.exe [file] --language=ja --model=large-v2 --device=cpu --vad_filter=false --output_dir=source`.
I don't have a capable gpu and the cpu transribes at ~0.65 audio seconds/s if this matters.

<img width="386" alt="Screenshot (3283)" src="https://github.com/Purfview/whisper-standalone-win/assets/135497049/0c01bec4-27cc-4ec3-9700-3ab08a9b4fe4">
<img width="294" alt="Screenshot (3285)" src="https://github.com/Purfview/whisper-standalone-win/assets/135497049/00f017d0-626a-4f6b-9bfe-06d87e4cf75b">

Whisper use 65% of CPU most of the time and the 8 cores graph stays pretty much the same throughout the processing.

But in Details tab it stays at 49-50.

<img width="456" alt="Screenshot (3287)" src="https://github.com/Purfview/whisper-standalone-win/assets/135497049/4c6c006d-360a-41f8-a97e-af19baf57db2">

Is this normal?

Thank you

**Comment by Purfview** [comment]
> Is this normal?

Yes, it's normal.
