### ISSUE TITLE
missing segments

### ISSUE THREAD

**Issue by gkngkngkn** [Purfview/whisper-standalone-win#172]
First of all, thank you very much for your updates and maintenance of this excellent project.

Recently, I have noticed that when using the default beam size to transcribe certain files, there are occasional occurrences of missing segments, typically around 30 seconds. However, when I increase the beam size to 10 or 15, the issue seems to be resolved. Additionally,a same video transcribed under the same beam size, the text from the large model appears to be more complete than the medium model. I'm curious about the underlying principles behind this situation.

I'm sure that the entire video's audio source is very clear without bgm and features standard English pronunciation.I wonder if It's possible that the issue could be related to changes in speakers during the transcription process.

i run on 167.4 and the profile i used: --device cuda --language en --model large-v2 --compute_type float32 --skip --sentence --batch_recursive --initial_prompt=auto

**Comment by Purfview** [comment]
> Recently, I have noticed that when using the default beam size to transcribe certain files, there are occasional occurrences of missing segments, typically around 30 seconds.

Can you share an audio sample with the issue?

**Comment by gkngkngkn** [comment]
> > Recently, I have noticed that when using the default beam size to transcribe certain files, there are occasional occurrences of missing segments, typically around 30 seconds.
> 
> Can you share an audio sample with the issue?

Strange thing, when I transcribed the entire video file into an MP3 ready to share, and then transcribed it again with the default beam size before uploading, the missing text reappeared.

**Comment by Purfview** [comment]
Any micro change in audio affects in different transcriptions.

Use `verbose=true` and make a screenshot of a console at the time where it's missing.

**Comment by gkngkngkn** [comment]
> Any micro change in audio affects in different transcriptions.
> 
> Use `verbose=true` and make a screenshot of a console at the time where it's missing.

![0e0facdfc0c9c0bd215bd15c15711ba](https://github.com/Purfview/whisper-standalone-win/assets/151842080/ea252f68-d509-4acd-86d8-e95b3837a37c)

the missing part is 13:05.660 to 13:36.640

**Comment by Purfview** [comment]
Yeah, it's just missing, model sometimes just refuse to output anything on some parts, I've seen example where it doesn't transcribe particular speaker.

**Comment by gkngkngkn** [comment]
> Btw, check if VAD didn't removed that segment.
I guess not but i will check it, because when I raised bs to 15,the missing part appears.(in the above segment, even when I increased the beam size to 10, the missing issue persisted. ) 
![082e72062681b1f28c2c79f0204e5eb](https://github.com/Purfview/whisper-standalone-win/assets/151842080/922c336f-a82d-45cb-b58a-4a995d0897ef)

>Yeah, it's just missing, model sometimes just refuse to output anything on some parts, I've seen example where it doesn't transcribe particular speaker.
Is this a random occurrence with Whisper? Is increasing the beam size the only effective way to address this?

**Comment by Purfview** [comment]
> I guess not but i will check it, because when I raised bs to 15, the missing part appears.

Then VAD is not the culprit.

> Is this a random occurrence with Whisper?

Maybe, I dunno,

> Is increasing the beam size the only effective way to address this?

Lots of things can trigger a model to transcribe differently, maybe even `-bs=1` would make it appear. 
Sometimes almost nothing helps, like in this case -> [Missing the first 21 seconds in small.en and large-v2]( https://github.com/openai/whisper/discussions/1937)

**Comment by Purfview** [comment]
Btw, I've personal test version with various ffmpeg preprocessing settings, I didn't release it because I didn't found any preprocessing helpful, but maybe there are some use cases for them.

**Comment by gkngkngkn** [comment]
> Btw, I've personal test version with various ffmpeg preprocessing settings, I didn't release it because I didn't found any preprocessing helpful, but maybe there are some use cases for them.

Yes, Converting video files to MP3 or WAV format and then transcribing them seems to be a solution for addressing the issue of missing text. It would be great if this processing could be built-in.  :)

**Comment by despairTK** [comment]
> > 顺便说一句，我有带有各种 ffmpeg 预处理设置的个人测试版本，我没有发布它，因为我没有发现任何预处理有用，但也许它们有一些用例。
> 
> 是的，将视频文件转换为 MP3 或 WAV 格式，然后转录它们似乎是解决文本缺失问题的解决方案。如果可以内置这种处理，那就太好了。:)
> 
> 此外，将问题视频拆分为几个部分也可以解决这个问题，但我不知道如何自动执行此任务。

You can transcribe in Subtitle Edit. When transcribing, Subtitle Edit will extract the audio into .WAV format and then transcribe it.

However, it may not be helpful for the problem you encountered, because some sentences will be lost in some audios. This situation occurs less in English audios and more in other language audios, such as the Portuguese I transcribed recently. This is what happens with audio. At this time, you can only try to change some transcription settings, such as `--compute_type` `--initial_prompt auto` `--initial_prompt default` and other parameters.

**Comment by Purfview** [comment]
> Converting video files to MP3 or WAV format and then transcribing them seems to be a solution...

> ...extract the audio into .WAV format and then transcribe it.

Everything is converted to wav inside before doing anything, converting to wav twice is pointless. :)

**Comment by gkngkngkn** [comment]
> > Converting video files to MP3 or WAV format and then transcribing them seems to be a solution...
> 
> > ...extract the audio into .WAV format and then transcribe it.
> 
> Everything is converted to wav inside before doing anything, converting to wav twice is pointless. :)

It's eerie that when I convert this video to MP3 or WAV format before transcribing, there is indeed no occurrence of such missing situations. However, if I transcribe directly from the video, there is a loss, almost like a ghost story.  :(

**Comment by Purfview** [comment]
It's using ffmpeg internally already.

> lossless converting

Maybe it;s not completely lossless, one bit difference anywhere wav can propagate in a way different transcription.
It fixed this particular issue, maybe it created issues at other parts or would in other audios.

Btw, different versions of ffmpeg produce different wavs, so it's not mathematically lossless in my book.

**Comment by gkngkngkn** [comment]
> It's using ffmpeg internally already.
> 
> > lossless converting
> 
> Maybe it's not completely lossless, one bit difference anywhere in wav can propagate in a way different transcription. It fixed this particular issue, maybe it created issues at other parts or would in other audios.
> 
> Btw, different versions of ffmpeg produce different wavs, so it's not mathematically lossless in my book.

Currently I tried, using different models, beam sizes, conversion methods, and video clipping all yield different results. It seems there is no universal method to solve this problem.
luckly this is just an incidental occurrence. :)

**Comment by Purfview** [comment]
Here is a quick test1 build with few filters added -> https://we.tl/t-F8VG46rY6V
Maybe `ff_speechnorm` is most useful from these (later I'll add more). Use ffmpeg v5 to compare apples to apples.

@despairTK wasn't it you who asked for a feature to specify the audio parts to transcribe? I can add that too.

**Comment by despairTK** [comment]
> > 如果可以内置这种处理，那就太好了。:)
> 
> 这是一个快速的 test1 构建，添加了一些过滤器 -[> https://we.tl/t-F8VG46rY6V](https://we.tl/t-F8VG46rY6V) 也许从这些中最有用（？），稍后我会添加更多。使用 ffmpeg v5 将苹果与苹果进行比较。`--ff_speechnorm`
> 
> 您不是要求指定要转录的音频部分的功能吗？我也可以补充一点。

Thank you very much for your special attention. I will test the beta version and give feedback.

**Comment by gkngkngkn** [comment]
> > It would be great if this processing could be built-in. :)
> 
> Here is a quick test1 build with few filters added -> https://we.tl/t-F8VG46rY6V Maybe `--ff_speechnorm` is most useful(?) from these, later I'll add more. Use ffmpeg v5 to compare apples to apples.
> 
> @despairTK wasn't you who asked for a feature to specify the audio parts to transcribe? I can add that too.

thx for ur job, but this version still don't work on that issue after testing.

**Comment by Purfview** [comment]
> thx for ur job, but this version still don't work on that issue after testing.

Not sure that I understand you, with what command doesn't work?

**Comment by Purfview** [comment]
How it "still don't work on that issue after testing" if you wasn't able to run it... 😆

Just run `ffmpeg.exe` in console and check it's version, probably it's some very old one.

**Comment by gkngkngkn** [comment]
> How it "still don't work on that issue after testing" if you wasn't able to run it... 😆
> 
> Just run `ffmpeg.exe` in console and check its version, probably it's some very old one.

ok i will check it thx

**Comment by gkngkngkn** [comment]
> How it "still don't work on that issue after testing" if you wasn't able to run it... 😆
> 
> Just run `ffmpeg.exe` in console and check its version, probably it's some very old one.

Sir, I  updated my ffmpeg and tried again with this command. There still seems to be text missing in THIS video. Perhaps other filters might be effective.

**Comment by Purfview** [comment]
Here is test2 build -> https://we.tl/t-6NPHtKQbpx

Check with `--ff_mp3`, this will per-process audio with mp3 conversion.
Dunno if it makes a difference, but conversion is at the end of the audio pre-processing, not at start. This way it's much faster.
Anyway, if it wouldn't make that segment appear then I can make this conversion at the start.

**Comment by Purfview** [comment]
I looked at spectrals and I see that mp3 conversion on 16000Hz cut off frequencies above ~7300Hz and I think I see slight timeline distortion like audio moved to the right side.
So here is test3 -> https://we.tl/t-MFz6hagPfA , it's converting MP3 at the start - processes original audio.
Compare it to test2 transcription results.

Original:
![Infinity Pool test mkv_dump wav](https://github.com/Purfview/whisper-standalone-win/assets/69023953/96ef4ae7-5d5f-4f9b-953e-88edb1e156de)

test2:
![Infinity Pool test mkv_dump_mp3 wav](https://github.com/Purfview/whisper-standalone-win/assets/69023953/52c99225-4ccd-4e6d-b817-3d1b72a71edd)

test3:
![Infinity Pool test mkv_dump_mp3_2 wav](https://github.com/Purfview/whisper-standalone-win/assets/69023953/b8c67e08-36a1-423f-a379-a5186eb5fc77)

**Comment by toprak** [comment]
@Purfview can I have linux build of  test version, I have had similar problem in many audios. sometimes there is text loss, some times it repeat itself. I generally use beam_size=5.

**Comment by gkngkngkn** [comment]
Based on the feedback from the tests, the use of test3 has significantly improved the situation of missing text in the large model compared to the original. However, there are still instances of missing text in the medium model.

**Comment by gkngkngkn** [comment]
will continue testing them, thx for ur decent job sir :)

**Comment by toprak** [comment]
@Purfview that new one fixed my issue ig i will let u know if it happens again, switched  to w11 to use the new one ;D

**Comment by Purfview** [comment]
About audio filters post there: https://github.com/Purfview/whisper-standalone-win/discussions/178
