### ISSUE TITLE
dot

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#173]
Hey, I have a stupid problem. Large version two started giving me dots very very very very strongly, it doesn't generate subtitles, only dots. Do you know how to fix it? Maybe give me some commands to prevent this from happening? 
here is the command I use:
1.-bo=10 -bs=10 --temperature_increment_on_fallback=None 
2.-bo=10 -bs=10 --temperature_increment_on_fallback=None --vad_threshold 0.3
-bo=1

**Comment by Purfview** [comment]
Your example commands doesn't make sense, don't use these.

**Comment by nielka98** [comment]
I'm sorry that I haven't responded but I've had some turmoil in my life... Well, I've somehow resolved the dot crisis, although it's not perfect yet, I'm still trying with different commands and in general. I wonder if it would be possible to turn up the whisper somehow... could you turn up the whisper so that it better peaks the song lyrics because it still generates subtitles for the musical? Generally, machine learning is not a terribly interesting topic, I think... If you have any ideas on how I can make whisper work more efficiently or commands, I will be happy to receive them. 
PS. because I'm writing and I've never thanked you for what you do and I'm super grateful to you, so thank you for what you do and for being patient with me

**Comment by Purfview** [comment]
I guess you had hallucinations with dots aka periods? That probably could be because of the recent change in initial_prompt.
Try `-prompt=None` or `-prompt=auto` if you encounter such problem.

I don't understand what other issues you have. Anyway, keep one problem per thread, open a new issue for other problem.

**Comment by nielka98** [comment]
that's exactly how I hallucinated the dots
