### ISSUE TITLE
Support for other language models

### ISSUE THREAD

**Issue by pulpul-s** [Purfview/whisper-standalone-win#177]
Is it possible to support models from for example Hugging Face? I'd like to try a Finnish optimized model https://huggingface.co/Finnish-NLP/whisper-large-finnish-v3

```
Whisper-Faster> .\whisper-faster.exe --model fin-large-v3 --sentence --language Finnish '..\test.mp4'

Standalone Faster-Whisper r167.4 running on: CUDA


Warning: 'large-v3' model may produce inferior results, better use 'large-v2'!

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 1104, in <module>
  File "D:\whisper-fast\__main__.py", line 972, in cli
  File "faster_whisper\transcribe.py", line 136, in __init__
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v149936. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)
[35420] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by Purfview** [comment]
You can use any model for `Faster-Whisper`.
The model in your link is for original OpenAI's `Whisper`.
To use this model you can use standalone Whisper -> https://github.com/Purfview/whisper-standalone-win/releases/tag/Whisper-OpenAI

Or you can convert that model to be comatible with Faster-Whisper, there is guide: https://github.com/SYSTRAN/faster-whisper#model-conversion
