### ISSUE TITLE
Add support for --max_line_width --max_line_count

### ISSUE THREAD

**Issue by topolar** [Purfview/whisper-standalone-win#18]
Could you please add support for --max_line_width and --max_line_count ?

https://github.com/Softcatala/whisper-ctranslate2/blob/b1583e7fe42fc0b185251ad6221328904cab3a25/src/whisper_ctranslate2/writers.py#L57

Thanks

**Comment by Purfview** [comment]
I'll check what whisper-ctranslate2 does.

**Comment by topolar** [comment]
Thank you

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/discussions/87
