### ISSUE TITLE
please release Whisper-Faster_r172.1_linux.zip

### ISSUE THREAD

**Issue by joostshao** [Purfview/whisper-standalone-win#181]
please release Whisper-Faster_r172.1_linux.zip, thank you very much

**Comment by defaultsecurity** [comment]
Yes, please! r172.4?

**Comment by Purfview** [comment]
Atm, I'm busy with r179. Probably that version will see a Linux build.

**Comment by Purfview** [comment]
It's released.

**Comment by defaultsecurity** [comment]
> It's released.

Thank you for your dedication and for releasing the linux version.

**Comment by defaultsecurity** [comment]
@Purfview 
Thank you very much for keeping the Linux version up to date!
