### ISSUE TITLE
configurable model dir?

### ISSUE THREAD

**Issue by KayLeung** [Purfview/whisper-standalone-win#19]
This is handy to run fast whisper from any folder. However, it will re-download model files now. Can you add a way to specify the fast whisper model dir? 

** I tried `[--model_dir MODEL_DIR]` but it doesn't prevent downloads.

Thanks.

**Comment by KayLeung** [comment]
ahh. I figured out the problem.

It required to add `\_models` to the path

**Comment by Purfview** [comment]
Thanks for report.
Check r126 version, it should work properly without need of `model_dir` setting.
