### ISSUE TITLE
[Feature-Request] Output pure text with 1 sentence per line

### ISSUE THREAD

**Issue by defaultsecurity** [Purfview/whisper-standalone-win#190]
I'm trying to output pure text with one sentence each line. I could not find a setting combination to achieve this.
For example the output_format "text" doesn't allow "--sentences=true"

**Comment by Purfview** [comment]
> I'm trying to output pure text with one sentence each line. I could not find a setting combination to achieve this.
> For example the output_format "text" doesn't allow "--sentences=true"

It outputs only to srt and vtt formats.

> [Feature-Request] Output pure text with 1 sentence per line

I'm not interested in supporting various subtitle formats, use other software dedicated for that.

For example, open srt or vtt file with [Subtitle Edit](https://github.com/SubtitleEdit/subtitleedit), it has hundreds export formats, here export plain text via File:

![image](https://private-user-images.githubusercontent.com/1261331/287300761-91f16879-6d89-45b1-8447-4a5e37d028e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTk0NTksIm5iZiI6MTcwNzY1OTE1OSwicGF0aCI6Ii8xMjYxMzMxLzI4NzMwMDc2MS05MWYxNjg3OS02ZDg5LTQ1YjEtODQ0Ny00YTVlMzdkMDI4ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTM0NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJhNDg4NjIzZTNjZmE5NjE2NTkwYzEwZThmNTk5MTNjZWUzZWJiYTc2NDE5MzI1MjJmN2NkYmI4MjkxNTU5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gb8dcLtmOdAUQ1NyEVKnCny8zgeoxu8tOW5xQu9LOF8)

![image](https://private-user-images.githubusercontent.com/1261331/287300975-912a968c-31e1-4d06-b0a2-d96fadb630c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTk0NTksIm5iZiI6MTcwNzY1OTE1OSwicGF0aCI6Ii8xMjYxMzMxLzI4NzMwMDk3NS05MTJhOTY4Yy0zMWUxLTRkMDYtYjBhMi1kOTZmYWRiNjMwYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTM0NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JjNTY4NzcyOTVlMzI5NmY1MzEwMzdlMTM1YjhhM2EzMTdmYzBiYzQwNTM1ZWRlODkxNjk2N2Y2Y2YyNDk5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BuTdlWfa7AO3nmqLHZAP3ljPb9pHMJPNBstubQ61bko)
 
You can even make your own custom export formats: ![image](https://private-user-images.githubusercontent.com/1261331/287301330-d5644dcf-ca38-4c28-911d-5353f70a6afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTk0NTksIm5iZiI6MTcwNzY1OTE1OSwicGF0aCI6Ii8xMjYxMzMxLzI4NzMwMTMzMC1kNTY0NGRjZi1jYTM4LTRjMjgtOTExZC01MzUzZjcwYTZhZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTM0NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjdjZDRmMmNjNWNkYjU2ZmVhY2JhM2I0Y2VjN2NiZTU3MDViYzE0YzdlNzdjMjMzNzNmNWIzZmQwMTI4ZGIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T9VSjlg5ifxvZTbydyzs_C3EEIyjSGwvWMlFBDg9Mf8)
