### ISSUE TITLE
[Question] max_line_width and max_line_count

### ISSUE THREAD

**Issue by URUWorks** [Purfview/whisper-standalone-win#191]
Hola Purfview,

How should I use these parameters?
If I use them, it tells me that they were altered and need to use them with "--sentence", using them together with "--sentence" has no effect ?

Gracias.

**Comment by Purfview** [comment]
Hi, effect is in srt and vtt files.

What you see in console is the pure whisper output.

**Comment by URUWorks** [comment]
Thank you!

**Comment by Purfview** [comment]
Btw, "max_line_width" and "max_line_count" are not same in vanilla Whisper, there it produces output in a borked way.
