### ISSUE TITLE
Best strings for various situations?

### ISSUE THREAD

**Issue by Manniala** [Purfview/whisper-standalone-win#194]
Hey, i am not sure what i do wrong, some times i get flawless translation, other times it is only the beginning, where after it starts with ... and ...

What string is best for English Movies to make .srt
Which for French translation to English .srt

And i see in the .bat [https://github.com/Purfview/whisper-standalone-win/discussions/29](url) people were using medium, why that, is large-2 not better, because that's the one i have been using, i did try medium but the result were well...

Would love if some one could past a string for translation and for just making english subtitle from english movies.

**Comment by Purfview** [comment]
>Best strings

What that means?

>where after it starts with ... and ...

Try `-prompt=None`

**Comment by Manniala** [comment]
First thank you for taking the time to reply.

Sorry yeah my English is not that great, so some times my explanations are well bad.

Lets say i want to translate French, i have been using this:
`whisper-faster.exe --language French --task translate --model large-v2 --model_dir`
So what i ment was, there must be something else i can try, other than the one there.

It works fine most of the times, but also many times, it just stops translating after a while, and puts out "..." (or nothing at all), in stead of translating, and when i rerun it, it does the same, there for i thought i must be doing something wrong, something i do not understand (which is a lot), there are so many parametres that i do not understand what does what.

So if you know what i might be doing wrong, or a way i can improve so that it wont happen that of than, i would be grateful, The speed of the translation, is not important, i have a lot of time. :)

**Comment by Purfview** [comment]
> Lets say i want to translate French

What means "translate French", translate what to what?

**Comment by Manniala** [comment]
Hmm, if the language of the video is in French, i use this "--language French --task translate" and makes it into English Text.

Sorry thought that was clear what translate ment.

**Comment by Purfview** [comment]
Did you tried `-prompt=None`

**Comment by Manniala** [comment]
To be honest nope, i did not, not the first time, since id did not  make much sense to not prompt anything, when the problem was it prompted either "..." or nothing, even that there were people talking.

And than i looked, and it was not on the list of what you could use when i wrote whisper-faster.exe in command prompt, and every thing else also always starts with --

Anyway i did run it now, it just replaces the "..." with the same few words, form 1/3 in the video to the end.

But never mind, i wont take more of your time, and sorry i wasted so much already..

**Comment by Purfview** [comment]
>it was not on the list of what you could use when i wrote whisper-faster.exe in command prompt, and every thing else also always starts with --

Some parameters have short alternatives, those start with one "-"

>Anyway i did run it now, it just replaces the "..." with the same few words, form 1/3 in the video to the end.

Can you share an audio sample with the issue and srt file?
