### ISSUE TITLE
Virus/Malware

### ISSUE THREAD

**Issue by hnorgaar** [Purfview/whisper-standalone-win#198]
When extracting Whisper-Faster_r172.4, Windows Defender is blocking the file saying its a threat and I wouldnt think it was. Might be an issue for many others i guess with less knowledge of computers than me

Threat : trojan:win32/wacatac.b!ml

**Comment by Purfview** [comment]
Dupe of https://github.com/Purfview/whisper-standalone-win/discussions/91
