### ISSUE TITLE
smaller executables.

### ISSUE THREAD

**Issue by tariq0101** [Purfview/whisper-standalone-win#2]
Hi, 
is it possible to release a win64 cuda executable without additional files (models, cuda libraries etc) because it's a huge file right now and I'm from a third world country with a bad internet connection, and I already downloaded the models and installed cuda.

**Comment by Purfview** [comment]
There is no models, "cuda libraries" nor "etc" included. It's bare minimum size already..

**Comment by Purfview** [comment]
Actually, Faster-Whisper doesn't need PyTorch, I've released a smaller executable for it.
