### ISSUE TITLE
whisper-Faster_r182.1 dont translate

### ISSUE THREAD

**Issue by Purfview** [Purfview/whisper-standalone-win#202]
<sup>Originally posted by @zalastone February 28, 2024</sup>
it work outside the app but if you just update exe in the app folder . it don't translate to english and just transcribe

v167 work 
whisper-faster.exe --language ko --model "large-v2" --task translate  "C:\*************.wav"

v172 don't work 
v182 don't work 
whisper-faster.exe --language ko --model "large-v2" --task translate  "C:\*************.wav"</div>

**Comment by Purfview** [comment]
@zalastone What is SE version?

**Comment by zalastone** [comment]
4.0.3 latest

**Comment by zalastone** [comment]
> @zalastone What is SE version?


4.0.3 latest

**Comment by Purfview** [comment]
Probably related to this bug -> https://github.com/SubtitleEdit/subtitleedit/issues/7813

**Comment by Purfview** [comment]
> now we have different problem

What means "now"? Is it means the latest beta?

> it work outside the app

Do you mean that it's OK if you run it directly?

**Comment by zalastone** [comment]
4.0.3 beta 
v167 work
v172 dont work
v182 work  ( but transcribe few lines only when using fine-tuned model of faster-whisper)

**Comment by zalastone** [comment]
it working ok now 
subtitle edit 4.0.3 
r182.2 ( faster-whisper and fine-tuned models) 
Thanks :)
