### ISSUE TITLE
Linux version cannot be executed

### ISSUE THREAD

**Issue by F4ceMeltor** [Purfview/whisper-standalone-win#206]
I loaded the Linux version, I'm on up to date Linux Mint Debian Edition and all the bash gives me is that "binary file couldn't be executed".

**Comment by Purfview** [comment]
Did previous version worked?
What is your CPU?

**Comment by flatsiedatsie** [comment]
I also get `-bash: ./whisper-faster: cannot execute binary file: Exec format error`

But that's likely because the Linux version is designed for X86 and not Arm.

**Comment by Purfview** [comment]
> But that's likely because the Linux version is designed for X86 and not Arm64.

Yes, x86-64.
