### ISSUE TITLE
[FR] Add web video support (Youtube) 

### ISSUE THREAD

**Issue by cogscides** [Purfview/whisper-standalone-win#21]
I would like to suggest adding support for web video transcription, specifically for platforms like YouTube.

By incorporating web video transcription capabilities, the tool would become even more versatile and valuable, catering to content creators and researchers. This enhancement would save time and effort while attracting a wider user base.

Thank you for considering my suggestion to further enhance your amazing tool's functionality.

**Comment by Purfview** [comment]
> I would like to suggest adding support for web video transcription, specifically for platforms like YouTube.
> 
> By incorporating web video transcription capabilities, the tool would become even more versatile and valuable, catering to content creators and researchers. This enhancement would save time and effort while attracting a wider user base.

You can do this already, download audio/video -> transcribe.
You can use [Local YouTube Downloader](https://greasyfork.org/en/scripts/369400-local-youtube-downloader).

Btw, I don't work for Google and I don't care about YouTube attracting a wider user base.
