### ISSUE TITLE
request: default Settings

### ISSUE THREAD

**Issue by Ed1ks** [Purfview/whisper-standalone-win#212]
Hello, by using faster-whisper standalone I can transcribe audio files very good. But sadly I cant use the .exe file inside a linux distrubition, so I am trying to set up this [faster-whisper python plugin](https://github.com/SYSTRAN/faster-whisper)
Sadly I am getting sometimes repetitive sentences inside of the lyrics, or it aborts after some time - not finishing the full audio file. Could you please provide the default settings of this standalone application?

My settings:

```
segments, info = model.transcribe(f'{self.audio_dir}/{file}',
                                  temperature=0,
                                  best_of=5,
                                  beam_size=5,
                                  patience=1,
                                  length_penalty=1,
                                  no_repeat_ngram_size=0,
                                  prompt_reset_on_temperature=0.5,
                                  compression_ratio_threshold=2.4,
                                  log_prob_threshold=-1,
                                  no_speech_threshold=0.6,
                                  vad_filter=True,
                                  vad_parameters=dict(
                                      min_speech_duration_ms=350,
                                      threshold=0.45,
                                      min_silence_duration_ms=3200,
                                      speech_pad_ms=900,
                                      window_size_samples=1536
                                  ),
                                  language="de",
                                  )
```

Any help is appreciated!

**Comment by Purfview** [comment]
> But sadly I cant use the .exe file inside a linux distrubition

Make a screenshot of the issues with `--verbose=true` and maybe share the audio sample.

If your audio is music then you should pre-process it with Demucs, for example a tools like this-> https://github.com/Anjok07/ultimatevocalremovergui

**Comment by Purfview** [comment]
> Could you please provide the default settings of this standalone application?

`--help`
