### ISSUE TITLE
Command too long when only using a few arguments

### ISSUE THREAD

**Issue by Ty-Grr** [Purfview/whisper-standalone-win#214]
Translating foreign films to english and testing out different arguments seen on the discussions to try and get the best readable translation without it cutting off words or making it difficult to read as I'm watching.

Command I am using is 
whisper-faster.exe "media path" --language en --sentence --ff_rnndn_sh --ff_rnndn_xiph --ff_silence_suppress -40 1 --model medium -o=source

This gives me the Command Too Long error.

https://i.imgur.com/yYXOk5B.png

Reading about with using TCC to try and run the command but it still gives me that same error message, not sure if I need to do anything else with that as saw previous discussion mention it 
https://github.com/Purfview/whisper-standalone-win/discussions/178#discussioncomment-8398495

It just gives me srt with 0kb 

https://i.imgur.com/0m4vVSw.png

I can reduce down the size of the command to get rid of the ffmpeg elements but want to use them as need to translate lots of foreign media and want to get best results.

Cant see anything about a config file to separately input arguments into for it to read to get past this command to long, 

I have tested without the --sentence but that again gives me 0kb srt file.

Hopefully I'm doing something wrong.

**Comment by Purfview** [comment]
> Command too long when only using a few arguments

It's not about user command length, it's internal command too long (it comes from ff_silence_suppress)

> using TCC

TCC wouldn't help because it's command to OS API

> but it still gives me that same error message...

But there is no error in your screenshot.

> It just gives me srt with 0kb

Looks like you silenced the whole audio.

>without it cutting off words or making it difficult to read as I'm watching

Use `--standard`

> want to get best results.

Then clean up audio with Demucs -> https://github.com/Anjok07/ultimatevocalremovergui
