### ISSUE TITLE
Translate and --postfix bug

### ISSUE THREAD

**Issue by Jorman** [Purfview/whisper-standalone-win#215]
Hi, many thanks for this!
Usually I use whisper within Bazarr, but my actual nas is very slow, so I had to help him with my pc, and this's very good, I tried in past to use docker under windows, but is not so good like under linux, so...
I have a question about translation, I know that is possible to translate only in English, maybe in future also in multiple languages?
Btw, I'm generating subs for a foreign language show, in French, I use this code `--language=fr --task=translate --postfix` but the final file have this form `showname_fr.srt` but is translated, should be `showname_en.srt` instead
I miss some configuration or is this right?

**Comment by Purfview** [comment]
> I know that is possible to translate only in English, maybe in future also in multiple languages?

I doubt that.
Anyway, if you want it to translate to other language you can try hacky way - by setting wrong --language. You may get good result or not, because model is not trained to do that.

> I use this code --language=fr --task=translate --postfix but the final file have this form showname_fr.srt but is translated, should be showname_en.srt instead

I'll fix it in the next version.

**Comment by Jorman** [comment]
I'll play a little bit with settings, thanks, but I think is better to use external services like deepl or similar.
Thanks for the future fix

**Comment by Purfview** [comment]
Should be fixed in r189.1
