### ISSUE TITLE
What settings improve word timestamps accuracy of timing? 

### ISSUE THREAD

**Issue by scaruslooner** [Purfview/whisper-standalone-win#216]
I have this problem where the end transcript time cuts off the word instead of capturing the whole word.
What settings do you recommend I play with to get more accurate/precise timing of the ending of a word?  
(Im using a 4060ti 16 gb vram)

This is what i type in:
"C:\Program Files\Whisper\whisper-faster.exe" "C:\Users\camer\OneDrive\Desktop\Whisper-Faster_r186.1_windows\Whisper-Faster\2024-03-10 20-56-19.mp4" --model large-v3 --output_dir C:\Users\camer\OneDrive\Desktop\Whisper-Faster_r186.1_windows\Whisper-Faster --output_format srt --language en --sentence 

Preview of the output:
(Also i highlighted the words that are getting cut off)
1
00:00:04,800 --> 00:00:05,240
Yo.

2
00:00:05,240 --> 00:00:05,680
Yo.

3
00:00:07,680 --> 00:00:09,300
The Pistons suck this **year.**

4
00:00:09,440 --> 00:00:10,620
I don't know why they're so **bad.**

5
00:00:11,620 --> 00:00:13,240
I feel like they need to get **better.**

6
00:00:14,720 --> 00:00:16,060
In everything they **do.**

7
00:00:16,380 --> 00:00:17,120
You feel **me?**

8
00:00:22,070 --> 00:00:23,770
I'm just kind of eating right **now.**

9
00:00:25,770 --> 00:00:26,750
Kyrie has the **ball.**
"

**Comment by Purfview** [comment]
Share the json file.

**Comment by scaruslooner** [comment]
I dont where the json file is but i have srt file.
[2024-03-10 20-56-19 words get cuttoff.txt](https://github.com/Purfview/whisper-standalone-win/files/14579485/2024-03-10.20-56-19.words.get.cuttoff.txt)

https://github.com/Purfview/whisper-standalone-win/assets/39450507/0134dd01-e732-4ced-9724-83be8dbe1b58

**Comment by scaruslooner** [comment]
Oh wait i can generate json. Here it is: 
[2024-03-10 20-56-19.json](https://github.com/Purfview/whisper-standalone-win/files/14579552/2024-03-10.20-56-19.json)

**Comment by Purfview** [comment]
Maybe you need to zip json and srt files as I can't open them.

**Comment by scaruslooner** [comment]
[SrtAndJSON.zip](https://github.com/Purfview/whisper-standalone-win/files/14579766/SrtAndJSON.zip)
Does this work

**Comment by Purfview** [comment]
Nope, zip doesn't work too. Upload there ->https://wetransfer.com/

**Comment by scaruslooner** [comment]
https://we.tl/t-3lFMlZW3D0

**Comment by Purfview** [comment]
That is normal precision for whisper.
Maybe in the future it will be improved with wav2vec alignment.

> --output_dir C:\Users\camer\OneDrive\Desktop\Whisper-Faster_r186.1_windows\Whisper-Faster 

You can use `-o source`

> --output_format srt

not needed as srt is default
