### ISSUE TITLE
stucks on download

### ISSUE THREAD

**Issue by freeexit2002** [Purfview/whisper-standalone-win#22]
Receiving objects:  63% (53/84)used 0 (delta 0), pack-reused 0

**Comment by Purfview** [comment]
What program? You can download models manually.

**Comment by freeexit2002** [comment]
i cant download whisper-faster.exe. I cant find it. Thank you

**Comment by Purfview** [comment]
It's in Releases, there: https://github.com/Purfview/whisper-standalone-win/releases
