### ISSUE TITLE
flashing/flickering text

### ISSUE THREAD

**Issue by ubemotho** [Purfview/whisper-standalone-win#223]
when enable highlight_words text is flicker like in this example https://github.com/openai/whisper/discussions/1072 

https://github.com/Purfview/whisper-standalone-win/assets/1352206/09e6fbb8-e0e6-47bd-b56e-7e5fa4b15c6c

i used this for example https://www.youtube.com/watch?v=ErRr-vA7_-U

i dont know if this a problem from whisperx or faster-whisper implementation 
but it should be fixed in whisper in this commit https://github.com/openai/whisper/pull/1087

**Comment by Purfview** [comment]
Can you post your whole command used?

**Comment by ubemotho** [comment]
--compute_type float16  --highlight_words true
```
-----------------------------------------------------------------------------
Date: 03/22/2024 
SE: 4.0.4.0 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: C:\Users\X\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language en --model "tiny.en" --compute_type float16  --highlight_words true "C:\Users\X\AppData\Local\Temp\a80d86ec-3c06-404c-88a7-2bbcdb1e3d44.wav"

-----------------------------------------------------------------------------
Date: 03/22/2024 
SE: 4.0.4.0 - Microsoft Windows NT 10.0.19044.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper) with : C:\Users\X\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language en --model "tiny.en" --compute_type float16  --highlight_words true "C:\Users\X\AppData\Local\Temp\a80d86ec-3c06-404c-88a7-2bbcdb1e3d44.wav"
Standalone Faster-Whisper r186.1 running on: CUDA
Starting transcription on: C:\Users\X\AppData\Local\Temp\a80d86ec-3c06-404c-88a7-2bbcdb1e3d44.wav
[00:15.270 --> 00:37.620]  Activate the intelligent system. Access granted. Good evening, Bennett. How are you? Being in quarantine isn't so great. Thank you for asking. I am so lucky to be a bot. Shut up. Just give me information on the current coronavirus situation.
[00:37.620 --> 01:05.940]  There are nearly 2 million confirmed cases of coronavirus worldwide. The number of infections with a new coronavirus continues to rise. Is there a vaccine on the COVID-19? There is currently no vaccine but there is a patient that has recovered from COVID-19 that has proven to have the most effective antibody against the virus. Do we have more information on the patient? Information classified. Shit. I guess I have to do it myself.
[01:10.900 --> 01:43.160]  Access granted. Yes. Got her name is Sena Savana. She is 26 year old and is a kindergarten teacher and is currently kept held in a Swiss biotech firm. Oh my god. She's the back scene. Shit. You have 10 seconds left. Starting count down now. 8, 7, 6, 4, 5, 4, 3, 2, 1.
[01:43.160 --> 01:55.340]  Down low. You're too late.
Transcription speed: 47.02 audio seconds/s

Operation finished in: 4 seconds

Subtitles are written to 'C:\Users\X\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster' directory.
Calling whisper Purfview's Faster-Whisper done in 00:00:08.8228101
Loading result from C:\Users\X\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\a80d86ec-3c06-404c-88a7-2bbcdb1e3d44.srt
```

**Comment by Purfview** [comment]
I think that's Subtitle Edit issue. Disable SE's post-processing!

Ping to @niksedk

**Comment by ubemotho** [comment]
> I think that's Subtitle Edit issue. Disable SE's post-processing!
> 
> Ping to @niksedk

oh youre right. i am new to subtitle edit i forgot about post-process. sorry for your time and  thank you. i added a example for better understanding

here is more info for SE guys 
this is SE output: 
<details><summary>Details</summary>
<p>

1
00:00:15,270 --> 00:00:15,578
<u>Activate</u> the intelligent system. Access granted. Good evening,
Bennett. How are you? Being in quarantine isn't so great.

2
00:00:15,590 --> 00:00:15,910
Thank you for asking. I am so lucky to be a bot. Shut up.
Just give me information on the current coronavirus situation.

3
00:00:15,911 --> 00:00:16,129
Activate <u>the</u> intelligent system. Access granted. Good evening,
Bennett. How are you? Being in quarantine isn't so great.

4
00:00:16,141 --> 00:00:16,370
Thank you for asking. I am so lucky to be a bot. Shut up.
Just give me information on the current coronavirus situation.

5
00:00:16,371 --> 00:00:16,439
Activate the <u>intelligent</u> system. Access granted. Good evening,
Bennett. How are you? Being in quarantine isn't so great.


</p>
</details> 

this is faster-whisper.exe when i run from cli with these   commands:  .\whisper-faster.exe '.\The Hacker (Quarantine Short Film) (1080p_25fps_H264-128kbit_AAC).mp4' -l English -m tiny -o source --compute_type float16 --highlight_words true

<details><summary>Details</summary>
<p>

1
00:00:14,850 --> 00:00:15,410
<u>I</u> activate the intelligent system.

2
00:00:15,410 --> 00:00:15,970
I <u>activate</u> the intelligent system.

3
00:00:15,970 --> 00:00:16,310
I activate <u>the</u> intelligent system.

4
00:00:16,310 --> 00:00:16,670
I activate the <u>intelligent</u> system.

5
00:00:16,670 --> 00:00:17,450
I activate the intelligent <u>system.</u>

</p>
</details>

**Comment by niksedk** [comment]
Turn of SE's "Post-processing" when using the `---highlight_words true` parameter

SE will do this automatically in next SE update
