### ISSUE TITLE
[INFO] Does it includes WhisperX strategies too?

### ISSUE THREAD

**Issue by gericho** [Purfview/whisper-standalone-win#225]
Regarding the title, could you kindly let us know if it includes WhisperX strategies as well? Compiling WhisperX.exe on Windows for automatic transcription in Subtitle Edit can be difficult for an average user. Thank you!

**Comment by Purfview** [comment]
Is it even compatible with Windows? What you mean by "WhisperX strategies"?

**Comment by gericho** [comment]
Correct me if I'm wrong (and I'm almost sure I am), seems WhisperX is more accurate because of the internal structure:

![pipeline](https://github.com/Purfview/whisper-standalone-win/assets/29167042/43d716cd-b2e4-41a8-ae6f-cf128ae2ae66)

they report this on the their [github](https://github.com/m-bain/whisperX) page.

`⚡️ Batched inference for 70x realtime transcription using whisper large-v2
🪶 [faster-whisper](https://github.com/guillaumekln/faster-whisper) backend, requires <8GB gpu memory for large-v2 with beam_size=5
🎯 Accurate word-level timestamps using wav2vec2 alignment
👯‍♂️ Multispeaker ASR using speaker diarization from [pyannote-audio](https://github.com/pyannote/pyannote-audio) (speaker ID labels)
🗣️ VAD preprocessing, reduces hallucination & batching with no WER degradation`


At the bottom, they show how to install it in Windows using Python/Conda. Unfortunately, Subtitle Edit is asking for an EXE file. Currently, I'm using the standalone faster-whisper.exe.

I'm just asking if there is room for improvement in the transcription.

![Untitled](https://github.com/Purfview/whisper-standalone-win/assets/29167042/b5ea4a47-10d5-4790-9a7d-2d8ebc3011fc)

**Comment by Purfview** [comment]
> ...seems WhisperX is more accurate...

Then why I see some posts that it's less accurate?
I guess you are asking about wav2vec alignment, currently it's not implemented.
Related question ->https://github.com/Purfview/whisper-standalone-win/issues/174

> I'm just asking if there is room for improvement in the transcription.

There always is room for improvement.
You can use [Standalone Faster-Whisper-XXL](https://github.com/Purfview/whisper-standalone-win/releases/tag/Faster-Whisper-XXL) and `--ff_mdx_kim2` option. [don't use it in SE!]

**Comment by gericho** [comment]
> Then why I see some posts that it's less accurate?

Good to know! Thank you! I'll try the XXL and follow the current test posts.
