### ISSUE TITLE
Allow `--highlight_words true` with `--sentence`

### ISSUE THREAD

**Issue by niksedk** [Purfview/whisper-standalone-win#228]
Could it be possible to allow `--highlight_words true` with parameters like `--sentence` or `--standard`?

The highlight is a nice feature, but a bit difficult to use in a subtitle with the current long blocks.

**Comment by Purfview** [comment]
Not with the current "--sentence" implementation, solution could be to enable the wonky original Whisper's max chars breaking, or to implement alternative code to do something similar like "sentence".

**Comment by niksedk** [comment]
OK

**Comment by Purfview** [comment]
Allowed and implemented in r189.1 -> https://github.com/Purfview/whisper-standalone-win/discussions/229

**Comment by Purfview** [comment]
> @Purfview so can I use highlight_words and sentence at the same time?

Yes, but --sentence isn't doing anything for highlight_words.

**Comment by niksedk** [comment]
> Allowed and implemented in r189.1 -> #229

Work very nice :)

SE beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip
