### ISSUE TITLE
Error: no such file or directory 

### ISSUE THREAD

**Issue by despairTK** [Purfview/whisper-standalone-win#23]
I downloaded Whisper-Faster r126 and replaced the original version, but when I run it, the following error message appears.

![QQ截图20230617101548](https://github.com/Purfview/whisper-standalone-win/assets/111871110/36e05bbd-7594-4268-b50f-b517cca0c971)

I don't know how to solve it, I need your help

**Comment by Purfview** [comment]
Your command syntax is not correct, file missing quote, and last argument missing value.
