### ISSUE TITLE
Using distil-whisper

### ISSUE THREAD

**Issue by vincaslt** [Purfview/whisper-standalone-win#230]
I wonder if distil-whisper models are supported by the standalone binaries already. Seems like faster-whisper has merged support for them, if they're not available in the standalone version, would it be possible to update them?

https://github.com/SYSTRAN/faster-whisper#distil-whisper

**Comment by Purfview** [comment]
Yes, distil-whisper models are supported, look the link in the post above.

**Comment by vincaslt** [comment]
Thanks, didn't realize. Are there macOS builds though?

**Comment by Purfview** [comment]
> Thanks, didn't realize. Are there macOS builds though?

Yes -> https://github.com/Purfview/whisper-standalone-win/releases/tag/faster-whisper
