### ISSUE TITLE
Faster-Whisper-XXL test2: Error code 126

### ISSUE THREAD

**Issue by Herzfrequenz21** [Purfview/whisper-standalone-win#232]
I installed XXL as you advised, but an error occurred

![320213795-2d8d7ac5-a9ff-4425-a947-aa09dbdb347f](https://github.com/Purfview/whisper-standalone-win/assets/166128009/3530b965-4c6b-4d24-a30c-d3594e52afb7)

**Comment by Purfview** [comment]
> I installed XXL as you advised, but an error occurred

 Use the latest version r192.1.1.
