### ISSUE TITLE
Errors on DTS audio tracks

### ISSUE THREAD

**Issue by Herzfrequenz21** [Purfview/whisper-standalone-win#236]
The full movie doesn't work.
But 30 minutes does.
I will not try further, because there is a possibility that this movie is an exception.
I decided to try with another movie with similar audio parameters - everything worked.

![Безымянный010](https://github.com/Purfview/whisper-standalone-win/assets/166128009/b67b9b87-d5b1-4b4e-825e-3097f5649230)

**Comment by Purfview** [comment]
Not same, now it's:

`Frame doesn't match AudioFifo parameters.`

Before it was:

`Residual encoded channels are present without core.`

![319981616-d8fd6a06-d075-4631-9c54-248001bf97c3](https://github.com/Purfview/whisper-standalone-win/assets/69023953/bad91655-d43f-4a65-9ec7-d7966cbf49e9)

**Comment by Purfview** [comment]
Errors shouldn't be different between `Faster-Whisper` and `Faster-Whisper-XXL`, probably you run now on the different audio.
Btw, both these are standalone.

Remux problematic audio removing other streams and upload it to https://wetransfer.com or mega.

**Comment by Herzfrequenz21** [comment]
Yeah, I guess so. I tried all three files - they all failed. I don't remember which ones and when exactly.
The files are too big. I made a torrent. Can you download it from me?
By the way, I didn't try to recognize audio files separately. So, if you suddenly succeed, maybe this is what will affect it.

[678.zip](https://github.com/Purfview/whisper-standalone-win/files/14910964/678.zip)

**Comment by Purfview** [comment]
Looks like it downloads.

**Comment by Purfview** [comment]
Reproduced error on ~700MB dts file, it comes from internal PyAV lib which is based on ffmpeg.
No error if external ffmpeg is used, you can trigger external ffmpeg use by any --ff... arg, for example `--ff_dump`, this command doesn't make any filtered change on audio.
Or with Faster-Whisper-XXL you can use the vocal extraction with `--ff_mdx_kim2`.

3GB file I'll check later.

**Comment by Purfview** [comment]
Same for 3GB DTS-HD file, if you trigger external ffmpeg use then it works.

I tried directly those files on ffmpeg, same errors reported there but it doesn't stop the process when PyAV breaks it.
Maybe those files are damaged as I tried some other DTS files and there were no such problems.
