### ISSUE TITLE
Need text file without timecodes

### ISSUE THREAD

**Issue by boykan313** [Purfview/whisper-standalone-win#24]
Hello! Tell me, what's the matter? It does not work for me. I have software installed, separately whaster-whisper is launched through python, but it won't work through yours. Help me please!
![Uploading 453.jpg…]()

**Comment by boykan313** [comment]
![453](https://github.com/Purfview/whisper-standalone-win/assets/90963133/0d6079d7-0386-456b-a10d-5bef4d5b8379)

**Comment by boykan313** [comment]
does not save work to a separate txt file. Tell me how can this be done? I do not plan to write subtitles for films, I need a clean transcription without timecode. How can I save the transcription result without timecodes?

**Comment by boykan313** [comment]
![543](https://github.com/Purfview/whisper-standalone-win/assets/90963133/149be8b8-2f8f-4ee9-91aa-21ce324bbabc)

**Comment by boykan313** [comment]
help me please=)

**Comment by Purfview** [comment]
You don't need to install anything nor Python at all.
You can use `-f=txt` option, there will be timecode but you can easily remove with some text editor.
For example with PSPad  `Edit>Selection Type>Column Selection` select columns with timecodes and delete them.

What you do with that text without timecodes?

**Comment by boykan313** [comment]
> Вам вообще не нужно ничего устанавливать или Python. Вы можете использовать `-f=txt`опцию, там будет тайм-код, но вы можете легко удалить его с помощью любого текстового редактора. Например, с помощью PSPad `Edit>Selection Type>Column Selection`выберите столбцы с тайм-кодами и удалите их.
> 
> Что вы делаете с этим текстом без таймкодов?


should this option be entered after transcription or before? I need this for work, I am a lawyer and I need to transfer the voice recording from the voice recorder to text with the highest quality for further work.

**Comment by boykan313** [comment]
![32211](https://github.com/Purfview/whisper-standalone-win/assets/90963133/5419ba97-c15b-438d-a36f-aadc09c4c42a)

**Comment by boykan313** [comment]
is my code
whisper-faster.exe "G:\Whisper\voz322.mp3" --language=Russian --model=large-v2 -f=txt

nothing happens. if I specify --f=txt then an error pops up.

![Uploading 322111.jpg…]()

**Comment by boykan313** [comment]
if I put it correctly, I don’t have any files with the results saved after the transcription is completed. They should appear next to the audio file, but they aren't there.

**Comment by Purfview** [comment]
> They should appear next to the audio file, but they aren't there.

No. They should appear next to the executable by default.
Next version I'll add an option to output txt without timexodes.

**Comment by boykan313** [comment]
> В следующей версии я добавлю возможность вывода txt без таймкодов.

Strange, I can't find these files anywhere. I looked in the folder with the audio file and in the folder with the whisper-faster itself.
Great! Thank you! When can we expect a new version? :)

**Comment by Purfview** [comment]
Just released r128. Use `-f=text`.
Check if it works as expected.

**Comment by boykan313** [comment]
> Just released r128. Use `-f=text`. Check if it works as expected.

It works, now at least it saves, but still with timecodes. And it only works for me in a folder with other python scripts.

**Comment by Purfview** [comment]
> but still with timecodes

It's impossible. Post your command.

> And it only works for me in a folder with other python scripts.

Probably because you call it from not it's folder, in such case you need to add it's folder path to [PATH environment variable](https://www.google.com/search?q=how+to+add+folder+to+PATH+environment).
Python install adds its folders to PATH, that's why programs there can be called from anywhere.

**Comment by boykan313** [comment]
![34221](https://github.com/Purfview/whisper-standalone-win/assets/90963133/0f3fe2e5-9938-4bb4-a784-ca937bfb5385)
You are right, thanks! I didn't really add it to the variable. Having made a separate folder and running the command line there, everything worked fine! But it outputs text with timecode..

Is my command:
whisper-faster.exe "G:\Whisper\voz322.mp3" --language=Russian --model=large-v2 -f=txt

**Comment by Purfview** [comment]
You run `-f=txt` instead of `-f=text`.

**Comment by boykan313** [comment]
> You run `-f=txt` instead of `-f=text`.

What same I not attentive. Thank you, it works! Tell me if there are ways or settings to improve the accuracy of transcription. Naturally, a lot depends on the quality of the audio recording, but are there settings to improve accuracy? You said that the setting of this transcription is more suitable for subtitles, by default ..

**Comment by Purfview** [comment]
> are there settings to improve accuracy?

There is no such magic setting, maybe you can look for some specifically finetuned model  for your language.

**Comment by boykan313** [comment]
> > есть ли настройки для повышения точности?
> 
> Такой волшебной настройки не существует, может быть, вы можете поискать какую-то специально доработанную модель для вашего языка.

where can i search? the developer's whisper or faster-whisper? Or in a completely different place.

and you helped me a lot in the previous question, thanks!

**Comment by Purfview** [comment]
Maybe here: https://huggingface.co/models?other=whisper&sort=downloads&search=-ru

**Comment by boykan313** [comment]
> Maybe here: https://huggingface.co/models?other=whisper&sort=downloads&search=-ru

Thanks a lot! You helped me a lot! I subscribed to your program and will wait for further updates! Good luck to you! Don't abandon the project! All the best!

**Comment by boykan313** [comment]
> Maybe here: https://huggingface.co/models?other=whisper&sort=downloads&search=-ru


Can you tell me how to integrate this model into faster whisper? after downloading and dropping it into the model folder, it can not be launched. Unable to specify large-v2-ru, it tries to download regular large-v2.
