### ISSUE TITLE
Repeated output issue

### ISSUE THREAD

**Issue by rajeevchourasiya** [Purfview/whisper-standalone-win#250]
It is repeating the initial and last bit of the original output again, as can be seen in the output; please help me in resolving this. TIA.

![image](https://github.com/Purfview/whisper-standalone-win/assets/130376260/729817d0-0dc3-4825-a5e2-fa086bf9d396)

the command that I'm using is this: 
![image](https://github.com/Purfview/whisper-standalone-win/assets/130376260/e46558b3-c90a-4369-a28f-65f5eae64ad5)

**Comment by Purfview** [comment]
Share that "test.m4a".
And that command obviously is not the one used to get "data.text" file.
