### ISSUE TITLE
Is wisper-standalone-win is closed source?

### ISSUE THREAD

**Issue by Codereamp** [Purfview/whisper-standalone-win#251]
I know that the project's engine uses different foss projects available elsewhere, but this excellent software itself is closed source, right? Every source (zip, tar.gz) just loads a small readme. Can you specifically mention this on the frontpage?

As for myself, I know that there might be reasons for this, it just very convenient to download the sources, index them and see why things work as they do with my own eyes.

**Comment by Purfview** [comment]
> Is wisper-standalone-win is closed source?

No, I don't think that it's even possible.

**Comment by vincaslt** [comment]
> > Is wisper-standalone-win is closed source?
> 
> No, I don't think that it's even possible.

Where can we find the source code though? Releases include a zip with readme only.

**Comment by Purfview** [comment]
https://github.com/openai/whisper
https://github.com/SYSTRAN/faster-whisper
