### ISSUE TITLE
transcription as best as possible

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#253]
Hey, I'm back because you changed something, whisperer, and I don't know what commands to add to make it as good as possible when transcribing. Can you recommend something?

**Comment by Purfview** [comment]
Try `--ff_mdx_kim2` with Faster-Whisper-XXL.

**Comment by nielka98** [comment]
but I'm asking her about the normal Whisper, not the XXL one, and I still can't get the console to work

**Comment by Purfview** [comment]
> best as possible 

Do not ask "what's best" because this question cannot be answered objectively. Each and everyone has their own view about what's best in a certain area. The best is what works best for you!

>I still can't get the console to work

Maybe there are online tutorials how to use Windows.

**Comment by nielka98** [comment]
I have two questions, does Whisper XXL work in the Subtitle Editor? and secondly, could you post links to manual installation of cuBLAS and cuDNN CUDA?

**Comment by Purfview** [comment]
At the moment SE doesn't support XXL, libs are always in same place at the Releases.
