### ISSUE TITLE
new Whisper old problems

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#255]
hey, I know you're fed up with me, but as they say, stupidity is endless. Listen, it's appeared again:RuntimeError: CUDA failed with error out of memory error.
and the commands -bs=10 or -bo=1 don't work, any ideas?

**Comment by Purfview** [comment]
You posted same thing multiple times already, just reread your old threads where you posted.

https://github.com/Purfview/whisper-standalone-win/issues?q=memory+out

Buy GPU with more memory or use smaller models.

**Comment by nielka98** [comment]
it's not a card problem, I'm wondering if it's a lack of disk space problem

**Comment by nielka98** [comment]
But where this certainty worked, it doesn't work now

**Comment by Purfview** [comment]
It comes from that your GPU doesn't have enough VRAM.

It worked before because you used different settings or different audio.

**Comment by nielka98** [comment]
Well, this means that there is no space for the graphics card because there is no space on the disk. Well, it works, now it has stopped working and it is a problem with the graphics card. Logically no.

**Comment by Purfview** [comment]
That is nonsense, that's not how computers work.
I wrote you where is the problem and how to solve it, you just waste your time fantasizing about things you don't understand.

**Comment by Purfview** [comment]
Or use CPU instead of GPU with `--device cpu` setting.
