### ISSUE TITLE
--highlight_words true --max_line_width 43 --max_line_count 2

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#256]
First of all, I'm sorry because I think I pissed you off last time, which wasn't my intention. I'm quite a clumsy person and sometimes I have to explain something several times, like a cow in a ditch. This is the additional feature that childhood cerebral palsy gives.

Secondly, I pasted this command because I use it and the results it gives are amazing, but it makes the lines repeat. There are an awful lot of them. Example: when I use the --standard command, there are about 1500 lines. And when I use the title command, there are about 10,000 lines. I have a question whether this is a bug and whether it can be fixed somehow, or is it just the nature of this command and you have to love her with all the benefits of the inventory.

**Comment by Purfview** [comment]
> First of all, I'm sorry because I think I pissed you off last time, which wasn't my intention. 

Not at all, 

> I pasted this command because I use it and the results it gives are amazing, but it makes the lines repeat.

That's normal, it makes karaoke subs, if you don't want karaoke subs then don't use highlight_words.
What is wrong with --standard?

**Comment by nielka98** [comment]
--standard It is less accurate...I don't know what you did with the commands I use, but they are really much better

**Comment by nielka98** [comment]
Could you tweak it so that it has a standard command?

**Comment by Purfview** [comment]
All these command mentioned here don't have anything to do with any "accuracy".
So, basically I can make sense of what you posted here.

**Comment by Purfview** [comment]
What means "better fit"?

**Comment by nielka98** [comment]
Better placed They match the audio better. I don't know how to write it better, I'm writing it using Google Translator, so the translation doesn't have to be good either

**Comment by Purfview** [comment]
All those commands mentioned in this thread don't have any influence on "match the audio better".

**Comment by Purfview** [comment]
I don't think that you'll go anywhere without posting the examples.

**Comment by nielka98** [comment]
I mean that the subtitles are better matched to the sound.

**Comment by nielka98** [comment]
> Nie sądzę, że nigdzie nie pójdziesz bez zamieszczenia przykładów.

😂😂😂
I'll attach the log to you tomorrow

**Comment by Purfview** [comment]
Maybe you want to read this again -> https://github.com/Purfview/whisper-standalone-win/issues/256#issuecomment-2101290022

That means that those commands have same influences on "match the audio better" like a water tap turned on in your kitchen.

**Comment by Purfview** [comment]
So, don't waste your time.
Probably you observed non-deterministic effect of Whiper model.

**Comment by nielka98** [comment]
Ok, I'll experiment and see. Are you planning to add a subtitle editor to Whisper Turbo?

**Comment by nielka98** [comment]
Okay, I'll see and experiment... You are going to add your Whisper XXL to the Subtitle Editor?

**Comment by Purfview** [comment]
Me not, I dunno C#, ask nikse.

**Comment by nielka98** [comment]
Can I use this topic as it's for you? I have many questions and I don't want to open new topics all the time

**Comment by Purfview** [comment]
Always open a new topic for a new question.
