### ISSUE TITLE
How to make the sentence segmentation more precise

### ISSUE THREAD

**Issue by BlueBlue7891** [Purfview/whisper-standalone-win#257]
Hello, I've been using this tool in SE for a while now. It's really handy, but I've encountered a few minor issues. 

1. How to make the sentence segmentation more precise? 
2.  I often get very short sentences, like 300 lines where the first 50 lines have normal sentence lengths but the rest become very short. I'm not sure what's causing this. How should I configure it to improve this issue?

**Comment by Purfview** [comment]
1. I don't understand what you meant.
2. Same as above.
