### ISSUE TITLE
cuBLAS dll file takes too much space

### ISSUE THREAD

**Issue by actforjason** [Purfview/whisper-standalone-win#258]
How to use the NVIDIA CUDA Toolkit installed on the system instead of being so bloated?
![图片](https://github.com/Purfview/whisper-standalone-win/assets/57058325/9aed402e-121d-4177-b609-5a039b96e246)

**Comment by Purfview** [comment]
Delete those files if you think that you don't need them.

**Comment by Purfview** [comment]
>We don't need them if we don't have nvidia right?

Yes.
