### ISSUE TITLE
Server/online mode to quickly process files on demand while keeping things in memory

### ISSUE THREAD

**Issue by Wizek** [Purfview/whisper-standalone-win#261]
I see that there is already something somewhat similar, batch processing at #29 

Not sure what interface would make sense if running in server mode, maybe simple http api, maybe CLI daemon that can be interacted with a client CLI command. If the former maybe a simple GUI could be added too for quick file drag and drop or dictation. I'm somewhat interested in this, would there be interest to merge if I implement something in this direction?

Of course the GUI variant can be done separately if some other server support is added.

**Comment by Purfview** [comment]
> Server/online mode to quickly process files on demand while keeping things in memory

For this you should look at some another repo dedicated for a server API usage.
This repo is not compatible with that.

> maybe a simple GUI could be added too for quick file drag and drop

You can "drag and drop" to CLI too.

**Comment by Purfview** [comment]
https://github.com/ycyy/faster-whisper-webui
