### ISSUE TITLE
192.3 in Subtitle Edit, incomplete transcriptions

### ISSUE THREAD

**Issue by rsmith02ct** [Purfview/whisper-standalone-win#263]
I've been using Faster Whisper from the start and since it was integrated into Subtitle Edit using that as a front-end.
Recently I've noticed that my transcriptions are stopping partway through and am not sure why. I do get a SRT file, it's just that it only has some of the audio from the original file transcribed. 

The GPU in use is a GTX 1050 (4GB) mobile and it's worked quite well with CUDA.

Is there a way to figure out why it quits? Is it that it encounters a gap in the audio or a different language and stops?

Happy to do some tests if you have any guidance on where to start or advanced parameters through Subittle Edit that would help.

**Comment by Purfview** [comment]
> Is there a way to figure out why it quits?

Use it directly in a terminal/console.

> Is it that it encounters a gap in the audio or a different language and stops?

It's because you have not enough VRAM and it crash with the out of memory error.

**Comment by rsmith02ct** [comment]
I just had a chance to do more testing.

On my desktop (RTX2080 8GB VRAM) I had no issues with any of the video
files I tried.

On my laptop it generally worked though one PCM wav is giving me trouble.
It gets to 4:54 min out of a 1 hour 34 min file and stops. I also assumed
it was a VRAM issue though watching it in task manager the GPU goes from 2
to 3GB used out of 4 and then back again.

From the command line with the same large v2 model I see less usage, 1.6 to
3.1.

You are right though it has the error:

"File "D:\whisper-fast\__main__.py", line 1600, in <module>
  File "D:\whisper-fast\__main__.py", line 1527, in cli
  File "faster_whisper\transcribe.py", line 1373, in
restore_speech_timestamps
  File "faster_whisper\transcribe.py", line 722, in generate_segments
  File "faster_whisper\transcribe.py", line 1072, in generate_with_fallback
RuntimeError: CUDA failed with error out of memory
[19540] Failed to execute script '__main__' due to unhandled exception!"

Is Windows not showing all the GPU VRAM usage? It's too bad as largev2 does
work sometimes.

I tried it again with the medium model and it easily gets past 4:50. It's
about at 1.7GB VRAM maximum. GPU-Z reports up to 2420GB but mostly under
1800.

I guess there is nothing to be done other than a smaller model or better
GPU?

**Comment by Purfview** [comment]
8GB should be enough for the large models, maybe your internet browser or other soft is using VRAM too.
Try Faster-Whisper-XXL.

Check with `--verbose true` what compute type is in use.

**Comment by rsmith02ct** [comment]
I just downloaded and tested XXL (on my laptop, 4GB) with large v2. With just this browser (Firefox) open, testing it on the same audio file it says it is using my GTX1050 with intl8_float32. I see nearly 100% CUDA activity in task manager.

With large v2... it made it to 10 minutes and then gave up when it ran out of memory. Oh well!

**Comment by Purfview** [comment]
Try to reduce `--best_of` till it takes less than 4GB memory.

**Comment by Purfview** [comment]
> Is there a quality downside to this setting?

Yes, but very small.

If it's audio from a movie then you can use `--ff_mdx_kim2 --vad_alt_method pyannote_v3` to increase quality [that's with Faster-Whisper-XXL].
