### ISSUE TITLE
When the --sentence option is enabled, some names in the transcription will be broken.

### ISSUE THREAD

**Issue by despairTK** [Purfview/whisper-standalone-win#264]
When the --sentence parameter is enabled, some names in the transcription results will be split into two lines, this resulted in some errors in subsequent machine translation.

For example:

```
6
00:01:03,670 --> 00:01:04,430
There's Wile E.

7
00:01:04,530 --> 00:01:07,730
Coyote, you know, of the roadrunner and coyote fame.

421
00:45:22,420 --> 00:45:24,340
It's almost got a, almost got a Wile E.

422
00:45:24,440 --> 00:45:29,080
Coyote feel to it, but it's, this one's still more dog-like than the coyote is.
```

This is the result of a transcription of a person's name that I recorded and read by Microsoft AI:

```
1
00:00:03,780 --> 00:00:04,520
Willard E.

2
00:00:04,620 --> 00:00:09,700
Boyle Louis-Jacques Mandiguer H.

3
00:00:09,960 --> 00:00:10,140
G.

4
00:00:10,320 --> 00:00:15,200
DeMelt Christian Johan Doppler J.

5
00:00:15,400 --> 00:00:15,560
D.

6
00:00:15,740 --> 00:00:21,580
Van Der Waals Michael Faraday Enrica Fermi

```
This is the correct name:
```
Willard E. Boyle
Louis Jacques Mand Daguerre
H. G. Dehmelt
Christian Johann Doppler
J. D. vanderwaals
Michael Faraday
Enrica Fermi
```

Here is the audio of the test names:
[0530.zip](https://github.com/Purfview/whisper-standalone-win/files/15495960/0530.zip)

**Comment by Purfview** [comment]
Yes, it splits on such one letter abbreviations, not sure if we need to do something about it as it's rare case when such abbreviations are spoken.
