### ISSUE TITLE
Not working with a non-English language

### ISSUE THREAD

**Issue by JDTR75** [Purfview/whisper-standalone-win#265]
Hi Purfview!

I'm getting this error whenever I try to transcribe anything that's not in English:

![image](https://github.com/Purfview/whisper-standalone-win/assets/1891941/2f3681e5-a3e2-422d-b817-0ea0e8d2123c)

What am I doing wrong? Ty in advance!

**Comment by Purfview** [comment]
This model is not multilanguage, it's English only.

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/discussions/180
