### ISSUE TITLE
unable to remove timestamps

### ISSUE THREAD

**Issue by walrusthief** [Purfview/whisper-standalone-win#266]
I can't seem to remove the timestamps from the output. I've tried without_timestamps=true and word_timestamps=false, but neither seems to do the trick. Is there a function I'm missing?

![timestamps](https://github.com/Purfview/whisper-standalone-win/assets/113811239/c1045c19-3e44-4e96-b909-9f1a2c5abdf4)

**Comment by Purfview** [comment]
`-f text`
