### ISSUE TITLE
Some peculiar effects of --initial_prompt

### ISSUE THREAD

**Issue by despairTK** [Purfview/whisper-standalone-win#269]
Recently I found a strange effect of the --initial_prompt parameter on the text.

When I use `--initial_prompt auto` or `--initial_prompt default` or `--initial_prompt ",."` (write some random sentences or simple punctuation marks), some words in the transcribed text will be wrongly selected. For example:

00:01:15,780 --> 00:01:23,300
今回は便宜上、大ラフ、【千ラフ】、色ラフ、詳細ラフと4段階に分けて呼んでいくことにします。

00:01:39,720 --> 00:01:49,300
【千ラフ】っていうのはこんな感じで大雑把ではあるんですけどある程度線がわかりやすくなっている感じのラフのことを呼んでいます。

When I use `--initial_prompt None` :

00:01:15,780  --> 00:01:23,340
今回は便宜上大ラフ【線ラフ】色ラフ詳細ラフと4段階に分けて読んでいくことにします

00:01:39,720 --> 00:01:49,340
【線ラフ】っていうのはこんな感じで大雑把ではあるんですけどある程度線がわかりやすくなっている感じの ラフのことを読んでいます

【】 marks are comparison points.

The comparison results of the two groups show that when using `--initial_prompt`, whether filling in auto, default, or writing a random sentence or just simple punctuation, some words will have an incorrect effect.

However, without `--initial_prompt`, some audio files cannot be segmented correctly and punctuation cannot be generated. I wonder if the situation I mentioned can be fixed?

**Comment by Purfview** [comment]
>I wonder if the situation I mentioned can be fixed?

Add correct word to prompt.
