### ISSUE TITLE
update to 1.0.3

### ISSUE THREAD

**Issue by vincaslt** [Purfview/whisper-standalone-win#277]
Would you be able to update it? Or is there a way to build faster-whisper to standalone on my own?

**Comment by Purfview** [comment]
Why you need "1.0.3"?

**Comment by vincaslt** [comment]
I thought giving https://github.com/SYSTRAN/faster-whisper/pull/807 a shot, though now I'm not so sure if it could solve a problem I want solving.

I'd like to somehow preload a model and use it between faster-whisper cli calls, rather than having the cli load the model every time - batch processing won't really work for me.

**Comment by Purfview** [comment]
To use that feature you need to use Python, not standalone exe, I think.

Eventually I'll update to latest commit, but so far there is nothing important in the commits after 192.
