### ISSUE TITLE
--Sentence

### ISSUE THREAD

**Issue by Narbs1** [Purfview/whisper-standalone-win#285]
When I add the command line --sentence, I get the following error message:

**Error: --sentence requires --word_timestamps=True**

Adding --word_timestaps=True doesn't resolve it, the same error occurs. 

Per the --help page:

_--word_timestamps WORD_TIMESTAMPS, -wt WORD_TIMESTAMPS
                        Extract word-level timestamps and refine the results based on them (default: True)_

Shouldn't it be activated by default?

Same error occurs with --standard, which should also activate --sentence

**Comment by Purfview** [comment]
Share the full command.

**Comment by Narbs1** [comment]
faster-whisper-xxl.exe "G:\test.mp4" --language German --model large-v3 --output_dir source --output_format text --sentence 

and

faster-whisper-xxl.exe "G:\test.mp4" --language German --model large-v3 --output_dir source --output_format text --sentence --word_timestamps=True

**Comment by Narbs1** [comment]
SOLVED: Doenst work on text format.

**Comment by Purfview** [comment]
It works only for srt/vtt output files.

**Comment by Narbs1** [comment]
What command would I use for text output to get one sentence per line? Is there an equivalent command?

**Comment by Purfview** [comment]
--Sentence - "works only for srt/vtt output files."

**Comment by Purfview** [comment]
You can open srt file for example with Subtitle Edit and export it to whatever format you want.

**Comment by Narbs1** [comment]
I understood that part. When opting for text output, sometimes I get 20 words per line and other times many lines with 3-5 words. I was wondering whether text output could also be forced to enter more words per line, eventually full sentences.

**Comment by Purfview** [comment]
> I was wondering whether text output could also be forced to enter more words per line, eventually full sentences.

Empirically, it could be.
