### ISSUE TITLE
Three transcription problems

### ISSUE THREAD

**Issue by oep42** [Purfview/whisper-standalone-win#295]
Using Faster-Whisper-XXL_r192.3.4_windows.

**Initial**

Problem with inital in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf problem 2-B](https://github.com/user-attachments/assets/5ae80ccf-72d3-4d4b-a42f-35fb094447aa)

Problem with initals in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf Problem 2-A](https://github.com/user-attachments/assets/c9bfb1d2-e476-4c70-9b88-77a6a1dfaebc)

**Hyphen**

Problem with hyphen in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf Problem 3-C](https://github.com/user-attachments/assets/7e16f3c2-c18f-4456-8e91-bdf963662e47)

Problem with hyphen in "Glass-Steagall" in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf problem 3-B](https://github.com/user-attachments/assets/e71e4363-b97c-470d-9112-af9bc0543814)

Problem with hyphen in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf problem 3](https://github.com/user-attachments/assets/5f192a10-442e-4335-beea-8f591377b2ce)
(When a line break followed by a hyphen, is automatically removed or repositioned in Subtitle Edit, it is replaced by a space. If this is removed automatically from this sentence, it will change into this: "In 1936, Roosevelt stood for re -election.")

Instead of like this:
```
There was something about this middle
-class Florentine housewife that
```
It should look like this:
```
There was something about this middle-
class Florentine housewife that
```
This would be even better (no risk of problems with subsequent processing):
```
There was something about this
middle-class Florentine housewife that
```
This would also be better:
```
There was something about this middle-class
Florentine housewife that
```

This problem with a hyphen, may be related to what is discussed [here](https://github.com/SubtitleEdit/subtitleedit/issues/8736).

**Comma**

Problem with comma in a transcription with --standard:
![Purf Problem 1-A](https://github.com/user-attachments/assets/938fce33-c606-4315-a3ea-61894a15e953)

Problem with comma in a transcription with --max_line_width 37 --max_line_count 2 --sentence --max_comma_cent 50:
![Purf Problem 1-B](https://github.com/user-attachments/assets/386596e7-9722-4795-9fb6-314dbb0e55af)
(When a line break followed by a comma, is automatically removed in Subtitle Edit, it is replaced by a space. If this is removed automatically from this subtitle, it will change into this: "under the Linden, how there were 100 ,000 of people when they passed".)

It would be best if line breaks were only created at positions where the line break can be replaced by a space character.

**Added later**: It may not be possible to find a satisfactory solution for the problem with initials. See [here](https://github.com/SubtitleEdit/subtitleedit/issues/8714#issue-2454128744).

**Added later:** Not sure how many people pronounce the English abbreviations "i.e." and "e.g." as letters, but if they do, something like this can happen:
![abbreviation ie](https://github.com/user-attachments/assets/abcb4665-5ce9-4eaf-bc8c-055dd5d70470)

**Comment by Purfview** [comment]
> Initial

Wouldn't be hard to add such one letter exceptions, but then there will be cases where initial or one letter with a dot is the end of a sentence and it won't be split.

> Hyphen
> Comma

Do you have json file for an example?

In general, for such issues please provide json and the commands used.

**Comment by oep42** [comment]
I am using Faster-Whisper-XXL from within Subtitle Edit. What should I do to get a json file?

**Comment by Purfview** [comment]
> I am using Faster-Whisper-XXL from within Subtitle Edit. What should I do to get a json file?

`-o all` will output all formats

**Comment by oep42** [comment]
This zip file contains audio, srt, and json files of the hyphen and comma issues (including information about the parameters used):
[Three transcription problems (Hyphen, Comma).zip](https://github.com/user-attachments/files/17836380/Three.transcription.problems.Hyphen.Comma.zip)

**Comment by Purfview** [comment]
I'm looking it. Btw, you may want to update "Faster-Whisper-XXL r192.3.4" to the latest version as r192.3.4 has three rare bugs in subtitle writing.

**Comment by Purfview** [comment]
**Initials.**

In your opinion if capitals would be added then there would be less wrong splits than wrong non-splits?
Is it better to have a wrong split or a wrong non-split?

Here is the current list of exclusions, these won't be treated as end of sentence:

`
 ['Arq.', 'bl.', 'Cnel.', 'dipl.', 'dr.', 'Dr.', 'Dra.', 'DRA.', 'Eng.', 'eng.', 'Exmo.', 'exmo.', 'Frk.', 'g.', 'Gov.', 'gov.', 'gosp.', 'Gral.', 'Hr.', 'Ing.', 'ing.', 'jr.', 'Jr.', 'Lic.', 'Mna.', 'mna.', 'Mno.', 'mno.', 'Mr.', 'mrs.', 'Mrs.', 'Mrs.', 'Mtro.', 'Mtra.', 'Ms.', 'P.', 'pe.', 'Pe.', 'Prof.', 'prof.', 'Sr.', 'sr.', 'Sra.', 'Srs.', 'srs.', 'Srta.', 'St.', 'sv.', 'Tte.', 'vlč.', 'vol.', 'vols.']
`

If you have any additions then post them here.



Btw, this is the list of words affected by `--min_dist_to_end`:
`
['a', 'an', 'Dr.', 'Jr.', 'Mr.', 'Mrs.', 'Ms.', 'Sr.', 'St.', 'the', 'The']
`

**Comment by oep42** [comment]
I can confirm that the hyphen and comma issues are fixed fixed in r194.2. Thank you.

Thanks for specifying the list of `--min_dist_to_end`, because I couldn't find this until now.

Need some time to think about wrong splits and wrong non-splits.

**Comment by oep42** [comment]
Cool that dots in numbers are fixed as well. This post can be seen as brainstorming without knowledge of what is practically feasible, as a response to "maybe some option could be added like if new break is shorter by some percentage from max width then not break".

With the current implementation of the --sentence parameter, after each end of a sentence, the next sentence is placed in the next subtitle line. This approach works fine most of the time, except when the last part of a sentence that is placed in a new subtitle line, is very short — or when the sentence itself is very short. Then you may get a very short subtitle line of one or two words with a short duration. Such short lines usually need to be corrected afterwards.

I think a new option to avoid such short lines, would be very welcome. Such a new option would check how long the current subtitle line would be if the next sentence would be placed in the next subtitle line. If this length is below a certain threshold, this new option should prevent the next sentence from being placed in the next subtitle line (so that the beginning of the next sentence is placed in the same subtitle line, right after the end of the previous sentence). Such an approach would be a solution for all short lines, except when the very last subtitle line is a short line. (For such a short last line, a separate solution could be invented that is used only for a short last line.)

Such a new option could be like this:

**--min_period_cent {30,40,50,60,70,80,90,100} (requires --sentence) Minimum line length as percentage of --max_line_width that is required for breaking the line after a sentence ending (. ! ?). Note: 100 = disabled. (default: 100)**

This suggested new option "--min_period_cent" is based on the existing option "--max_comma_cent", and works for sentence endings (. ! ?) in the same way as "--max_comma_cent" works for commas.

(To me, the "max" in the name "--max_comma_cent" is confusing, because this is about a minimum, not about a maximum. Also, to me, "--max_line_length" would be clearer than "--max_line_width".)

Although a relative way of determining the minimum line length makes the most sense to me, an 'absolute' version of the suggested new option could be based on the existing "--max_comma" option:

 **--min_period MIN_PERIOD (requires --sentence) Minimum line length as minimum number of characters that is required for breaking the line after a sentence ending (. ! ?). Note: disabled if it's over or equal to --max_line_width. (default: 250)**

The biggest problem with very short subtitle lines, is their usually short duration. Many people might appreciate a duration-based option, like this:

**--min_dur_period (requires --sentence) Minimum duration of line in milliseconds that is required for breaking the line after a sentence ending (. ! ?). Note: Disabled if it's greater than or equal to the (de facto) maximum duration of subtitle lines. (default: ...)**

These suggested new options should also work for multiple short lines in a row. So with any of these options, it should be possible to generate a subtitle line like this: "That's it. Do it. Good! Good! Again! Yes!"

If more than one of these options is active, the strictest minimum limit should be applied.

The names of the suggested new options above, are modeled after existing option names. I think the following option names would be clearer than the ones used above:
"--min_relative_line_length" instead of "--min_period_cent"
"--min_line_length_chars" instead of "--min_period"
"--min_line_duration" instead of "--min_dur_period"

**Comment by Purfview** [comment]
Every sentence should be in the new line, no exceptions or there is no point in --sentence then, I didn't meant to add multiple sentences in one line, I meant not to break a sentence neglecting "max_line_width".

>To me, the "max" in the name "--max_comma_cent" is confusing, because this is about a minimum, not about a maximum. 

Then your brain works in reverse because it's about setting the maximum, it doesn't do anything on the lower values, its minimum is always 0%.  By your logic why --max_line_width isn't confusing then, it sets similar thing. 😄

>Also, to me, "--max_line_length" would be clearer than "--max_line_width".

For me too, but that's how it's named in reference whisper.

**Comment by oep42** [comment]
> Every sentence should be in the new line, no exceptions or there is no point in --sentence then


There are already exceptions. If a list of exclusions, --max_gap, and --min_dist_to_end make sense as exceptions to --sentence, other exceptions may also make sense. An optional exception that improves the result of --sentence for some users, makes sense. 

Starting sentences in a new line with the condition that the end portion of the last sentence in the previous line is not shorter than some minimum length, makes sense as an exception, because it can prevent having to correct short lines later.

If there is a minimum duration condition, combining several very short duration 'sentences' in one line to reach that minimum, makes sense.

**Comment by Purfview** [comment]
>--max_gap

That's to end a sentence because Whisper didn't put an end to it.

>--min_dist_to_end

Is about where to make a break.

Your proposed settings are opposite of the core functionality of --sentence - "splitting lines to sentences", that means every sentence should start in a new line no matter what.

**Comment by oep42** [comment]
I understand your logic. 

If there is user demand for a conditional variant of --sentence, for example named --sentence_cond, which allows conditional exceptions to the rule that each sentence should start on a new line, would you consider implementing it?

**Comment by Purfview** [comment]
> would you consider implementing it?

No, this repo is not meant to be for subtitle editing, I don't want to bother with such, you should ask at repos meant for this task.

**Comment by oep42** [comment]
I understand. Thank you very much for creating Standalone Faster-Whisper.

**Comment by oep42** [comment]
Added later, as a response to "For other functionality you need to use the subtitle editing tools like SE":

If word level timestamps are known by Faster-Whisper-XXL during processing, Faster-Whisper-XXL could use that knowledge to prevent short lines with a --sentence_cond parameter while keeping spoken words and subtitles synchronized.

In post-processing tools like SE, such word level timestamps are not known, so SE cannot always adequately automatically correct short lines (because when a split is required for such a correction, SE doesn't know the timestamp of the word where it wants to split a line — so at such a split, spoken words and subtitles may not be synchronized).

If the above thoughts are true, and if synchronisation between spoken words and subtitles is important, then automatically preventing short lines can only adequately be done by a tool like Faster-Whisper-XXL, and not by post-processing tools like SE.

**Comment by Purfview** [comment]
Short lines merging should be manual as automatically you can't be 100% sure that those lines to be merged are from the same speaker.

**Comment by oep42** [comment]
Thanks for pointing out that when more than one person is talking in a video, a sequence of two or more short sentences should not be merged automatically. (Earlier I did not think about the possibility of more than one speaker in a video. A silly oversight.) Merging what two different speakers say into one line, is, in general, not a good idea. I agree that with a sequence of two or more short sentences, short line merging should be done manually, because there may be more than one speaker.

With a multi-short-sentence example with multiple speakers like this:
```
   Hello!
   How are you?
   I'm fine.
```
this may be manually changed into this:
```
   Hello! How are you?
   I'm fine.
```
or like this:
```
   Hello! How are you?<br />- I'm fine.
```
or like this:
```
   - Hello! How are you?<br />- I'm fine.
```

With a multi-short-sentence example with one speaker like this:
```
   That's it.
   Do it.
   Good!
   Good!
   Again!
   Yes!
```
this may be manually changed into this:
```
   That's it. Do it. Good! Good! Again! Yes!
```
or like this:
```
   That's it. Do it. Good!
   Good! Again! Yes!
```
or otherwise, if there is a long pause in between the saying of some of these sentences.

So if there is a sequence of two or more short sentences, then the merging should be done manually.

However, in situations where a long line without a sentence ending (such as ".", "!", and "?") is followed by a short line, as in this example:

![Image](https://github.com/user-attachments/assets/9874dda8-a56b-458a-ba7b-aebac98c3db7)

there can be only one speaker, and then automatic merging does not run the risk of merging two different speakers into one line.

Even in a situation like this:

![Image](https://github.com/user-attachments/assets/2062cab1-f2f6-4511-a5c1-b1827ec175e0)

there can be only one speaker, and then automatic merging does not run such a risk either.

So any sequence of a long line and a very short line, can be automatically merged if the first of these two lines does not end with a sentence ending.

(If it is certain that there is only one speaker in a video, then sequences of two or more short sentences in that video can be merged automatically, provided that there is no long pause in between the saying of these sentences.)

**Comment by Purfview** [comment]
> However, in situations where a long line without a sentence ending (such as ".", "!", and "?") is followed by a short line, as in this example:
> 
> ![Image](https://github.com/user-attachments/assets/9874dda8-a56b-458a-ba7b-aebac98c3db7)
> 
> there can be only one speaker, and then automatic merging does not run the risk of merging two different speakers into one line.

Yes, but then what's the the point of the max characters. Each of these subs should be split to the two separate subs.


> Even in a situation like this:
> 
> ![Image](https://github.com/user-attachments/assets/2062cab1-f2f6-4511-a5c1-b1827ec175e0)
> there can be only one speaker, and then automatic merging does not run such a risk either.

Usually such shouldn't be produced by faster-whisper-xxl.

>So any sequence of a long line and a very short line, can be automatically merged if the first of these two lines does not end with a sentence ending.

And it's merged like that already with --sentence, unless it's split by some other rule.

For what do you use this automatic splitting/merging?

**Comment by oep42** [comment]
The example with "At... that time" is indeed an unusual case, primarily meant as an example of "the other extreme case of a long and short line". However, the examples with "Alps." and "reason.", are examples of what happens regularly when using --sentence.

> And it's merged like that already with --sentence, unless it's split by some other rule.

It is not. On the contrary, --sentence regularly produces such long-short-line combinations that need to be merged afterwards (or perhaps corrected in another way). After ".", "!", or "?", --sentence always starts with a new subtitle, irrespective of the length of the subtitle that ends with ".", "!", or "?". Whenever a sentence just does not fit within the maximum line length, --sentence creates a long-short-line combination. Because of this, --sentence regularly produces short subtitles like "Alps." and "reason." that need te be corrected afterwards.

The ideal is to minimize the manual work needed for generating subtitles, by doing as much as possible automatically — first with Faster-Whisper-XXL, and after that with a tool like Subtitle Edit. The examples with "Alps." and "reason.", are examples of something that happens regularly when using --sentence. If such short subtitles can be prevented automatically, that would eliminate the need for manual correction of such short subtitles afterwards.

Assuming that Faster-Whisper-XXL is aware of word-level timestamps during processing, it could, when it sees that a short line like "Alps." or "reason." is going to be created after a long line, intervene and prevent that from happening, by distributing the text of that long line and the following short line evenly between those two lines. In this way, the line lengths will stay within the 'max characters' constaint, and no very short lines will be created.

> For what do you use subtitles produced with automatic splitting/merging?

I am not looking for subtitles specifically produced with automatic splitting/merging. I am just looking to minimize the manual work required to generate subtitles.

**Comment by Purfview** [comment]
>It is not. On the contrary, --sentence regularly produces such long-short-line combinations that need to be merged afterwards (or perhaps corrected in another way). After ".", "!", or "?", --sentence always starts with a new subtitle, irrespective of the length of the subtitle that ends with ".", "!", or "?". Whenever a sentence just does not fit within the maximum line length, --sentence creates a long-short-line combination. Because of this, --sentence regularly produces short subtitles like "Alps." and "reason." that need te be corrected afterwards.

Such behaviour would be a bug, share the json and the full command used.

>The ideal is to minimize the manual work needed for generating subtitles, by doing as much as possible automatically — first with Faster-Whisper-XXL, and after that with a tool like Subtitle Edit. The examples with "Alps." and "reason.", are examples of something that happens regularly when using --sentence. If such short subtitles can be prevented automatically, that would eliminate the need for manual correction of such short subtitles afterwards.

That doesn't eliminate the need to correct them, as subs would be incorrect after such merge.

>Assuming that Faster-Whisper-XXL is aware of word-level timestamps during processing, it could, when it sees that a short line like "Alps." or "reason." is going to be created after a long line, intervene and prevent that from happening, by distributing the text of that long line and the following short line evenly between those two lines. In this way, the line lengths will stay within the 'max characters' constaint, and no very short lines will be created.

Sorry but I don't understand how "the line lengths will stay within...".

**Comment by oep42** [comment]
This zip file contains audio, srt, and json files of the long-short-line combinations issue (including information about the parameters used): [Long-short-line combinations.zip](https://github.com/user-attachments/files/18650454/Long-short-line.combinations.zip). The examples below which were generated by Faster-Whisper-XXL, are included in this zip file.

In an earlier post, I incorrectly spoke of “automatic merging.” The "merging" in that was completely incorrect. My brain does not seem to have been sufficiently switched on at the time. In my last post, I used the terms "line" and "subtitle" interchangeably, while I meant "subtitle" each time. This may cause confusion, as there may be multiple "lines" within a "subtitle". ("Long-short-line combinations" should actually be "long-short-subtitle combinations".) Sorry for the incorrect use of "merge" and the unclear wording. Below I will use images to explain what I was trying to say earlier. After that, I will add something about two lines within a subtitle.


**Two consecutive subtitles**

The first of the two images below is an example of what was generated by Faster-Whisper-XXL, and the second is a manually created example of how this could be improved.

![Image](https://github.com/user-attachments/assets/c2d1d876-5454-4142-a3b9-6b587acacf72)

![Image](https://github.com/user-attachments/assets/49cb813c-6032-4b65-9d93-d42b88061657)

This is how Faster-Whisper-XXL could be improved: When Faster-Whisper-XXL sees that a short subtitle like "Alps." or "reason." is going to be created after a long subtitle that does not end with ".", "!" or ?", it could intervene and prevent that from happening, by distributing the text of that long subtitle and the following short subtitle evenly between those two subtitles. In this way, the subtitle lengths will stay within the 'max characters' constraint, and no very short subtitles will be created. If Faster-Whisper-XXL could automatically generate something as in the second image, that would reduce the need for manual corrections afterwards. (This requires setting a minimum length for subtitles. Only if a subtitle would become shorter than this minimum, Faster-Whisper-XXL will be triggered to intervene. Alternatively, a minimum duration could be used instead of a minimum length in characters.)


**Two lines within a subtitle**

There can be an analogous situation within subtitles. The first of the two images below is an example of what was generated by Faster-Whisper-XXL, and the second is a manually created example of how this could be improved.

![Image](https://github.com/user-attachments/assets/b4295fb1-44d9-405d-8825-32be6ed579d8)

![Image](https://github.com/user-attachments/assets/4f2e994c-2775-470f-b5fb-da753828bbfd)

This is how Faster-Whisper-XXL could be improved: When Faster-Whisper-XXL sees that a short line like "them." is going to be created after a long line within a subtitle, it could intervene and prevent that from happening, by distributing the text of that long line and the following short line evenly within that subtitle. Such a balanced distribution within the lines of a subtitle, is generally preferred. This can easily be improved automatically afterwards, but it would be nice if Faster-Whisper-XXL could improve it itself.

-----------------------
(Note: With the earlier version r192.3.4 of Faster-Whisper-XXL and an earlier version of Subtitle Edit, it was possible to use the parameter "--output_format" from within Subtitle Edit, but this parameter can now only be used with a Command Prompt.)

**Comment by Purfview** [comment]
>Two consecutive subtitles...

But there is no bug, it output exactly what you commanded: `--max_line_width 37 --max_line_count 2 --sentence`

Use `--max_line_width 39 --max_line_count 1 --sentence` for the output to look like in your "what you want" example.

>Two lines within a subtitle...
>When Faster-Whisper-XXL sees that a short line like "them." is going to be created after a long line within a subtitle

No, it doesn't "see" that.
Faster-Whisper is not subtitle editor, if you want over-complicated editing things then ask at SE.

>(Note: With the earlier version r192.3.4 of Faster-Whisper-XXL and an earlier version of Subtitle Edit, it was possible to use the parameter "--output_format" from within Subtitle Edit, but this parameter can now only be used with a Command Prompt.)

Why you can't use it now?

**Comment by oep42** [comment]
Thank you for your responses and sorry for my slow response.

> But there is no bug, it output exactly what you commanded: `--max_line_width 37 --max_line_count 2 --sentence`

Of course, the result is in line with the used command, but that's not the point. The point is, that `--sentence` sometimes results in very short subtitles that have to be corrected manually afterwards. The point is about looking for ways to prevent that such manual correction would be needed afterwards (by either a change in the implementation of `--sentence`, or some additional parameter). The current logic/implementation of `--sentence`, will always result in some occurrences of bad (very short) subtitles, which is a pity.

> Use `--max_line_width 39 --max_line_count 1 --sentence` for the output to look like in your "what you want" example.

Sorry, this is silly, because I do want subtitles with one or two lines, so I do need to use `--max_line_count 2`. (The fact that the correction of two consecutive subtitles with one long and one very short line, results in two single-line subtitles, does not change my wish to have subtitles with one or two lines.)

> Why you can't use it in SE now?

I have no idea. I only reported an unexpected change that I encountered. It may be caused by some change in SE.

**Comment by Purfview** [comment]
>The current logic/implementation of --sentence, will always result in some occurrences of bad (very short) subtitles, which is a pity.

No, your max_line_width selection resulted in those short subtitles.

>Sorry, this is silly, because I do want subtitles with one or two lines, so I do need to use --max_line_count 2. 

I just wrote the command for "what you want" example. :)
If you don't like how subtitles are split here then you can use SE or any other tool to split them.
Or better, write that perfect subtitle splitting function yourself, I'll be happy to include it.

> I only reported an unexpected change that I encountered. It may be caused by some change in SE.

That doesn't tell me much, what error you get?

**Comment by oep42** [comment]
> That doesn't tell me much, what error you get?

When running Faster-Whisper-XXL r254.2 from within Subtitle Edit 4.0.10, it is possible to press the F2 key to see a window with output generated by Faster-Whisper-XXL. This works fine, when the parameter `--output_format all` or `-f all` is **not** included in "Extra parameters for Whisper command line". 

When running Faster-Whisper-XXL r254.2 from within Subtitle Edit after adding the `--output_format all` or `-f all` parameter to "Extra parameters for Whisper command line", an erroneous empty srt file is being created. When this happens, presumable an error message is temporarily being displayed in the "F2 window", but it is not possible to read it, because it is followed by a list of available parameters that immediately scrolls the error message out of sight. Scrolling up is not possible after the process has ended. So I have no idea what error occurs in this situation.

> > The current logic/implementation of --sentence, will always result in some occurrences of bad (very short) subtitles, which is a pity.

>No, your max_line_width selection resulted in those short subtitles.

In general, both `--sentence` and `--max_line_width` are needed to get those short subtitles. So it is true that without `--max_line_width`, there will be, in general, no such short subtitles. However, using `--sentence` without using `--max_line_width`, only makes sense for those who do not mind getting subtitles that are too long and have to be corrected afterwards.

I think that most people would prefer not to have such long subtitles. So when using `--sentence`, it does make sense to also use `--max_line_width` to avoid getting such long subtitles. If one uses `--sentence` with `--max_line_width` to set a maximum length, there will always be, in general, some sentences that are just a little longer than that maximum. And whenever such a sentence occurs when using `--sentence` and `--max_line_width`, a very short subtitle will always be created.

Note that the `--standard` parameter, which is supposed to be used by a lot of people as a standard, includes `--sentence` and `--max_line_width=42`. So using `--standard`, will always result in some occurrences of very short subtitles.

This is a rephrasing of my earlier statement:
The current logic/implementation of `--sentence` with `--max_line_width`, and the current logic/implementation of `--standard`, will always result in some occurrences of bad (very short) subtitles, which is a pity.

>If you don't like how subtitles are split here then you can use SE or any other tool to split them.

Not using `--max_line_width` will result in some subtitles that are too long and have to be split afterwards. When they are automatically split afterwards by a tool like SE, this may cause synchronization errors between spoken words and subtitles, because SE does not know the word-level timestamps of where it splits long lines. Faster-Whisper-XXL does know such timestamps, so it makes sense to let Faster-Whisper-XXL do such splitting, and not to leave that job to a tool that does not know such timestamps.

I think that Faster-Whisper-XXL is an excellent tool, except for what I consider a weakness when using `--sentence` together with `--max_line_width`.

>Or better, write that perfect subtitle splitting function yourself, I'll be happy to include it.

I don't know how realistic any of my suggestions are. I am not qualified to write a subtitle splitting function. What I can do, is give well-intentioned user feedback.
