### ISSUE TITLE
Runs on CPU instead of GPU

### ISSUE THREAD

**Issue by keith555** [Purfview/whisper-standalone-win#296]
I installed it automatically via subtitle-edit. I noticed that transcriptions were running on the CPU, not the GPU. I ran it from the command line with the same results. I've tried several different models. The output says that it is "running on CUDA" but the GPU usage remains minimal.  I tried explicitly setting cuda with `--device: cuda.` I also tried  `--device cuda:1` in case there was some problem with the integrated graphics card, but that failed with `invalid device ordinal`.  If I transcribe the same file using Whisper Desktop, it runs on the GPU. The GPU is an RTX 4080 running on a Gigabyte Auros 17H. 

![Snag_8cef0a](https://github.com/user-attachments/assets/f331d0d7-a15e-400c-9768-b2e6aca36fc3)

Using Whisper Desktop: 
![Snag_8d46af](https://github.com/user-attachments/assets/b80b32f8-d7bb-4836-bb4e-63581eaf06ba)

**Comment by Purfview** [comment]
Come transcription speed with `--device cpu`.

**Comment by keith555** [comment]
I don't understand your previous comment. It runs much faster on the GPU. When I transcribed the file with Whisper Desktop which uses the GPU, it finished in under 10 minutes. When I ran it using this version,  which runs on the CPU,  it took almost an hour.

**Comment by Purfview** [comment]
I meant compare transcription speed of Faster-Whisper with `--device cpu` vs `--device cuda`.
I'm not interested Whisper Desktop, whatever that is.

**Comment by keith555** [comment]
-cuda 110 seconds
-cpu killed it after 30 minutes and it had transcribed three lines
-Whisper Desktop  48 seconds

**Comment by Purfview** [comment]
> -cuda 110 seconds
> -cpu killed it after 30 minutes and it had transcribed three lines

Obviously it runs on GPU.
