### ISSUE TITLE
Recognize different speakers while transcribing audio

### ISSUE THREAD

**Issue by tubia** [Purfview/whisper-standalone-win#297]
Hi,
forgive me if this is a silly question, but there is a way to automatically mark in the transcribed text the different speakers from an audio file. Let's say I have 30 minutes of interview in which two people talk: would it be possible to have marked in the transcribed text when the speaker changes?

Something like:

```
Person1: Hello everyone!  
Person2: Hello!
```

Thanks!

**Comment by Krzysiu** [comment]
You are looking for diarization: https://github.com/MahmoudAshraf97/whisper-diarization

**Comment by tubia** [comment]
That's the word @Krzysiu thanks!

I recently discovered [m-bain/whisperX](https://github.com/m-bain/whisperX) which should include this apparently. I somehow took for granted whisper-standalone-win had already the ability to do it since it's use of VADs. Thanks @fideliochan for pointing out the proper issue.
