### ISSUE TITLE
AVX512 support

### ISSUE THREAD

**Issue by ivoryguard** [Purfview/whisper-standalone-win#299]
My CPU is a Xeon Gold that supports AVX512.
So, when I run the command line, it shows AVX512=true as follows:
However, the Selected ISA is always AVX2.

[2024-08-30 20:21:23.590] [ctranslate2] [thread 14304] [info] CPU: GenuineIntel (SSE4.1=true, AVX=true, AVX2=true, AVX512=true)
[2024-08-30 20:21:23.590] [ctranslate2] [thread 14304] [info]  - Selected ISA: AVX2
[2024-08-30 20:21:23.590] [ctranslate2] [thread 14304] [info]  - Use Intel MKL: true

I couldn't find any information related to activating AVX512 in the help text or other issue posting of both whisper-standalone-win and Faster Whisper.

Is there a way to utilize AVX512 in whisper-standalone-win?

**Comment by Purfview** [comment]
Do you run it on CPU, not CUDA?

**Comment by ivoryguard** [comment]
> Do you run it on CPU, not CUDA?
> 
> > I couldn't find any information related to activating AVX512
> 
> It should select the best backend and instruction set architecture for the platform, maybe AVX2 is best for your PC, dunno. I think a separate executable could be made with forced AVX512, are you willing to benchmark it?

If you provide an executable for AVX512, I will try to benchmark it.

**Comment by Purfview** [comment]
Here is AVX512 executable: https://we.tl/t-cqO9MQo1In

It's for "Faster-Whisper-XXL_r192.3.4_windows" release.
Place files at the "faster-whisper-xxl.exe", close all the programs, run "benchmark.bat", don't touch your PC till it finish.

Post the six "Transcription speed:" lines from the terminal.

**Comment by ivoryguard** [comment]
> Here is AVX512 executable: https://we.tl/t-cqO9MQo1In
> 
> It's for "Faster-Whisper-XXL_r192.3.4_windows" release. Place files at the "faster-whisper-xxl.exe", close all the programs, run "benchmark.bat", don't touch your PC till it finish. Shouldn't be long, there is six runs on cpu with the medium model on 10 mins audio.
> 
> Post the six "Transcription speed:" lines from the terminal, in the same order.

I executed on Intel Xeon Gold 5317 with 128GB RAM.

Transcription speed: 1.8 audio seconds/s
Transcription speed: 1.83 audio seconds/s
Transcription speed: 1.83 audio seconds/s
Transcription speed: 1.82 audio seconds/s
Transcription speed: 1.81 audio seconds/s
Transcription speed: 1.82 audio seconds/s

---------------

I performed my own testings for a Korean wav file which length is 05:16s with the following settings;
--compute_type int8 --beam_size 1 --threads 8 --language_detection_segments 3 --sentence

large-v2, avx2:                 1.75~2.18 audio seconds/s
large-v2, avx512:             2.18 audio seconds/s

large-v3-turbo, avx2:       3.63 audio seconds/s
large-v3-turbo, avx512:   4.76 audio seconds/s

---------------

Your benchmark uses medium model and it may make smaller difference between avx2 and avx512.
My benchmark uses non-english audio, large moodel with more theads and using avx512 make better results.
However, changing input audio file, model or parameters may cause different benchmark results.

I have read some post that the efficiency of avx512 on pytorch was not that good, so it did not utilize avx512 by default.
But, I don't know it is still true now.

Best regards.

**Comment by Purfview** [comment]
> I executed on Intel Xeon Gold 5317 

Shows no benefit with AVX512, closing the issue.

> I performed my own testings

Your tests are invalid.
Change only a model in the provided bat if you want to benchmark the other models and it to be valid.

>I have read some post that the efficiency of avx512 on pytorch

This has nothing to do with pytorch.
