### ISSUE TITLE
how can i run it using subtitle edit

### ISSUE THREAD

**Issue by eagleftw023** [Purfview/whisper-standalone-win#3]
how can i run it using subtitle edit?
and i have amd gpu can i use it ?

**Comment by Purfview** [comment]
> how can i run it using subtitle edit?

You need Subtitle Edit v3.6.13 or above, at the moment you need this [beta](https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip). It's portable, so don't overwrite your installed SE with it.
Then as usual, select preferred engine and Subtitle Edit will ask where .exe file is located. 

> and i have amd gpu can i use it ?

AMD GPUs doesn't have CUDA, so it would run only on CPU for you.
But faster-whisper is very fast, faster than CPP and Const-me.

**Comment by eagleftw023** [comment]
thanks alot
if i have file.bin how i can use it ,what should i type in cmd for the location of it?

**Comment by eagleftw023** [comment]
its worked now thanks but i got an error before its start to work 
[W:onnxruntime:Default, onnxruntime_pybind_state.cc:1671 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.

**Comment by eagleftw023** [comment]
thanks, sometimes its not transcribe the sound in specific regions i dont know if there is a default settings that i should change in cmd (i mean it transcribe part of the sound in this region and then skip)

![image](https://user-images.githubusercontent.com/130007636/234327037-5b57d375-c3e6-4850-b2cf-422591c080ff.png)

**Comment by Purfview** [comment]
Maybe it doesn't look like a speech at that place, try `--vad_filter False` and see if it doesn't skip this place.
If it doesn't skip with VAD off, is transcription correct in that place?

**Comment by eagleftw023** [comment]
its doesnt work now,it start to do loop of same words from the start to end

**Comment by Purfview** [comment]
Can you cut a snippet and share few minutes of that audio?
