### ISSUE TITLE
Accuracy improvements for timestamps

### ISSUE THREAD

**Issue by Tibetansand** [Purfview/whisper-standalone-win#30]
Will the latest commit of faster-whisper be updated to whisper-standalone-win?

The latest commits seem to have improved timestamp accuracy.

I wish you a happy day!

**Comment by Purfview** [comment]
Those commits are already included.

**Comment by Tibetansand** [comment]
Oh, I'm so sorry, I made a mistake.
I should be paying attention to this commit: https://github.com/guillaumekln/faster-whisper/pull/336

This issue I followed earlier (https://github.com/guillaumekln/faster-whisper/issues/330) was closed early, so I thought it was submitted.

May I ask if this commit is included in the published package? Thanks again.

**Comment by Purfview** [comment]
#336 was made just 8 hours ago so it's not included yet, it will be in the next release.

**Comment by Purfview** [comment]
I just released r134 with #336 included.

Quick test shows that #336 improves timestamps generally [some timestamps can be a bit worse].

**Comment by Tibetansand** [comment]
Thank you very much, I will test it in the video.
