### ISSUE TITLE
User defined name for output file

### ISSUE THREAD

**Issue by SanyaOs** [Purfview/whisper-standalone-win#303]
Please : add arguments for user defined name for output file. For Example in whisper.cpp
 -of FNAME, --output-file FNAME [       ] output name file (without file extension )

**Comment by SanyaOs** [comment]
Аnd if possible, add information about the specified language for the phrases in the JSON file

**Comment by Purfview** [comment]
What is the use cases for these?

**Comment by Purfview** [comment]
> Аnd if possible, add information about the specified language for the phrases in the JSON file

Implemented in v193.1

**Comment by Purfview** [comment]
>Please : add arguments for user defined name for output file. 

Why you need that? I don't see reason for this and that would add more spaghetties...
