### ISSUE TITLE
Whisper-turbo model support

### ISSUE THREAD

**Issue by codeMonkey-shin** [Purfview/whisper-standalone-win#305]
https://github.com/openai/whisper/pull/2361/files

Will this model be supported in the future?

**Comment by stevevaius2015** [comment]
Definitely we need this.

**Comment by andyhoeung** [comment]
I know large-v3 causes some weird stuff in transcription compared to large-v2, I wonder if they improved upon that while also making it faster.

**Comment by wangfeng35** [comment]
+1 need turbo

**Comment by AlanHuang99** [comment]
+1 need turbo

**Comment by andyhoeung** [comment]
I didn't have to replace any model. Just downloaded any faster-whisper large-v3 turbo variant, for example this one [https://huggingface.co/Infomaniak-AI/faster-whisper-large-v3-turbo](url), created a folder in _models called 'faster-whisper-large-v3-turbo', and used '--model=large-v3-turbo'.

**Comment by LoggeL** [comment]
> I didn't have to replace any model. Just downloaded any faster-whisper large-v3 turbo variant, for example this one https://huggingface.co/Infomaniak-AI/faster-whisper-large-v3-turbo, created a folder in _models called 'faster-whisper-large-v3-turbo', and used '--model=large-v3-turbo'.

Ah nice to know. I was checking on the old source code for the CLI and it didn't support other than the hard coded models at that time. 
https://github.com/Purfview/whisper-standalone-win/blob/e0472ddaa51ca0c5ff9775dcdc589e1ab878c28f/faster-whisper%20cli/__main__.py#L28

**Comment by ZeVince** [comment]
> > I didn't have to replace any model. Just downloaded any faster-whisper large-v3 turbo variant, for example this one https://huggingface.co/Infomaniak-AI/faster-whisper-large-v3-turbo, created a folder in _models called 'faster-whisper-large-v3-turbo', and used '--model=large-v3-turbo'.
> 
> --model=large-v3-turbo
> 
> ` Warning: 'large-v3' model may produce inferior results, try 'large-v2'!
> 
> Traceback (most recent call last): File "D:\whisper-fast_XXL__main__.py", line 1668, in File "D:\whisper-fast_XXL__main__.py", line 1595, in cli File "faster_whisper\transcribe.py", line 1456, in restore_speech_timestamps File "faster_whisper\transcribe.py", line 798, in generate_segments File "faster_whisper\transcribe.py", line 1109, in encode ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead [15868] Failed to execute script '**main**' due to unhandled exception! `
> 
> faster-whisper-xxl.exe

Same error here... any fix since then ?

**Comment by Purfview** [comment]
>Same error here... any fix since then ?

Not yet, but will be sooner than later, just that now some other things have priority.

**Comment by Purfview** [comment]
> Will this model be supported in the future?

It was always supported, as any other custom finetuned model.

Autodownload for it is added in v193.1

**Comment by nebehr** [comment]
Is turbo model supposed to do any translation at all? Produces untranslated German text with `--task translate`, whereas vanilla large-v3 appears to work fine.

**Comment by Purfview** [comment]
"Whisper turbo was fine-tuned for two more epochs over the same amount of multilingual transcription data used for training large-v3, i.e. excluding translation data, on which we don’t expect turbo to perform well."

**Comment by nebehr** [comment]
I see. From this description though I would expect it to be bad translation, not no translation at all. Anyway, this is beyond the scope of this project.
