### ISSUE TITLE
Different output of faster-whisper vs whisper-standalone

### ISSUE THREAD

**Issue by tjongsma** [Purfview/whisper-standalone-win#306]
Hi there,

I've been using whisper-standalone for a long time now, with really good results so thank you!

I've recently been trying to implement faster-whisper into a python application for streaming. I noticed that (especially for short clips) whisper-standalone has significantly better output than faster-whisper. I've tried to get the parameters as similarly as possible by mostly filling into default values of whisper-standalone into the faster-whisper command (where possible, _temperature_increment_on_fallback_ and _vad_window_size_samples_ don't have equivalents I think, but somehow whisper-standalone is still outperforming massively for this one somewhat noisy audio file of ~29s. Faster-whisper hallucinates a bunch, while whisper-standalone correctly transcribes the text. 

Here's my whisper-standalone command:
`Whisper\whisper-faster.exe "audio_files\temp_audio.wav" --task=transcribe --model=medium --output_dir="C:\Users\test\Desktop\Audio_transcription\audio_transcripts" --output_format=txt --beam_size=5 --temperature=0 --language=nl --word_timestamps=True --initial_prompt="" --compute_type float16`

And here's my code for faster-whisper in python:
```
from faster_whisper import WhisperModel
import os
import sys
base_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
#Loading model
model_size = "medium"
cache_dir=os.path.join(base_dir, "models", "cache")
model_dir = os.path.join(base_dir, "models", "cache", "models--Systran--faster-whisper-medium", "snapshots", "08e178d48790749d25932bbc082711ddcfdfbc4f")
model = WhisperModel(model_dir, device="cuda", compute_type="float16",download_root=cache_dir)

class WordWithTimestamp:
    def __init__(self, word, start, end):
        self.word = word
        self.start = start
        self.end = end

    def __str__(self):
        return self.word
segments, info = model.transcribe("temp_audio.wav", initial_prompt="",
                                        #max_new_tokens=224,
                                        beam_size=5,
                                        temperature=0,
                                        language="nl",
                                        length_penalty=1,
                                        condition_on_previous_text=True,
                                        prompt_reset_on_temperature=0.5,
                                       # temperature_increment_on_fallback=0.2,
                                        compression_ratio_threshold=2.4,
                                        log_prob_threshold=-1,
                                        no_speech_threshold=0.6,
                                        vad_filter=True,
                                        vad_parameters=dict(threshold=0.45,
                                                            min_speech_duration_ms=350,
                                                            min_silence_duration_ms=3000,
                                                            speech_pad_ms=900,
                                                           # vad_window_size_samples=1536
                                                            ),
                                        word_timestamps=True)
text = []
# Iterate over the segments and store words with timestamps
for segment in segments:
    for word in segment.words:
        text.append(WordWithTimestamp(word.word, word.start, word.end))
text_str = "".join(str(word) for word in text)
print(text_str)
```

Any insights would be appreciated! I'm basically just wondering how whisper-standalone is performing so much better while I understand it to be the same backend.

**Comment by tjongsma** [comment]
For some additional context: I don't think it's the VAD settings, setting vad_filter to False for both yields the exact same result.

**Comment by tjongsma** [comment]
Fixed, issue was an experimental faster-whisper branch 🤦‍♂️ (https://github.com/SYSTRAN/faster-whisper/issues/1027).

**Comment by Purfview** [comment]
There are more differences in defaults than you have posted, for example custom prompt, and there are some small differences in code, don't expect the output to be same.

I don't remember now exactly, but I think "temperature=0" doesn't behave same here vs python, here it behaves like in vanilla whisper's cli, for equivalent result here you should set `--temperature_increment_on_fallback None` or `-fallback None`.

**Comment by tjongsma** [comment]
Thanks a lot for still replying @Purfview! If possible could you tell me a bit more about how you got things to work so well for subtitles? I for example notice that your whisper-standalone output is still a lot better than just default whisper-large-v2 with regards to punctuation for segments, and it also seems to produce new segments for new speakers a lot more consistently. Is this just due to the different in default parameter settings combined with what you just mentioned or is there something else going on?

**Comment by Purfview** [comment]
Probably various things sums up. If you want new sentences to start as the new subtitle then use `--sentence` or `--standard`

**Comment by tjongsma** [comment]
Apologies, what do you mean by that exactly? I can't find those options in either whisper-standalone or whisper parameters.

What I was referring to is that when I use whisper-standalone with the default settings the segmentation seems to much better suited to subtitles than when I just use base large-v2 in faster-whisper in python with the default settings

**Comment by Purfview** [comment]
Those parameters are for Standalone Faster-Whisper. Use these commands to see parameters:

`whisper-faster.exe --help`
`faster-whisper-xxl.exe --help`
