### ISSUE TITLE
XXL_r192.3.1_linux hangs with --ff_mdx_kim2 in Colab

### ISSUE THREAD

**Issue by CevreMuhendisi** [Purfview/whisper-standalone-win#319]
I'm using Faster-Whisper-XXL_r192.3.1_linux version, but when I add this command, it hangs like this. When I remove the command, it works normally. Can you help me?

Standalone Faster-Whisper-XXL r192.3.1 running on: CUDA

Audio filtering is in progress...
Estimating duration from bitrate, this may be inaccurate

100% 506/506 [10:42<00:00,  3.51s/it]^C

**Comment by Purfview** [comment]
What verbose shows? Do you run it in Colab?

**Comment by Purfview** [comment]
What `--verbose = true` shows?

**Comment by Purfview** [comment]
Post your full command.

**Comment by Purfview** [comment]
Try these:

`whisper-faster-xxl audio.ac3 --verbose true --ff_mdx_kim2 --model tiny --vad_alt_method pyannote_v3`

`whisper-faster-xxl audio.ac3 --verbose true --ff_mdx_kim2 --model tiny`

`whisper-faster-xxl audio.ac3 --verbose true --ff_mdx_kim2 --model tiny --device cpu`

**Comment by Purfview** [comment]
Probably some incompatibly with Colab's Linux version. Could you check and post the exact Linux version it's using?

Test this: `whisper-faster-xxl audio.ac3 --verbose true --ff_rnndn_xiph --ff_dump --model tiny`

**Comment by Purfview** [comment]
>`Model not found at: /content/Faster-Whisper-XXL/Whisper-Faster-XXL/_models/faster-whisper-tiny
Attempting to download:

How the tiny model is not found if you tested those previous 3 commands?

**Comment by Purfview** [comment]
It shouldn't be missing if it downloaded it once, no?

**Comment by Purfview** [comment]
At the moment I can't help you further, from your tests I got idea what could be wrong but I need to check stuff in Linux, that may not happen soon.

You could post what problems you had with Colab and how you solved them, or post links of the guides you followed:  https://github.com/Purfview/whisper-standalone-win/discussions/318

**Comment by Purfview** [comment]
Thanks for the code, I'll try to test the next version there too.

**Comment by Purfview** [comment]
>@Purfview can you check ur mail when u free

Ah, that one I don't get notifications from... Will do.

**Comment by Purfview** [comment]
Tested, it runs without problems on PC with Ubuntu 22.04.5, probably some quirk in Colab.
I've no idea what can be as it doesn't show any error, btw, that last line with the progress shouldn't look like that.

**Comment by Purfview** [comment]
Just tested it my self, there is no problem you just had to wait a bit longer I guess.

**Comment by xueli12** [comment]
I also encountered the same issue. When executing --ff_mdx_kim2 on Colab, it gets stuck indefinitely. Is it possible to add alternative solutions for vocal separation? The software version I am using is Faster-Whisper-XXL_r245.3.

**Comment by Purfview** [comment]
>I also encountered the same issue. When executing --ff_mdx_kim2 on Colab, it gets stuck indefinitely.

Yes, recently I encountered it too, it hits the free RAM limit and Colab crash silently, happens with audios longer than 01:39:00, so ATM solution would be to split longer audios than that.

>Is it possible to add alternative solutions for vocal separation?

Hypothetically, possible. You can post there about this request: https://github.com/Purfview/whisper-standalone-win/discussions/389

>The software version I am using is Faster-Whisper-XXL_r245.3.

Ah that, it's not some new version I was testing something with libs and forgot to delete it.
