### ISSUE TITLE
r134.5 writes output to wrong dir

### ISSUE THREAD

**Issue by KayLeung** [Purfview/whisper-standalone-win#32]
r126: written into start dir (video dir)
r134.5: always the whisper-faster.exe folder dir

**Comment by Purfview** [comment]
Actually, r126 behavior was "wrong", I always meant the default output dir to be in the .exe dir.

If you want previous behavior then use `-o=.` parameter, this will set the output to the current dir.

Btw, `batch_recursive=true` parameter sets the output strictly to the same dir where media file is.
