### ISSUE TITLE
Hallucination - "Υπότιτλοι AUTHORWAVE"

### ISSUE THREAD

**Issue by afghklhgfjdsg** [Purfview/whisper-standalone-win#321]
The Greek audio-to-text library will randomly write "Υπότιτλοι AUTHORWAVE" and not actually translate the audio on that line/time. I think this is purposeful and is an issue instead of bug? 
Software I use with this awesome software: Subtitle Edit.
![image](https://github.com/user-attachments/assets/8b3d8928-fbc2-497d-ba37-ea979567e712)
![image](https://github.com/user-attachments/assets/40c718ab-1d9a-43d9-b2cd-eaec953c7220)
When not randomly writing "Υπότιτλοι AUTHORWAVE" it works well.

**Comment by Purfview** [comment]
> translate

What do you mean? Translate is not selected in your screenshot.

**Comment by Purfview** [comment]
> "Υπότιτλοι AUTHORWAVE"

It's just a hallucination, not a bug per se.

These options can help you with hallucinations:
`--ff_mdx_kim2` `--vad_alt_method pyannote_v3` `-hst 2`

**Comment by afghklhgfjdsg** [comment]
I'll try this. Thanks! This software is awesome!

I was trying to write "translate" = "generate-audio-to-text" or something.

Extra info. if needed in future. This has only happened while generating Greek text, and happens on the same line/timecode in a given file (I ran a file twice and same timecodes). My attached photos were from a failed run on my part, but shows the random text "Υπότιτλοι AUTHORWAVE" that is generated.

**Comment by Purfview** [comment]
>This software is awesome!

Thanks, and for donation too.

>I was trying to write "translate" = "generate-audio-to-text" or something.

That's "Translate to English" option box in your screenshot, the model is trained to translated only to English.
Where you selected "Greek" there actually goes a language of audio.
You can do your way to get translations to other languages, but this is unsupported hack and may lead to a weird output.

**Comment by konsnos** [comment]
To add to this issue I'm running whisper through the CLI `python -m whisper '.\audio.mp3' --language Greek` , and I sometimes get the same.

```
[00:00.000 --> 00:29.980]  Υπότιτλοι AUTHORWAVE
[00:30.000 --> 00:59.980]  Υπότιτλοι AUTHORWAVE
[01:00.000 --> 01:29.980]  Υπότιτλοι AUTHORWAVE
[01:30.000 --> 01:59.980]  Υπότιτλοι AUTHORWAVE
```

**Comment by afghklhgfjdsg** [comment]
It's the data set that causes this. I don't know if there's another Greek
data set out there. I would recommend finding a better one as this one is
too limited.
At first I thought it was some type of time-based response, but I'm pretty
sure it just doesn't know enough context. So just defaults to outputting
this text.
