### ISSUE TITLE
How can i use Custom models?

### ISSUE THREAD

**Issue by Nisekoi-1** [Purfview/whisper-standalone-win#330]
https://huggingface.co/arc-r/faster-whisper-large-v2-mix-jp

`faster-whisper-xxl.exe --model large-v2-mix-jp --model_dir "C:\Users\VICTUS\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2-mix-jp" --language ja --task transcribe "D:\Shows\output.mp3"`

i got this in return

`Unknown model not found at: C:\Users\VICTUS\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2-mix-jp\faster-whisper-large-v2-mix-jp

Try these known models:
['tiny', 'tiny.en', 'base', 'base.en', 'small', 'small.en', 'medium', 'medium.en', 'large-v1', 'large-v2', 'large-v3', 'large', 'distil-large-v2', 'distil-medium.en', 'distil-small.en', 'distil-large-v3']`

any way to use custom models?

**Comment by Purfview** [comment]
No need to use `--model_dir` in your case, it's not for any particular model, it just just for the all models folder aka `_models` by default.

Use this command:
`faster-whisper-xxl.exe "D:\Shows\output.mp3" -m large-v2-mix-jp -l ja`

If still you get same error then post a screenshot showing content of the model's folder and with disk path visible.
