### ISSUE TITLE
Running on Cuda instead of CPU?

### ISSUE THREAD

**Issue by koebbe14** [Purfview/whisper-standalone-win#335]
I can't seem to get diarization working.

command:  >start faster-whisper-xxl.exe "Andrea Sykes Interview Audio.m4a" --diarize=pyannote_v3.0

error:  Standalone Faster-Whisper-XXL r194.1 running on: CUDA

Speaker Diarization using Pyannote v3.0: WeSpeaker voxceleb_resnet34_LM embedding - onnx
2024-11-21 12:10:15.4773292 [W:onnxruntime:, transformer_memcpy.cc:74 onnxruntime::MemcpyTransformer::ApplyImpl] 2 Memcpy nodes are added to the graph torch-jit-export for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.

I've tried using --diarize=reverb_v2 and it just holds up on the legal notice.  Also, what command should I use for CPU rather than CUDA?

What am I doing wrong??

**Comment by Purfview** [comment]
Do you have Zluda installed or some other CUDA emulator if there is?

What `--verbose true` shows? -> `faster-whisper-xxl.exe "Andrea Sykes Interview Audio.m4a" --verbose true`

**Comment by koebbe14** [comment]
I do not have any Zluda or any other cuda emulator installed.  It seems to be functioning and will diarize, but I’m not sure why it’s using cuda???  And I’m not sure what you mean about your verbose question.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Purfview** [comment]
What OS you run and what is your CPU and GPU?

>  And I’m not sure what you mean about your verbose question.

I meant execute that command:

`faster-whisper-xxl.exe "Andrea Sykes Interview Audio.m4a" --verbose true`

And post a screenshot or copy/paste of what it shows.

**Comment by koebbe14** [comment]
Well disregard.  Apparently my work laptop does have an Geoforce RTX 3050!  🤦‍♂️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
