### ISSUE TITLE
large-v3 issues

### ISSUE THREAD

**Issue by darnn** [Purfview/whisper-standalone-win#338]
Hi. I was trying out Faster-Whisper-XXL again, and performed a transcription using both large-v2 and large-v3. The results with large-v3 were, indeed, much worse than with large-v2, but also, notably, much worse than the results I get with large-v3 using, e.g., WhisperX on Kaggle. To make sure it isn't just my specific setup, I've also compared them to the results I get from Whisper.cpp CuBLAS with v3, and they're still much worse. Is there anything that could be done about this? Or does large-v3 just not work as well converted to ggml?

Also, if you'd like to try it yourself using Kaggle, just create an account, create a new notebook, upload your file and then use the following commands:
!pip install git+https://github.com/m-bain/whisperx.git --root-user-action=ignore
!whisperx --language en --model large --compute_type float32 --batch_size 3 --output_format srt --output_dir 1 "/kaggle/input/folder/file.aac"

The thing I was transcribing was in Hebrew, but I assume the difference is evident in English as well.

**Comment by Purfview** [comment]
You just observe randomness you don't need to worry about, especially on very inaccurate languages like Hebrew.

How many hours did you evaluated in you comparisons? I guess you just looked at one or two sentences, when you'll evaluate hours then you'll see that in general there is nor much difference. 

>I assume the difference is evident in English as well.

On clear English you can use base model and get almost same results as from large.
