### ISSUE TITLE
Subtitle Edit 4.0.9 and Purfview's Faster Whisper XXL Still Broken Merging Subtitle Lines

### ISSUE THREAD

**Issue by TranslateFuture** [Purfview/whisper-standalone-win#339]
Hello, thank you for the newest updates.

With the newest Subtitle Edit 4.0.9 beta update (and every release after the final version of Subtitle Edit 4.0.3, or after December 23, 2023) there's still the broken/merged/random capitalization/no commas or periods/etc. issues that I described here: https://github.com/SubtitleEdit/subtitleedit/issues/8634 and https://github.com/SubtitleEdit/subtitleedit/issues/8209

![github translate new korean chinese spanish shuhua workdol broken subtitles comparison 1080p](https://github.com/user-attachments/assets/37f6d078-a9fb-4db4-8810-1d603d2abd24)

I've also posted it again on the Subtitle Edit page since the default --standard option (can't be toggled on or off right now, like the settings are not saved) in Subtitle Edit is what's creating the issues: https://github.com/SubtitleEdit/subtitleedit/issues/9035

Once more, thank you so much Purfview, really appreciate all the work and help you've done. I apologize again if I was unclear or rambling, the specific examples (with videos and images) are in the previous comments.

**Comment by mjamil85** [comment]
Try to run directly from faster-whisper-xxl.exe using command. Purfview already released a new version with .bat included (drop files in bat) & check if the result is the same as with Subtitle Edit.

**Comment by Purfview** [comment]
Those SE screenshots doesn't tell me anything.

1) Make sure you use the latest version at the moment: `r194.2` +  [r194.2_to_r194.2.1_patch](https://fromsmash.com/HDB7pHi_qG-bt) 
2) Share `json` file with the problem, you can get it with `-f srt json` command.
3) Then write what exact problem you have.

**Comment by Purfview** [comment]
Open a new issue when you can provide all those three things described in the above post.

**Comment by TranslateFuture** [comment]
Thank you as always for the quick reply, Purfview, I have here one new example, this is with the standalone Faster-Whisper-XXL r194.2 (before today's update with r194.4), not using Subtitle Edit at all. The .json file is included now. 

The commands were the default (I only changed it to the large-v2 and to Translate to English), or this from the .bat file: faster-whisper-xxl.exe %file_list% -pp -o source --batch_recursive --check_files --standard -f json srt -m large-v2 --task translate

This is a 1-hour video from the DdeunDdeun channel on Youtube, I've also included the official English and Korean subtitles as comparison. Pinggyego/Just An Excuse Episode 58: https://www.youtube.com/watch?v=B4bOGORy58E

[github purfview faster whisper xxl broken merged capitalizations translations for korean chinese spanish etc.zip](https://github.com/user-attachments/files/17928375/github.purfview.faster.whisper.xxl.broken.merged.capitalizations.translations.for.korean.chinese.spanish.etc.zip)

The problem (with Korean, Spanish, probably a lot of the other languages as well, especially when the video or audio is over 1 hour long) seems to be that the lines are merged because of the --standard command or something along those lines, and so the final output with the .srt file in English has the random capitalized letters, missing periods and commas, etc.

I apologize again if it's not reproducible, I'm using the latest version (not the r194.4 that was uploaded a few hours ago) of Faster-Whisper-XXL, and even back with regular Faster-Whisper back then, it definitely looks like due to the introduction of the --standard command being default or something like that.

I can't really describe it further in detail as I'm still pretty new to all of this, but it seems to be related to the updates around the time period between Subtitle Edit 4.0.3 and Subtitle Edit 4.0.4.

The previous default (for Subtitle Edit) didn't have as many breaks or "<br />" per each dialogue/line, but since from that time to today, it does a lot of the breaking of the lines and it looks it's doing the breaks for like every other word or so.

Thank you again for the fast response. The previous examples from several months ago also exhibit the same behaviors (they were done through Subtitle Edit instead of standalone though).

![github translate new korean chinese spanish shuhua workdol broken subtitles comparison 1080p](https://github.com/user-attachments/assets/37f6d078-a9fb-4db4-8810-1d603d2abd24)

[github subtitle edit broken translation for korean chinese etc.zip](https://github.com/SubtitleEdit/subtitleedit/files/15019293/github.subtitle.edit.broken.translation.for.korean.chinese.etc.zip)

![github translate broken korean drama](https://github.com/SubtitleEdit/subtitleedit/assets/167344091/a51092b3-9c65-4485-9130-4da1e3a5591c)

![github translate new korean chinese spanish shuhua workdol broken subtitles comparison 1080p](https://github.com/user-attachments/assets/37f6d078-a9fb-4db4-8810-1d603d2abd24)
