### ISSUE TITLE
Best option for MacOS

### ISSUE THREAD

**Issue by hlevring** [Purfview/whisper-standalone-win#340]
I presume that the older version [Faster-Whisper r192.3](https://github.com/Purfview/whisper-standalone-win/releases/tag/faster-whisper) is not compatible with the new Turbo model?

I am looking for a temporary easy CLI solution for Mac similar to yours. I could use whispercpp for both Mac and Windows , but I am more happy with the accuracy of word level timestamps that I am getting from your solution on Windows.

**Comment by Purfview** [comment]
> I presume that the older version [Faster-Whisper r192.3](https://github.com/Purfview/whisper-standalone-win/releases/tag/faster-whisper) is not compatible with the new Turbo model?

It should work like any other ct2 model, just that there is no auto-download for the turbo model, so you need to download it manually -> https://huggingface.co/Purfview/faster-whisper-large-v3-turbo .
