### ISSUE TITLE
r194.3 doesn't work

### ISSUE THREAD

**Issue by Ditchbuster** [Purfview/whisper-standalone-win#341]
Hello, I have just tried using whisper-standalone after testing the vanilla whisper. I am trying with mostly defaults to test that I have everything setup correctly. I am getting the below error. I am a little confused as I don't have a "D:" drive. I saw another issue report something similar and that it was due to an output file being open. I have deleted any transcribed files related to the audio file I am testing with. As you can see, I do get a single line of output before it crashes, so I thought it might be related to output.
I am at a bit of a loss, but am very new to using whisper/fast-whisper Thanks!

```
PS C:\Users\*****\Documents\Programming\WhisperDnD> .\Faster-Whisper-XXL\faster-whisper-xxl.exe ".\3-*****_0.flac" -l en

Standalone Faster-Whisper-XXL r194.3 running on: CUDA


Starting transcription on: .\3-******_0.flac

[00:03.020 --> 00:09.750]  Oooooh. See how this goes, should be interesting.
Traceback (most recent call last):
  File "D:\whisper-fast-XXL\__main__.py", line 1997, in <module>
  File "D:\whisper-fast-XXL\__main__.py", line 1868, in cli
  File "dataclasses.py", line 1237, in asdict
TypeError: asdict() should be called on dataclass instances
[PYI-4756:ERROR] Failed to execute script '__main__' due to unhandled exception!```

**Comment by Purfview** [comment]
Oh, I was testing some stuff and forgot to remove that code, wait a bit for a new proper release.

**Comment by Ditchbuster** [comment]
oh thanks! i didnt think about trying an older version..

**Comment by Purfview** [comment]
Should be fixed in r194.4
