### ISSUE TITLE
More memory usage for r134.6?

### ISSUE THREAD

**Issue by oevesque** [Purfview/whisper-standalone-win#35]
I was using version 126 without any problems, and have now switched to version 136.
On videos that were correctly processed previously, I now have errors. The last message mentions a memory problem. 
Does the latest revision use more memory?
Every video file have this same error at some point of the transcript:

```
Processing segment at 00:27.680
Compression ratio threshold is not met with temperature 0.0 (4.674074 > 2.400000)
Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 615, in <module>
  File "D:\whisper-fast\__main__.py", line 565, in cli
  File "faster_whisper\transcribe.py", line 869, in restore_speech_timestamps
  File "faster_whisper\transcribe.py", line 401, in generate_segments
  File "faster_whisper\transcribe.py", line 603, in generate_with_fallback
RuntimeError: CUDA failed with error out of memory
[21292] Failed to execute script '__main__' due to unhandled exception!
```
I'm going back to r126 for now.

**Comment by Purfview** [comment]
That's because defaults changed, r126 has bug with compute_type default when on cuda.
By error it is set to int8 there, which uses less memory but is slower, I think.

**Comment by oevesque** [comment]
Ok thanks, forcing "--compute_type int8" solved the issue. (I'm using an old geforce 1070)

**Comment by Purfview** [comment]
What model did you use and what is VRAM size of your GPU?

**Comment by oevesque** [comment]
--model large-v2 
8Go Vram

**Comment by Purfview** [comment]
I think 8Gb should be enough for float32, looks like a spike in memory use happens on that temperature fallback:
>File "faster_whisper\transcribe.py", line 603, in generate_with_fallback

Is this error always producible on that file?
Post other settings if you changed from defaults.
Could you check if with `--compute_type=float32 --best_of=1` it's gone?

**Comment by oevesque** [comment]
Yes, the problem, for all files, are in the "temperature fallback".
It works fine when using `--compute_type=float32 --best_of=1`
But I'm a lot confused with this parameters.
In a short way, is there an ideal parameter for accuracy in speech detection and timestamp ?

**Comment by oevesque** [comment]
I was using this script (and using Directory Opus to send all selected files to this .bat)
```
@echo off

REM ATTENTION CE SCRIP NE FONCTIONNE PAS SI LE PATH DU FICHIER à SOUS TITRER CONTIENT un ESPACE
REM  OU SI LE NOM DU FICHIER CONTIENT UN &

REM Initialisez une variable pour stocker les arguments concaténés
set "concatenatedArgs="
set file_path=%~dp1

REM Boucle à travers tous les arguments en ligne de commande
:loop
if "%~1"=="" goto done

REM Ajouter l'argument actuel à une variable temporaire entre guillemets
set "currentArg="%~1""

echo %currentArg%

REM Concaténez chaque argument à la variable "concatenatedArgs"
set "concatenatedArgs=%concatenatedArgs% %currentArg%"

shift
goto loop

:done
REM Affichez la variable contenant les arguments concaténés
echo Arguments concaténés : %concatenatedArgs%
D:\Application\Python\Subtitle\whisper-faster.exe --model large-v2 --language en --output_format srt --model_dir c:\temp  --compute_type int8 --output_dir %file_path%  %concatenatedArgs%

REM Fin de votre script batch

```

**Comment by Purfview** [comment]
> I was using this script

You don't need to use it, you can do same out of the box. Few usage examples:

`whisper-faster.exe "D:\Clips\*.mkv" --language=en --model=medium --batch_recursive=True`

`whisper-faster.exe "D:\Audio" --language=en --model=medium --batch_recursive=True`

`whisper-faster.exe "D:\Band\Album.m3u" --language=en --model=medium --vad_filter=False`

> In a short way, is there an ideal parameter for accuracy in speech detection and timestamp?

Imo, defaults are generally good for that, there are no ideal parameters for everything, if there were then all those parameters wouldn't be needed. :)
Thanks for tests, maybe I'll adjust some defaults in the next release.

Could you do benchmark from me with `--compute_type=float32 --best_of=1` and `--compute_type=int8 --best_of=1` where test runs at least for few minutes?
I need "Transcription speed" lines from tests.

**Comment by oevesque** [comment]
Videofile duration: 39mn57s
int8: Transcription speed: 6.29 audio seconds/s in 458s
float32 : Transcription speed: 6.56 audio seconds/s in 425s
but the flag best_of=1 give poorer recognition result. Lots of hallucination.

**Comment by Purfview** [comment]
> but the flag best_of=1 give poorer recognition result. Lots of hallucination.

Can you share audio (remuxed, not transcoded) and the examples of those hallucinations?

**Comment by oevesque** [comment]
the test file is an english adult movie. So maybe not...

**Comment by Purfview** [comment]
Are you sure that best_of=1 affects transcription?
Maybe you are mixing-up int8 vs float32 results. I never noticed that parameter making a single difference,

**Comment by oevesque** [comment]
Here are the result of different Best_of and Compute_Type parameter and the file size.
As you can see, some combination give more text for the same file.

Testfile.1080p.MP4-WRB.int8.bestof1.result.srt			21,2 Ko
Testfile.1080p.MP4-WRB.int8.bestof5.result.srt			41,1 Ko
Testfile.1080p.MP4-WRB.int8.bestof7.result.srt			36,8 Ko
Testfile.1080p.MP4-WRB.float32.bestof1.result.srt			31,3 Ko
Testfile.1080p.MP4-WRB.float32.bestof2.result.srt			40,3 Ko

I can't do more than bestof=2 with float32 without error.

But you should not take so much time of investigation with this particular file. Evenmore, adult films contain groans and grunts that fool both AIs and the code that seek to detect sections containing voice. (I guess the quick repeating non word voice give false result for the compression ratio threshold too)

**Comment by Purfview** [comment]
I downloaded some adult clip, and yeah now I see that best_of has effect.

But opposite effect in results from yours:

float32 + best_of1: 7.6 Kb
float32 + best_of5: 5.5 Kb
float32 + best_of5 + beam_size5: 1.9Kb

By quick looks all versions have worse/better lines, not clear which subs are better. Size difference is mostly because of those pointless ah/oh lines.
