### ISSUE TITLE
GPU is not used at all...

### ISSUE THREAD

**Issue by 0wwafa** [Purfview/whisper-standalone-win#354]
I understand that I have a sh*tty GPU (GTX970M) but https://github.com/Purfview/whisper-standalone-win/releases/download/Faster-Whisper-XXL/Faster-Whisper-XXL_r194.5_windows.7z is not using it at all.
:(

**Comment by Purfview** [comment]
Post what it shows with `--device cuda --verbose true`

**Comment by Purfview** [comment]
Looks like PEBKAC.
