### ISSUE TITLE
Please add these models

### ISSUE THREAD

**Issue by 0wwafa** [Purfview/whisper-standalone-win#357]
https://huggingface.co/Sandiago21/whisper-large-v2-italian
https://huggingface.co/whispy/whisper_italian
https://huggingface.co/speechbrain/asr-whisper-medium-commonvoice-it
https://huggingface.co/ALM/whisper-it-small

**Comment by Purfview** [comment]
Add where and why? For what do you use whisper?
Btw, these models are not in ctranslate2/faster-whisper format.
