### ISSUE TITLE
Is the non XXL Faster-Whisper obsolete?

### ISSUE THREAD

**Issue by niksedk** [Purfview/whisper-standalone-win#358]
It looks like the non XXL version is not updated anymore, so we should use the XXL version, correct?

(I'm working on SE 4.0.9 and thinking about removing the old "Purfview's Faster Whisper" in SE)

**Comment by Purfview** [comment]
Yeah, I'll not update it anymore.

Btw, would you like self-extracting exe of XXL so it could be autodownloaded by SE?

**Comment by AuroraMartell** [comment]
XXL gives a no text found error on Win 11 (SE 4.0.8). How to fix?

If the non XXL version is deprecated, this hurts my workflow since I use SE with Faster Whisper to transcribe episodes for a Polish drama.

**Comment by Purfview** [comment]
>XXL gives a no text found error on Win 11 (SE 4.0.8). How to fix?

Run it directly. And post what error is there.

**Comment by AuroraMartell** [comment]
> Run it directly. And post what error is there.

What do you mean run directly? I'm a command-line noob.

**Comment by AuroraMartell** [comment]
If it helps, here's the log from SE:

```
-----------------------------------------------------------------------------
Date: 12/08/2024 13:26:43
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: CUDA check reports: CUDA device: 0

-----------------------------------------------------------------------------
Date: 12/08/2024 14:17:58
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\1504ebad-4b62-45c1-ac6a-fc77f626b188.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:18:00
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\1504ebad-4b62-45c1-ac6a-fc77f626b188.wav"

LoadLibrary: Não foi possível encontrar o módulo especificado.

Error loading Python DLL 'C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_xxl_data\python38.dll'.
Calling whisper Purfview's Faster-Whisper-XXL done in 00:00:00.9177327
Loading result from STDOUT


-----------------------------------------------------------------------------
Date: 12/08/2024 14:21:56
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Cpp\main.exe --language pl --model "C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Cpp\Models\medium.bin" --output-srt --print-progress  "C:\Users\PC\AppData\Local\Temp\40e35656-fe78-43fd-99ec-e0c68d2fcd18.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:23:35
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: CUDA check reports: CUDA device: 0

-----------------------------------------------------------------------------
Date: 12/08/2024 14:28:03
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" -- task (transcribe) "C:\Users\PC\AppData\Local\Temp\952146ea-1a52-4afb-8585-0613c4bb0ef5.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:31:15
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium"  "C:\Users\PC\AppData\Local\Temp\2049e1cb-3cbc-4c1a-81e4-95f9005f8314.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:31:49
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\93542611-74bd-4733-bcb3-d82289ef053d.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:31:50
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\93542611-74bd-4733-bcb3-d82289ef053d.wav"

Error loading Python DLL 'C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_xxl_data\python38.dll'.

LoadLibrary: Não foi possível encontrar o módulo especificado.
Calling whisper Purfview's Faster-Whisper-XXL done in 00:00:00.7515174
Loading result from STDOUT


-----------------------------------------------------------------------------
Date: 12/08/2024 14:32:40
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: CUDA check reports: CUDA device: 0

-----------------------------------------------------------------------------
Date: 12/08/2024 14:32:41
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\1e7d0102-31c6-4482-b47b-3fe8cd7fd31c.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:44:50
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\ede9b2c8-9f9b-4c69-89e0-bb85cea3cf2b.wav"

-----------------------------------------------------------------------------
Date: 12/08/2024 14:44:52
SE: 4.0.8.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper-XXL) with : C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\faster-whisper-xxl.exe --language pl --model "medium" --standard "C:\Users\PC\AppData\Local\Temp\ede9b2c8-9f9b-4c69-89e0-bb85cea3cf2b.wav"

LoadLibrary: Não foi possível encontrar o módulo especificado.

Error loading Python DLL 'C:\Users\PC\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\_xxl_data\python38.dll'.
Calling whisper Purfview's Faster-Whisper-XXL done in 00:00:00.9890805
Loading result from STDOUT
```

**Comment by Purfview** [comment]
Then I can't help you.

Read there: https://github.com/Purfview/whisper-standalone-win/discussions/337
Or there: https://github.com/Purfview/whisper-standalone-win/discussions/315

**Comment by AuroraMartell** [comment]
> > I'm a command-line noob.
> 
> Then I can't help you.
> 
> Read there: #337 Or there: #315

Do I need to download python? I noticed a python38.dll error in the log...

**Comment by Purfview** [comment]
>Do I need to download python? I noticed a python38.dll error in the log...

No. That looks like old version. Current is r194.5, try that.

**Comment by AuroraMartell** [comment]
> No. That looks like old version. Current is r194.5, try that.

Will test and report back.

**Comment by AuroraMartell** [comment]
Same error.

**Comment by Purfview** [comment]
>Same error.

Not possible. You must be doing something wrong.
Run it directly, not from SE!

**Comment by niksedk** [comment]
>Btw, would you like self-extracting exe of XXL so it could be autodownloaded and extracted by SE

I will give unpacking a try... I will get back soon.

**Comment by AuroraMartell** [comment]
> Run it directly, not from SE!

Run the executable directly?

**Comment by AuroraMartell** [comment]
> > Run the executable directly?
> 
> Yes.

Doesn't work either. The app doesn't open.

**Comment by Purfview** [comment]
>Doesn't work either. The app doesn't open.

That means you don't know what you are doing.
Read the links.

**Comment by AuroraMartell** [comment]
> > Doesn't work either. The app doesn't open.
> 
> That means you don't know what you are doing. Read the links.

#337 has a one click tool. How do I use that with the app?

**Comment by Purfview** [comment]
>https://github.com/Purfview/whisper-standalone-win/discussions/337 has a one click tool. How do I use that with the app?

That's literally written there.

**Comment by AuroraMartell** [comment]
> > #337 has a one click tool. How do I use that with the app?
> 
> That's literally written there.

Tested. It doesn't work. 

I think I'll stick with the non XXL Faster Whisper in SE 4.0.8 until the no text found error is fixed.

**Comment by Purfview** [comment]
>Tested. It doesn't work.

That doesn't tell me anything, post a screenshot.

**Comment by AuroraMartell** [comment]
> That doesn't tell me anything, post a screenshot.

I do as instructed in #337 but nothing happens, just a blank CMD screen.

**Comment by Purfview** [comment]
post a screenshot of a blank CMD screen.

**Comment by AuroraMartell** [comment]
> post a screenshot of "a blank CMD screen."

Looks like this, but in a green font and black screen.


```

     8""""                                    8   8  8                                       8   8 8   8 8
     8     eeeee eeeee eeeee eeee eeeee       8   8  8 e   e e  eeeee eeeee eeee eeeee        8 8   8 8  8
     8eeee 8   8 8   "   8   8    8   8       8e  8  8 8   8 8  8   " 8   8 8    8   8        eee   eee  8e
     88    8eee8 8eeee   8e  8eee 8eee8e eeee 88  8  8 8eee8 8e 8eeee 8eee8 8eee 8eee8e eeee 88  8 88  8 88
     88    88  8    88   88  88   88   8      88  8  8 88  8 88    88 88    88   88   8      88  8 88  8 88
     88    88  8 8ee88   88  88ee 88   8      88ee8ee8 88  8 88 8ee88 88    88ee 88   8      88  8 88  8 88eee


Nothing to do. Read usage instruction at this link:
https://github.com/Purfview/whisper-standalone-win/discussions/337

Press any key to continue . . .

```
I literally did everything as described.

**Comment by Purfview** [comment]
That is clearly not "a blank CMD screen"... 

Just to open SE you need two mouse clicks, when here whole job from open to getting subtitles is literally one mouse click...
You can't do one mouse click ,you can't describe what you see on you monitor - I can't help you, find a person who can show you the computer usage basics.

**Comment by AuroraMartell** [comment]
> That is clearly not "a blank CMD screen"...
> 
> Just to open SE you need two mouse clicks, when here whole job from open to getting subtitles is literally one mouse click... You can't do one mouse click ,you can't describe what you see on you monitor - I can't help you, find a person who can show you the computer usage basics.

Maybe I worded it wrong: This screen appears when I do as described in #337 but nothing happens. I went back to SE and won't upgrade until the no text found is fixed.

**Comment by niksedk** [comment]
(SE will include 7zip unpacking in next update)

**Comment by AuroraMartell** [comment]
> (SE will include 7zip unpacking in next update)

Thank you👍

**Comment by Purfview** [comment]
>This screen appears when I do as described in https://github.com/Purfview/whisper-standalone-win/discussions/337 but nothing happens.

Not possible.

>...until the no text found is fixed.

There is nothing to fix.

**Comment by AuroraMartell** [comment]
> > This screen appears when I do as described in #337 but nothing happens.
> 
> Not possible.
> 
> > ...until the no text found is fixed.
> 
> There is nothing to fix.

I still don't know why SE throws the no text found error. Normal faster whisper works fine.

**Comment by Purfview** [comment]
>I still don't know why SE throws the no text found error. 

That's simple - because faster-whisper-xxl.exe didn't run.
But we don't know why it doesn't run as you can't describe the problem.

**Comment by AuroraMartell** [comment]
> That's simple - because faster-whisper-xxl.exe didn't run.

I see.

> But we don't know why it doesn't run as you can't describe the problem.

Not good with CLI tools since I have little luck with those.

**Comment by Purfview** [comment]
> Not good with CLI tools 

There is nothing to be good at, it's like to be good at clicking a left mouse button.

> I have little luck with those.

Computer is not a casino, there is no such thing as luck in this context.

Read the links.
