### ISSUE TITLE
Transcription stopped halfway

### ISSUE THREAD

**Issue by nhan000** [Purfview/whisper-standalone-win#36]
I downloaded this 27 min [Youtube video](https://www.youtube.com/watch?v=V5cqI4LKPko) (uploaded it [here](https://drive.google.com/file/d/1VNaG_HK1zYecwI9lTfcn5HnGsGmcdLTC/view?usp=sharing)). 

I run the transcription using this code
`whisper-faster "C:\Users\ntnha\Videos\4K Video Downloader\Carl Sagan Astronomer of the People.mp4" --language en --model large-v2 --batch_recursive true`

and it stopped at `[13:15.860 --> 13:18.860]  His greatest achievement was just around the corner.`

I downloaded the mp3 file from that YouTube video (uploaded it [here](https://drive.google.com/file/d/1QI0JxXckRLQ6oKe5nP3YZe2H2O7w04jr/view?usp=sharing))
`whisper-faster "C:\Users\ntnha\Videos\4K Video Downloader\Carl Sagan Astronomer of the People.mp3" --language en --model large-v2 --batch_recursive true`

and it was able to run to `[26:44.760 --> 26:46.180]  might have been enough.`

Interestingly, it didn't transcribe the advertisement at the beginning and at the end of the video.

**Comment by Purfview** [comment]
Check if .srt subtitle file is created.

**Comment by nhan000** [comment]
The srt file was created and the later half was missing, same as the timestamp in the command prompt.

**Comment by Purfview** [comment]
Do you run it on cuda? Try `--compute_type=int8` parameter.

**Comment by nhan000** [comment]
I added the parameter you gave me, so the code is

`whisper-faster "C:\Users\ntnha\Videos\4K Video Downloader\Carl Sagan Astronomer of the People.mp4" --language en --model large-v2 --batch_recursive true --compute_type=int8`

It ran on cuda
![image](https://github.com/Purfview/whisper-standalone-win/assets/85216095/d0360802-d906-475a-8bd5-5b78ce65307d)

And it still stopped at the same location

![image](https://github.com/Purfview/whisper-standalone-win/assets/85216095/3237ce30-21be-4789-a0ac-1c3ef2df1252)

**Comment by Purfview** [comment]
I reproduced this issue on my side. Later I'll check what can be done about it.
Interestingly, this hallucination starts on the advertisement.

**Comment by nhan000** [comment]
Thanks for looking into this, and separately, thanks for making this program. Very noob-friendly for people who are not very techy like me.

**Comment by nhan000** [comment]
Thanks for looking into this, and separately, thanks for making this program. Very noob-friendly for people who are not very techy like me.

The video has 3 advertisement segment:

- One at the beginning that Whisper Standalone doesn't transcribe for both mp4 and mp3 files.
- One at the middle (13:19) that it transcribes in the mp3 file but stopped for the mp4 file.
- One at the end (26:46) that it also doesn't transcribe in the mp3 file.

**Comment by Purfview** [comment]
It doesn't stuck with `-beam_size=5` option.

Ad at start/end is still ignored, probably models are trained to ignore that ad. Btw tiny and base models transcribe that ad.

**Comment by nhan000** [comment]
Thanks a lot! I will keep the beam size parameter in mind and change it around when I ran into issues.
