### ISSUE TITLE
compute type warning float16

### ISSUE THREAD

**Issue by softlypink** [Purfview/whisper-standalone-win#37]
>  [ctranslate2] [thread 6280] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.

Ran large-v2 downloaded by your program. Command was "--language English --model large -f srt". I didn't have this issue with older releases. CUDA is fine, cuBLAS and cuDNN libs in whisper folder. Please help

**Comment by Purfview** [comment]
Help with what? This is just a message from ctranslate2, not an error.

**Comment by softlypink** [comment]
Oh, so nothing is wrong? My bad, sorry. I'm not good at tech and never saw it before so I thought something was wrong.

Thank you for making this program.

**Comment by Purfview** [comment]
From r134.7 this message is hidden by default.
