### ISSUE TITLE
help with log

### ISSUE THREAD

**Issue by nielka98** [Purfview/whisper-standalone-win#371]
Hi, Merry Christmas! It's your most annoying scatterbrain in the world. I can't figure out what went wrong – as usual, after the SE update, there's something I don't understand. I thought I needed to update CUDA, but I did that already. I have a copy of CUDA on an external drive, but that doesn't work either. Could you help me? I know this is probably something trivial, and you'll be annoyed that I'm texting and wasting your time, but I really need help. Thanks!

This only happens when I use the command: --device cuda. On CPU, it works fine.

[whisper_log.txt](https://github.com/user-attachments/files/18262566/whisper_log.txt)

**Comment by nielka98** [comment]
Alright, a small update. I figured out what the problem is. I'm already downloading new drivers, but for the life of me, I have no idea where to put them.

**Comment by nielka98** [comment]
a day later the problem was solved

**Comment by Purfview** [comment]
> a day later the problem was solved

Merry Christmas! 
How you solved it?

**Comment by nielka98** [comment]
with the help of GPT chat you had to update your graphics card drivers
