### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by eagleftw023** [Purfview/whisper-standalone-win#4]
hi i use large-v1 because it has more accuracy than large v2
i get this loop 
 --> 01:50:20,070
line

2626
01:50:20,070 --> 01:50:22,070
line

2627
01:50:22,070 --> 01:50:24,070
line

2628
01:50:24,070 --> 01:50:26,070
line

2629
01:50:26,070 --> 01:50:28,070
line

2630
01:50:28,070 --> 01:50:30,070
اخواني

2631
01:50:30,070 --> 01:50:32,070
اخواني

2632
01:50:32,070 --> 01:50:34,070
shot

2633
01:50:34,070 --> 01:50:36,070
shot

2634
01:50:36,070 --> 01:50:38,070
shot

2635
01:50:38,070 --> 01:50:40,070
shot

2636
01:50:40,070 --> 01:50:42,070
shot

2637
01:50:42,070 --> 01:50:44,070
shot

2638
01:50:44,070 --> 01:50:46,070
shot

2639
01:50:46,070 --> 01:50:48,070
shot

2640
01:50:48,070 --> 01:50:50,070
shot

2641
01:50:50,070 --> 01:50:52,070
shot

2642
01:50:52,070 --> 01:50:54,070
shot

2643
01:50:54,070 --> 01:50:56,070
shot

2644
01:50:56,070 --> 01:50:58,070
shot

2645
01:50:58,070 --> 01:51:00,070
shot

2646
01:51:00,070 --> 01:51:02,070
shot

2647
01:51:02,070 --> 01:51:04,070
shot

2648
01:51:04,070 --> 01:51:06,070
shot

2649
01:51:06,070 --> 01:51:08,070
shot

2650
01:51:08,070 --> 01:51:10,070
shot

2651
01:51:10,070 --> 01:51:12,070
shot

2652
01:51:12,070 --> 01:51:14,070
shot

2653
01:51:14,070 --> 01:51:16,070
shot

2654
01:51:16,070 --> 01:51:18,070
shot

2655
01:51:18,070 --> 01:51:20,070
shot

2656
01:51:20,070 --> 01:51:22,070
shot

2657
01:51:22,070 --> 01:51:24,070
shot

2658
01:51:24,070 --> 01:51:26,070
shot

2659
01:51:26,070 --> 01:51:28,070
shot

2660
01:51:28,070 --> 01:51:30,070
shot

2661
01:51:30,070 --> 01:51:32,070
shot

2662
01:51:32,070 --> 01:51:34,070
shot

2663
01:51:34,070 --> 01:51:36,070
shot

2664
01:51:36,070 --> 01:51:38,070
shot

2665
01:51:38,070 --> 01:51:40,070
shot

2666
01:51:40,070 --> 01:51:42,070
shot

2667
01:51:42,070 --> 01:51:44,070
shot

2668
01:51:44,070 --> 01:51:46,070
shot

2669
01:51:46,070 --> 01:51:48,070
shot

2670
01:51:48,070 --> 01:51:50,070
shot

2671
01:51:50,070 --> 01:51:52,070
shot

2672
01:51:52,070 --> 01:51:54,070
shot

2673
01:51:54,070 --> 01:51:56,070
shot

**Comment by Purfview** [comment]
Can you share a sample to reproduce this?
Is it same if you use `--beam_size 5`?

**Comment by eagleftw023** [comment]
Yes it the same thing
The video is 2hr how can i send it

**Comment by Purfview** [comment]
Video is not needed, just audio. And you can cut just a snipped where problem happens.

**Comment by eagleftw023** [comment]
here is the [audio](https://drive.google.com/file/d/1OH1eBf4Zs1elWg3TS-swqGEReF8aBlDv/view?usp=sharing)
when i tried with --beam_size 5 the loop occur in different time in audio so i upload the full audio

**Comment by Purfview** [comment]
This is wav file, share the original without reencode.

**Comment by eagleftw023** [comment]
i will send the original video i dont know how to send just the audio 
[video](https://drive.google.com/file/d/1scprAVRvUtES7KqPr0NZrbgnwwB4u3Uy/view?usp=sharing)

**Comment by Purfview** [comment]
Can't reproduce it with Faster-Whisper:
`whisper.exe --language Arabic --device cpu --model "large-v2" --vad_filter False "D:\test_01.49.37_01.50.57.mkv"`

Sample:  https://we.tl/t-fUVLMGZRTd
Result: https://pastebin.com/e7kGA25x

**Comment by eagleftw023** [comment]
You mean that fast_whispsr cannnot do transcription to this audio?
+I use gpu

**Comment by Purfview** [comment]
I meant that I can't reproduce your looping result.
I don't have GPU with CUDA.

**Comment by Purfview** [comment]
Can you reproduce this loop on my shared sample?

**Comment by eagleftw023** [comment]
https://pastebin.com/KUvbVVg3
i think the loop occur in longer audio files

**Comment by Purfview** [comment]
Try to isolate that loop in a shorter sample. You can cut videos with programs like Avidemux and ect...

You can try `--condition_on_previous_text False`.
