### ISSUE TITLE
Library cublas64_11.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by ymilv** [Purfview/whisper-standalone-win#43]
Windows 11, Nvidia CUDA Toolkits has been installed, and CUDA path has been added to Windows Path, but it cann't work.

**Comment by Purfview** [comment]
You need:
CUDA v11.x: https://developer.nvidia.com/cuda-toolkit
cuDNN v8.x: https://developer.nvidia.com/cudnn

Or alternatively you can download libs from there: https://github.com/Purfview/whisper-standalone-win/releases/tag/libs
