### ISSUE TITLE
CUDA failed with error out of memory

### ISSUE THREAD

**Issue by Purfview** [Purfview/whisper-standalone-win#50]
### Discussed in https://github.com/Purfview/whisper-standalone-win/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **salsavalencia2000** August  1, 2023</sup>
Notified you of the following problem.

You can put the option that it can work with CPU instead of detecting it automatically.

D:\Programacion\DELPHI\JJ 2023\Win32\Debug>w.exe "D:\Programacion\DELPHI\JJ 2023\Win32\Debug\1.ts" --model=large-v2

Standalone Faster-Whisper r141.3 running on: CUDA

Traceback (most recent call last):
File "D:\whisper-fast_main_.py", line 638, in
File "D:\whisper-fast_main_.py", line 529, in cli
File "faster_whisper\transcribe.py", line 125, in init
RuntimeError: CUDA failed with error out of memory
[16468] Failed to execute script 'main' due to unhandled exception!</div>

**Comment by Purfview** [comment]
That means that there is not enough VRAM.
How much memory you need depends from a model size and compute_type used.
You can check what compute type is used with `--verbose=true`.

For example, large & float32 needs ~8GB VRAM, large & int8 needs ~4GB.

**Comment by Purfview** [comment]
@salsavalencia2000
That means that there is not enough VRAM.
How much memory you need depends from a model size and compute_type used.
You can check what compute type is used with `--verbose=true`.

For example, large & float32 needs ~8GB VRAM, large & int8 needs ~4GB.

**Comment by salsavalencia2000** [comment]
But can you say that it does it by CPU?
Because he automatically goes directly to CUDA .

**Comment by salsavalencia2000** [comment]
Because when I run it in a Virtual Windows, since it doesn't have CUDA, it works perfectly, it directly takes CPU, does it have an option to tell it to take CPU compulsorily?

**Comment by Purfview** [comment]
By default it works on GPU if CUDA is detected, you can set it to CPU with `--device=cpu`.
Use `--help` to see all the options.

**Comment by salsavalencia2000** [comment]
One last question is that I don't know if it is possible that your project has the option to translate only one txt to another language?

**Comment by Purfview** [comment]
It's model only for audio to text.
