### ISSUE TITLE
Add normal .zip file for releases

### ISSUE THREAD

**Issue by niksedk** [Purfview/whisper-standalone-win#51]
Hi @Purfview ,

Could you add a .zip file to your releases?
That would make it easier to download from inside Subtitle Edit, if that's okay with you? :)

**Comment by Purfview** [comment]
I can, no difference for Whisper-Faster as it's already compressed exe.
Can't SE unpack 7z archives? How SE finds what to download?

**Comment by niksedk** [comment]
No, SE cannot unpack 7z  archives, sorry.

I normally just hardcode download urls in SE (incl. a hash value)

**Comment by Purfview** [comment]
URLs like this:
` ...Purfview/whisper-standalone-win/releases/download/faster-whisper/Whisper-Faster_r141.4.7z`?

Then I guess you need tag and filename to be constant?
What about .zip with lzma compression?

**Comment by Purfview** [comment]
Attached .zip file for Whisper-Faster, test if it works.

Do you need same for cuBLAS and cuDNN. What about Whisper-OpenAI?

**Comment by niksedk** [comment]
Could you make the zip file with zip Compression.Deflate ?  I cannot unpack the current .zip file via C#.

>Then I guess you need tag and filename to be constant?

Actually, you a version with each release would be best.

**Comment by niksedk** [comment]
Version in the filename is perfect :)
