### ISSUE TITLE
Suggestionç Save TXT without subtitle time stamps

### ISSUE THREAD

**Issue by AdKiller** [Purfview/whisper-standalone-win#55]
Suggestion, please also save plain text without timestamps.

**Comment by Purfview** [comment]
You can do that already -> `-o=text`.

**Comment by AdKiller** [comment]
> You can do that already -> `-o=text`.

I used that switch and the output was placed in a sub folder called text, but it is still an srt file with time stamps.

**Comment by Purfview** [comment]
Sorry my bad, the right parameter is this: `-f=text`

**Comment by AdKiller** [comment]
> Sorry my bad, the right parameter is this: `-f=text`

That works, thanks a lot!
