### ISSUE TITLE
Add normal .zip file download of cuBLAS and cuDNN libs

### ISSUE THREAD

**Issue by niksedk** [Purfview/whisper-standalone-win#58]
Hi @Purfview,

Could you possibly also add a normal .zip file for CUDA libs for Faster Whisper?

**Comment by niksedk** [comment]
Thx :)

Added in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

Just in the context menu for now: 
![image](https://github.com/Purfview/whisper-standalone-win/assets/1261331/47d71219-8922-46c0-a34d-f789260ada0a)


+ if you get no text and the result contains "running on: CUDA", SE will prompt for download.

I don't suppose there is an easy way to check for CUDA support?

**Comment by Purfview** [comment]
> I don't suppose there is an easy way to check for CUDA support?

I don't know what .NET Framework can do.
I could add such option, something like `--checkcuda`, you could run .exe after download and get "CUDA found" or "CUDA not found".

**Comment by niksedk** [comment]
> > I don't suppose there is an easy way to check for CUDA support?
> 
> I don't know what .NET Framework can do. I could add such option, something like `--checkcuda`, you could run .exe after download and get "CUDA found" or "CUDA not found".

That would be nice :)

**Comment by Purfview** [comment]
I've added this option to `r145.2`, usage -> `whisper-faster.exe --checkcuda`.

If no CUDA devices are found then it will produce  `CUDA device: 0` message.

**Comment by niksedk** [comment]
He, I get the `CUDA device: 0` but that was expected... what is returned if CUDA is found/supported?

**Comment by Purfview** [comment]
Higher number than 0. Depends from how many CUDA GPUs are on a system.

**Comment by niksedk** [comment]
OK, hopefully implemented in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by Purfview** [comment]
I can't test it too. :)
Maybe someone will respond there: https://github.com/SubtitleEdit/subtitleedit/issues/7217#issuecomment-1679323902

**Comment by niksedk** [comment]
He, I thought I was the only one without a fancy graphics card.

**Comment by Purfview** [comment]
I have a desktop with CUDA GPU but it's collecting dust in the attic. :)

Btw, what about a progress bar implementation? Can you catch it as system `title` commands or you would need them printed as messages?

**Comment by niksedk** [comment]
Hm, I don't seem to be able to get the title... (the process.MainWindowTitle is empty)

**Comment by Purfview** [comment]
Maybe because of multiple "whisper-faster.exe" processes.
Maybe there is some info: https://bytes.com/topic/net/answers/855274-getting-child-windows-using-process-getprocess

Later I'll make some test release with a printed progress bar.

**Comment by niksedk** [comment]
Hm, the progress is somewhat working already:

![image](https://github.com/Purfview/whisper-standalone-win/assets/1261331/aca3fbb7-e1db-4163-8b1d-70e8f436d135)

**Comment by Purfview** [comment]
Nice,  so what was the issue? Do you take "Time remaining" from the progress bar?

I almost finished "printing it" implementation, need to think about some hack for "100%", it wasn't needed for the title as it resets after .exe is finished anyway. Atm, the progress bar can end not necessarily on "100%" because of no-speech at the end.

**Comment by Purfview** [comment]
@niksedk Check `r145.3` for `--print-progress`.
