### ISSUE TITLE
Add version/commit info to releases

### ISSUE THREAD

**Issue by jpenney** [Purfview/whisper-standalone-win#6]
Could you please add the info for what versions or commits of whisper/whisper-faster your standalone builds are based on?

It’s helpful if issues are encountered to be able to check if they’re known/addressed upstream.

**Comment by Purfview** [comment]
"b103" <- this number in version means what is the last commit included.

**Comment by jpenney** [comment]
I was expecting something like:

- openai/whisper@c09a7ae
- guillaumekln/faster-whisper@d889345

**Comment by Purfview** [comment]
Here you go: https://github.com/Purfview/whisper-standalone-win/releases
