### ISSUE TITLE
Could not load library cudnn_ops_infer64_8.dll. Error code 126

### ISSUE THREAD

**Issue by Purfview** [Purfview/whisper-standalone-win#62]
### Discussed in https://github.com/Purfview/whisper-standalone-win/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **evanarnoldi** August 19, 2023</sup>
Hi! It seems there are problem in locating the CUDnn files, even though I've properly installed them all. Is there a way of solving this issue? I tried putting the library in the whisper-faster file, but it doesn't work at all.</div>

**Comment by Purfview** [comment]
@evanarnoldi make a screenshot of the folder where whisper-faster.exe is.

**Comment by evanarnoldi** [comment]
![image](https://github.com/Purfview/whisper-standalone-win/assets/115683729/fbc7c43e-795e-408d-b1c2-e4e0cc191476)
here is the screenshot, the bin, include and lib is the cUDNN files

**Comment by Purfview** [comment]
cuBLAS and cuDNN files needs to be in the same folder where exe is.
