### ISSUE TITLE
Skip files if it already has subtitles

### ISSUE THREAD

**Issue by deadcoder0904** [Purfview/whisper-standalone-win#64]
I used recursive on a folder.

It has 7 videos.

4 of them already have `.srt` files yet it still generates for it.

I'd rather have it skip them if the filename & subtitle name match.

for eg, if i have 3 videos in a folder like;

```
a.mp4
a.srt
b.mp4
b.srt
c.mp4
```

only generate subtitles for 1 video like:

```
c.mp4
```

Doesn't make sense to do everyone.

I think this should be on by default & someone can switch it off with a flag if they want to regenerate subtitles for everything.

**Comment by Purfview** [comment]
Use `--skip`.
