### ISSUE TITLE
Faster-Whisper crash  - ucrtbase.dll

### ISSUE THREAD

**Issue by burrinhoMAC** [Purfview/whisper-standalone-win#66]
I tried to transcribe audio to text from a video. The Faster-Whisper setting only transcribes 1 minute of video. I tried medium and large models with the same result.

The base model works fine in Faster-Whisper setting.

The medium model works fine in CPP.

I tried to reinstall the Microsoft Visual C++ Redistributable with this tool below, but without success. The application only transcribes the first minute of the video.

https://github.com/abbodi1406/vcredist

Thanks for your help.

**Comment by Purfview** [comment]
**Here I brought relevant bits from your other post:*

`SE: 3.6.13.823 - Microsoft Windows NT 10.0.22621.0 - 64-bit`
`Standalone Faster-Whisper r146 running on: CUDA`
`[00:15.970 --> 00:21.870] It really is fascinating, the path that my father chose in order to become an actor`

Crash report from "Event Viewer":
```
Log Name: Application
Source: Application Error
Date: 08/28/2023 16:58:05
Event ID: 1000
Task Category: Application crash events
Level: Error
Key words:
User: xxxxx
Computer: xxx
Description:
Faulting application name: whisper-faster.exe, version: 146.0.0.0, timestamp: 0x64ebe44d
Faulting module name: ucrtbase.dll, version: 10.0.22621.608, timestamp: 0xf5fc15a3
Exception code: 0xc0000409
Fault offset: 0x000000000007f61e
Failing Process ID: 0x0x3F4D4
Faulting application start time: 0x0x1D9D9E9E6D8E740
Faulting Application Path: C:\PORTABLE\SubtitleEditBeta (2)\Whisper\Purfview-Whisper-Faster\whisper-faster.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
```

**Comment by Purfview** [comment]
Could you test if it crash when running in console like this:
`whisper-faster.exe "C:\yourvideo.mkv" --language en --model=medium.en --verbose=true`

And post what it shows at the end if it crash.

**Comment by burrinhoMAC** [comment]
![2023-08-29_224604](https://github.com/Purfview/whisper-standalone-win/assets/110316011/02ccf89a-e31d-45a6-a85b-1cc1b578a8cb)

**Comment by Purfview** [comment]
I'm not interested in SE tests. You need to run it alone in console.

**Comment by burrinhoMAC** [comment]
[PowerShell 7.2.13.txt](https://github.com/Purfview/whisper-standalone-win/files/12478157/PowerShell.7.2.13.txt)

**Comment by burrinhoMAC** [comment]
I updated the Powershell.

It transcribe 3 minutes:
[PowerShell 7.3.6.txt](https://github.com/Purfview/whisper-standalone-win/files/12478293/PowerShell.7.3.6.txt)

**Comment by Purfview** [comment]
Your GPU is `NVIDIA GeForce GT 1030`, is that 2GB model?

**Comment by Purfview** [comment]
Hmm, strange that you don't get "out of memory error", you can't run those models on such low VRAM.
For example `medium` needs at least 4GB.

**Comment by Purfview** [comment]
Can you test `small` model?

**Comment by Purfview** [comment]
I think `medium` could work on 2GB. Maybe try to close all other programs using GPU, like internet browsers.

If that doesn't help try to run  `-l=en -m=medium.en -bs=1 -bo=1 --temperature_increment_on_fallback=None`

Btw, try to run `large` model to see if it crash abruptly without any error too.

**Comment by Purfview** [comment]
I'm still interested in the tests mentioned in the above post.

Anyway, solution is to use CPU with `--device=cpu` if you have low VRAM GPU and want to run larger models.
