### ISSUE TITLE
Don't stop batch processing when some file fails

### ISSUE THREAD

**Issue by KyNicholas** [Purfview/whisper-standalone-win#67]
hi,

i'm using batch processing to transcribe multiple files. however, i've run into an issue with some mp3 files related to a setting called "compute_type." to fix this, i need to change "compute_type" to either float16, int8, or float32, depending on the file.

my problem is that when there's an error with one mp3 file, the **whole batch processing stops**. is there a way to make it **skip** the problematic file and continue with the next one instead of stopping the entire application?

thanks.

**Comment by Purfview** [comment]
> i've run into an issue with some mp3 files

What issue? Can you share audio sample with the issue?

Btw, could you post [there](https://github.com/Purfview/whisper-standalone-win/issues/46) how you solved your [%1 is not a valid win32 application](https://github.com/Purfview/whisper-standalone-win/issues/46) issue?

**Comment by Purfview** [comment]
>my problem is that when there's an error with one mp3 file, the whole batch processing stops. is there a way to make it skip the problematic file and continue with the next one instead of stopping the entire application?

Then process files one by one: `for %i in (*.mkv) do whisper-faster.exe --language=en --model=medium %i`

**Comment by Purfview** [comment]
Implemented in r160.7 as --check_files switch.
