### ISSUE TITLE
Punctuation Missing on Some Files

### ISSUE THREAD

**Issue by wwaag76** [Purfview/whisper-standalone-win#68]
Just ran WF on roughly 90 voice recording wav files using large-v2 and beam size of 5.  The accuracy of the transciption was great given the noisy environment of the recording and a faulty Zoom recorder.  Also some very unusual words such a "hyderized" or "Takkakaw" were transcribed correctly to my great surprise.

However, I'd say about a 20 to 25% were missing punctuation altogether--no commas, periods, or capitaliztion of the first word in sentence.  In such instances, I reran using the Medium model and they worked OK.

Any ideas to avoid such errors in the future?  Thanks.

This really is a great tool.

**Comment by Purfview** [comment]
Read and post there: https://github.com/Purfview/whisper-standalone-win/discussions/45
