### ISSUE TITLE
save transcriptions half-way

### ISSUE THREAD

**Issue by deadcoder0904** [Purfview/whisper-standalone-win#70]
i have a huge 2-hour video that takes around 5-6 hours or more.

i sometimes finish only 1 hour of video midway so i'd like it to save half-way.

on the next day, i can restart it again from half-way.

idk if this is the right repo for that but would like to request this feature.

probably have to change `--skip` logic for this.

very rare scenario probably but i have large videos now. all around 2 hours that dont finish before i close my computer.

ideally, i can only do it if i start the process in the morning & only then if my chances are bright, it will be done.

**Comment by Purfview** [comment]
> i'd like it to save half-way. on the next day, i can restart it again from half-way.

Here won't be such feature.

> i have large videos now

You don't need video tracks at all, you can remux file for example with MKVToolNix, select only audio track.
Then with same MKVToolNix you can split a file to the shorter parts if you want to process file in parts.

**Comment by deadcoder0904** [comment]
cool, i'll probably spend $10 online on gpu's or tpu's :)
