### ISSUE TITLE
Add postfix to subtitle's filename

### ISSUE THREAD

**Issue by juntaosun** [Purfview/whisper-standalone-win#71]
Save file name format，For example :

Input: C:/Users/myname/Desktop/audio.mp3
Options: --language=Chinese
The output now is: audio.srt
I want the output to be: audio_Chinese.srt

Options: --language=en
I want the output to be: audio_en.srt

Options: --language=Japanese
I want the output to be: audio_Japanese.srt

The recommended saved file name is: filename_language.xxx
`
filename _ language .  xxx
`
This facilitates output management in different languages, 
rather than directly overwriting files with the same name.
This project is very good, 
I have been using it and hope to see updates in the next version.

-----------------------------------------------------------------------------

（Chinese using Google Translate）中文使用谷歌翻译

保存文件的名称格式，举例说明：

输入：C:/Users/myname/Desktop/audio.mp3
选项：--language=Chinese
现在的输出是：audio.srt
我希望输出是：audio_Chinese.srt

选项：--language=en
我希望输出是：audio_en.srt

选项：--language=Japanese
我希望输出是：audio_Japanese.srt

建议的保存的文件名称是：filename_language.xxx
这样方便不同语言的输出管理，而不是直接覆盖同名文件。
这个项目非常好，我一直在使用，希望下个版本能看到更新。

**Comment by juntaosun** [comment]
Of course, an option can be added to implement such a function, and the original function will be retained.

**Comment by Purfview** [comment]
Implemented `--postfix` arg in r160.
