### ISSUE TITLE
Please add support for .AMR audio files

### ISSUE THREAD

**Issue by ch826** [Purfview/whisper-standalone-win#72]
Hello, thank you for developing and releasing this wonderful program. I use it daily and prefer it over all the other programs I have tried.

I am requesting that you add support for .AMR audio files. Other Whisper speech-to-text programs support .AMR files by default. I wish I could use your program for all speech-to-text functions, and that I didn't have to switch to using one of the other (inferior) programs when processing .AMR files.

.AMR stands for Adaptive Multi-Rate Audio Codec. It is an audio file format that was specifically designed for speech audio coding and is mostly used for voice recordings and transmissions on mobile networks. It is optimized for low-bitrate voice recordings, making it useful for things like mobile phone conversations, voicemail systems, and audio messaging.

Someone might suggest, "Just convert it to another format or use a different program to encode those files", which is an option, but it would be really nice if this wasn't necessary due to the extra complexity involved. Your program is faster than those other programs, and I believe yours does a better job in processing speech to text than other solutions. I'd love to do everything from within the Whisper Standalone app.

Thank you!

**Comment by Purfview** [comment]
I just tested AMR file and `whisper-faster.exe` works fine with it.
