### ISSUE TITLE
Access Denied - This app can't run on your PC

### ISSUE THREAD

**Issue by BBC-Esq** [Purfview/whisper-standalone-win#76]
I've downloaded the .exe, the cublas and cudnn files, and run a proper command but it gives me the following error (see image):

Also, the following is what shows in the command prompt:

whisper-faster.exe "D:\Whisper - Purfview_whisper_standalonew_win\WS602300.MP3" --language=English --model=medium
Access is denied.
<img width="511" alt="error" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/54e3597e-5f35-4f3d-814c-226642aefad8">

Any ideas?  It'd be nice to use whisper-faster without having to program in Python for a change.

BTW, I'm using a command prompt in administrator mode and am making sure the folders and relevant files have the necessary permissions...

**Comment by Purfview** [comment]
On what Windows version you get that? 
Did you tried the older versions too?

**Comment by BBC-Esq** [comment]
Windows 10.  I looked at Event Viewer and didn't see an error.  However, I'm not familiar with how to use Event Viewer.  However, I did run two commands in PowerShell instead and got a little additional information...See the attached images.
<img width="771" alt="error2" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/5c0b0c7c-b757-443e-8a3f-359d9991c5c8">
<img width="866" alt="error3" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/8b21308c-d029-4a99-acc0-de5328e00a33">

**Comment by BBC-Esq** [comment]
Do you need me to resend the post...Here's the pictures...
<img width="771" alt="error2" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/3b9e406d-19a1-4452-b00e-f1741cbcdd60">
<img width="866" alt="error3" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/9b9a7476-7016-4aef-9e60-85e791d4b06f">

**Comment by BBC-Esq** [comment]
I tried both of those commands.

**Comment by Purfview** [comment]
Sorry, I restored your post.

> Windows 10

Post full version numbers & architecture please.

**Comment by BBC-Esq** [comment]
My "system" information says Version 22H2 and Windows 10 Pro and 64-bit if that is what you are needing?

**Comment by Purfview** [comment]
Yes, that's what I needed.

> I looked at Event Viewer and didn't see an error.

Maybe it's not marked as error, looks at Windows logs there

Google suggests that's it can be something with permissions or corrupted file.

Try these:
https://www.youtube.com/watch?v=MdHgIxI7-OY
https://www.makeuseof.com/how-to-fix-the-this-app-cant-run-on-your-pc-error-in-windows-10/

**Comment by Purfview** [comment]
Check checksum of the file, MD5 of r153:
f554c6054817915ed9ab6c06080f11c2 *whisper-faster.exe

**Comment by BBC-Esq** [comment]
Strange.  I downloaded the file again and unzipped it to the directory...and now the "--help" command is working.  Will test out actually running the program next.  If you don't hear from me it's working and I will close out this issue once I confirm.  I think that maybe it was partially downloaded or something?  All I know is that the little icon for whisper-faster.exe was NOT sho
<img width="17" alt="icon" src="https://github.com/Purfview/whisper-standalone-win/assets/108230321/090a4224-afd4-47c8-90db-455fc1b4a2a5">
wing before, but now it is.

**Comment by Purfview** [comment]
You should'nt be able to unzip if archive was corrupted at download.

Could be that exe was corrupted by failing HDD, RAM or maybe corrupted by virus.

**Comment by BBC-Esq** [comment]
I understand.  I'm not sure what happened, but am testing now and will let you know if the problem continues.

**Comment by BBC-Esq** [comment]
It's working now.  Thanks for your help.  Not sure why the file was corrupted or what happened exactly...

**Comment by wegylexy** [comment]
I have to stop McAfee from quarantining the exe as it thinks it contains a malicious JIT.

**Comment by Purfview** [comment]
> I have to stop McAfee from quarantining the exe as it thinks it contains a malicious JIT.

Read and post there: https://github.com/Purfview/whisper-standalone-win/discussions/91
I don't see McAfee in virustotal report.
