### ISSUE TITLE
I can't run whisper.exe from CMD for some reason

### ISSUE THREAD

**Issue by aaron2221** [Purfview/whisper-standalone-win#8]
I followed the video provided but I keep getting this error: _"'whisper.exe' is not recognized as an internal or external command,
operable program or batch file."_ my whisper.exe is located at **D:\FasterWhisper\whisper.exe** and I'm running CMD as administrator. then, I type the following: D: -> dir -> cd fasterwhisper -> whisper.exe but to no avail.

**Comment by aaron2221** [comment]
Alright I think I'm unto something. I've used that .exe with with SE and then simply moved it to D. What I did was unpack a fresh .exe from the .rar and used it instead of the one used with SE and this is what I'm getting right now: https://imgur.com/pdszJ70

**Comment by Purfview** [comment]
Probably you had it renamed to `whisper-ctranslate2.exe`.
So you needed to type `whisper-ctranslate2.exe` instead of `whisper.exe`.

**Comment by Purfview** [comment]
> am i ready to transcribe now or the audio error needs to be fixed?

Yes you can transcribe now, error is because you didn't enter any arguments to command what to do.

**Comment by aaron2221** [comment]
I did change the name from whisper-ctranslate2.exe to whisper.exe and it's weird, I tried it again and it seems like SE is doing something to that .exe because I managed to have 2 whisper.exe's at the same folder. As if SE is "corrupting" that file. Hope this helps others :)

**Comment by Purfview** [comment]
> it seems like SE is doing something to that .exe because I managed to have 2 whisper.exe's at the same folder

Having same files in same folder is not possible, so definitely you had differently named files.
You would know if you did that command I posted few posts above.
