### ISSUE TITLE
Whisper Master, Please Add Support for Hugging Face Models

### ISSUE THREAD

**Issue by lipolipo111** [Purfview/whisper-standalone-win#81]
Hi, I hope this message finds you well. I wanted to express my appreciation for the excellent work you've been doing with the Whisper Standalone Windows app.

I believe that adding support for Hugging Face models, in addition to the default ones currently supported, could significantly enhance the power and versatility of the application. I understand that implementing such a feature may require considerable effort. However, I strongly believe that this enhancement would greatly benefit the user community.

Thank you for considering my request. I look forward to any updates you might be able to provide regarding the potential for this additional feature.

**Comment by Purfview** [comment]
Custom models are already supported.

**Comment by lipolipo111** [comment]
> Custom models are already supported.

Sure, I can help with that. Here's your text with corrected grammar, spelling, and coherence:

> Custom models are already supported.

Oh, I see. The problem was that I don't know how to do it. When I tried using `--model HuggingFaceModel`, it didn't recognize it and showed me a list of default models. So, how should I go about it?

**Comment by lipolipo111** [comment]
> > When I tried using --model HuggingFaceModel, it didn't recognize it and showed me a list of default models. So, how should I go about it?
> 
> Have it in folder like this: `faster-whisper-HuggingFaceModel`

Hi,

First of all, I want to express my gratitude for all the support you've provided. It's been really helpful.

However, I'm still encountering an issue. Specifically, when I run the following command:

```bash
whisper-faster.exe "J:\Convertion\MyTestJapaneseAudio.wav" --language ja --model large-v2-japanese-5k-steps
```

I’ve downloaded the respective model and moved it into the _models folder as shown below:

> C:\Users\lipo111\AppData\Roaming\Whisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2-japanese-5k-steps

 which contains the following three files:

1.  config.json
2.  model.bin
3.  vocabulary.json

Despite this, I’m receiving an error message that the model cannot be found at the specified location:

```bash
whisper-faster.exe "J:\Convertion\MyTestJapaneseAudio.wav" --language ja --model large-v2-japanese-5k-steps

Unknown model not found at: C:\Users\lipo111\AppData\RoamingWhisper\Purfview-Whisper-Faster\_models\faster-whisper-large-v2-japanese-5k-steps

['tiny', 'tiny.en', 'base', 'base.en', 'small', 'small.en', 'medium', 'medium.en', 'large', 'large-v1', 'large-v2']
```

I’d appreciate any further assistance you could provide to resolve this issue.

Thanks again for your support.

**Comment by Purfview** [comment]
> which contains the following three files:
> 
>     1. config.json
> 
>     2. model.bin
> 
>     3. vocabulary.json

Copy there `tokenizer.json` too.

**Comment by lipolipo111** [comment]
> > which contains the following three files:
> > ```
> > 1. config.json
> > 
> > 2. model.bin
> > 
> > 3. vocabulary.json
> > ```
> 
> Copy there `tokenizer.json` too.

Actually there is no tokenizer.json in the Hugging Face model, thats why I did't copy. The model is 

zh-plus/faster-whisper-large-v2-japanese-5k-steps

[](https://huggingface.co/zh-plus/faster-whisper-large-v2-japanese-5k-steps/tree/main)

Do I have to generate the tokenizer.json or can I use one that already exist?

**Comment by Purfview** [comment]
> Do I have to generate the tokenizer.json or can I use one that already exist?

I dunno, but `tokenizer.json` is same in all default models.

**Comment by lipolipo111** [comment]
> > Do I have to generate the tokenizer.json or can I use one that already exist?
> 
> I dunno, but `tokenizer.json` is same in all default models.

Just wanted to say a big thanks! Actually I download the file `tokenizer.json` from the model `guillaumekln/faster-whisper-large-v2` and it works.

Really appreciate your help. You’re awesome!
