### ISSUE TITLE
ambiguous option error on MacOS. 

### ISSUE THREAD

**Issue by baeckerman83** [Purfview/whisper-standalone-win#86]
When startet at macos with: ./whisper-faster "test.ogg" --language=German --model=large

It is working, but I get a output of all possible options, and also an error:
whisper-faster: error: ambiguous option: -c could match -ct, -cc

I used Version  r160

Why?
Regards
Benjamin

**Comment by Purfview** [comment]
I noticed too that after it finished working macOS by itself runs it again with some "-c" arg.

No idea why.

**Comment by Purfview** [comment]
I think I solved this glitch, test`r106.1` if its good now.

**Comment by baeckerman83** [comment]
Thank you for your fast help. Now it is working fine!
