### ISSUE TITLE
It is not clear how to run this program

### ISSUE THREAD

**Issue by search620** [Purfview/whisper-standalone-win#9]
![image](https://github.com/Purfview/whisper-standalone-win/assets/56544202/e3cb8456-a8f3-4667-9754-f898328d83f9)

I click this file and popup window is open and close after 1 second and the guide in the main page are not clear of how to run this program. It will be nice if you make a short video of how to run it.

Thanks!

**Comment by Purfview** [comment]
But such video is already on the main page:

>Guide how to run the command line programs: https://www.youtube.com/watch?v=A3nwRCV-bTU

**Comment by search620** [comment]
don't be mad at me but it is not enough. if you can make it like python script that open a dialog file browse or a  simple gui with beam size, model choosing, input folder output folder. it can be great.

Because your app is supposed to be for noobs. :) and to save all the noobs the endless effort with command lines

**Comment by Purfview** [comment]
>Because your app is supposed to be for noobs. :) 

Command line programs are for noobs too. ;)

>a simple gui 

Possible, but at the moment I'm not interested in writing a GUI, maybe in future. [Don't hold your breath]

**Comment by search620** [comment]
my friend come on...

A programmer sits down to code
With GUI design as their mode
In Python they will make it shine
And create a UI so fine

The buttons, sliders, and text boxes too
Will all be easy to use and view
With Python code, it's all a breeze
To create a GUI that will please

They'll work with classes, functions, and more
To create a GUI that won't bore
The user who interacts with their code
And finds the UI so easy to behold

So let the programmer work their craft
And create a GUI that will last
With Python as their trusty tool
They'll make a UI that's cool.
