### ISSUE TITLE
cuda version outdated

### ISSUE THREAD

**Issue by Helmasko** [Purfview/whisper-standalone-win#93]
I noticed the large model wasn't working on my GPU and decided to use a more up to date cuda library and it worked. I think it'd be useful to release the newer cuda libraries.

**Comment by Purfview** [comment]
> I noticed the large model wasn't working...

What was the issue?

 > ...on my GPU

What GPU?

> ,,,up to date cuda library,,,

What library and what version?

**Comment by Helmasko** [comment]
the issue was it was outputting an empty srt file. Using verbose nothing seemed out of the ordinary, no errors, just the temperature seemed to be exactly the same every single time it outputted it to the console. GPU was 1650 mobile the library and version was the one you published on this repo

**Comment by Purfview** [comment]
> the issue was it was outputting an empty srt file. Using verbose nothing seemed out of the ordinary, no errors, just the temperature seemed to be exactly the same every single time it outputted it to the console. 

This doesn't look like the issue with libs.

>  the library and version was the one you published on this repo

I meant about those "up to date" you mentioned.

**Comment by Purfview** [comment]
Put old libs in place, run with verbose and make as screenshot of first ~minute transcribed. Do same with "up to date" libs.

**Comment by Helmasko** [comment]
v8.9.5.30_cuda11, and updating it did fix it

**Comment by Purfview** [comment]
Do as written in https://github.com/Purfview/whisper-standalone-win/issues/93#issuecomment-1788232259

Btw, I've no idea what "v8.9.5.30_cuda11" means.

**Comment by Helmasko** [comment]
literally just go on the cuda website...

**Comment by Purfview** [comment]
> literally just go on the cuda website...

They don't know what "v8.9.5.30_cuda11" means too...

**Comment by Helmasko** [comment]
I don't have time for this make up your mind, you want the screenshots or not.

**Comment by Purfview** [comment]
Don't post them if you don't have time.
