### ISSUE TITLE
--skip only recognises .srt files

### ISSUE THREAD

**Issue by xtreamrob24** [Purfview/whisper-standalone-win#94]
I ran into an issure with the --skip option:
It seems after various testing that --skip only recognises .srt files. 

To replicate the issue:
I generated a transcript in all formats with --output_format=all, then ran the same script again and it aborted with "no media found". After deleting the .srt file and running the same script, it ran the full transcription process again.

**Comment by Purfview** [comment]
That's intended behavior, check the help on `--skip`:
`"Skips files if 'srt' subtitle exists. Works if input is wildcard or directory."`

**Comment by xtreamrob24** [comment]
Oops, I missed that. Thanks!

May I ask why? ^^

**Comment by Purfview** [comment]
> May I ask why? ^^

Someone asked this feature for srt files.
Other extensions were not added probably because of additional coding or some additional code spaghetti, I don't remember...

**Comment by xtreamrob24** [comment]
Okay ^^
Would love for it to skip whatever file format you have currently put in. If I want to generate .json, just skip all with a .json and so on, you get it.
But not too important ofc, there are easy workarounds.

**Comment by Purfview** [comment]
I'll look at it.

**Comment by cagenuts** [comment]
@xtreamrob24 You could just write a simple batch file that starts with `if not exist (*.vtt)` or whatever you already have.

Or `if exist (*.vtt)` then goto label that has a command which specifies all other formats except the one in question. Something like this at least.

**Comment by Purfview** [comment]
## r160.7:
Improved `--skip` to work with all output formats. If output is "all" - checks only "srt".

**Comment by xtreamrob24** [comment]
You are amazing - thanks!
