### ISSUE TITLE
Add option to set maximum characters per line

### ISSUE THREAD

**Issue by teeaarbee** [Purfview/whisper-standalone-win#98]
It would be very useful to have a command line option in whisper-faster.exe to set the maximum number of characters allowed per line and max number of lines when generating subtitles.

Currently, the only way to limit line length is to post-process the generated .srt file in Subtitle Edit and use its "Max number of characters per line" option to split long lines.

I suggest adding a new argument like --max-characters-per-line 80 to allow controlling the maximum line length right from whisper-faster, without needing additional processing.

**Comment by Purfview** [comment]
> Currently, the only way to limit line length is to post-process the generated .srt file in Subtitle Edit and use its "Max number of characters per line" option to split long lines.

Subtitle Edit is the right way, unless it's the highlighted karaoke subtitles.

Read and post there: [Max Line Width and Max Line Count Commands ](https://github.com/Purfview/whisper-standalone-win/discussions/87)
