### ISSUE TITLE
Will large-v3 model support be in a subsequent update?

### ISSUE THREAD

**Issue by despairTK** [Purfview/whisper-standalone-win#99]
I just saw your comment on SubtitleEdit and learned about the release of the large-v3 model. This is an exciting day. Not sure if the recent update of whisper-standalone-win will support the large-v3 model. I look forward to the day of support.

have a beautiful day!

**Comment by Purfview** [comment]
Do you mean Whisper or Faster-Whisper?

**Comment by despairTK** [comment]
I mean it can be used in your project.

Do we have to wait for [faster-whisper] to convert and support the model so that [whisper-standalone-win] can support the large-v3 model?

I've also seen people trying to convert large-v3, but they all encountered some problems.

**Comment by Purfview** [comment]
There is no such program here as "whisper-standalone-win". :)
Only Whisper and Faster-Whisper.

**Comment by Purfview** [comment]
There is no problem with Whisper, but the development in original faster-whisper repo is on halt so it can take some time for it.

**Comment by despairTK** [comment]
I tried large-v3 at Whisper, and it did solve a lot of incorrectly generated words due to similar pronunciation. However, for some reason, some sentences are repeated in the neighboring subtitle lines. Most of all, Whisper is still too slow, and it doesn't have as many adjustable parameters as faster-whisper. For example, the timestamp accuracy is still not as good as faster-whisper, and the illusion is still not really solved.

I decided to wait for faster-whisper support, and I think it's worth the wait. :)

**Comment by Purfview** [comment]
Released Standalone Faster-Whisper `r160.2` with `large-v3` support. Enjoy.

**Comment by despairTK** [comment]
Great job! Thank you for your dedication!

I see that you have two large-v3's in huggingface, one with an int8 suffix and the other with a float16. and the model.bin file sizes are different for both. Is there any difference in the use of these two?

**Comment by Purfview** [comment]
int8 model is default with `large` & `large-v3`, I think the vast majority of the users are using int8 compute type anyway. That way it's faster to load and the weights are "degraded" only once.

If you want to run float16 model then you can call it with `large-v3-fp16`.

**Comment by despairTK** [comment]
Thank you for your answer!

I just ran a test, transcribing some Japanese and English videos, using the parameters I was using with large-v2's settings. There are a couple of serious problems so far.

1. easily repeated sentences.
2. inaccurate time stamps.
3. some of the audio is not transcribed.

These three situations are easy to occur in long and frequent audio where the speaker is talking a lot.
In general, the current large-v3 model has improved the selection of similarly pronounced words, but compared to large-v2, some of the normal features are problematic. And I think it's a problem with the large-v3 model itself? Or do you need to slowly adjust some parameters?
